### ISSUE TITLE
TypeResolvers

### ISSUE THREAD

**Issue by vjelic** [aaubry/YamlDotNet#101]
Hi,

I am using YamlDotNet to read my yaml files and it works excellent,
but it would be great if I could convert YamlNodes into .Net types such as int, float, string , List or Dictionary.

I can see that you have implemented TypeResolvers wich have method Resolve.
Do you have plans to continue with work on this method so that it could return .Net types?
Have you any suggestions that could help me?

Best regards,
Vladimir

**Comment by AlexanderMartinyuk** [comment]
I also had the same issue and I found a solution that suitable for me. If little bit correct the condition in the code sample provided by Antony we can ignore values in YAML document that are quoted and should not be converted to simple types such as bool or int.
So, `if (scalar != null)` we should replace on `if (scalar != null && !scalar.IsQuotedImplicit)` and all works fine!
