### ISSUE TITLE
Add YamlPropertyName attribute

### ISSUE THREAD

**Issue by totpero** [aaubry/YamlDotNet#1011]
Hi, 
I have this scenario:
In my project I have Yaml files with some poperties like this: https://github.com/totpero/DeviceDetector.NET/blob/master/DeviceDetector.NET.Tests/fixtures/unknown.yml#L3235
And when I try to deserialize this into object I get this error:  `Property 'http-x-requested-with' not found on type `

It will be nice like in Json serialize/deserialize library to some attribute like `YamlPropertyNameAttribute` and add this on my proprieties like this:

```
[YamlPropertyName("http-x-requested-with")]
public string http_x_requested_with { get; set; }
```

Because now I can't add property with the name `http-x-requested-with`

Thanks

**Comment by EdwardCooke** [comment]
We already have this ability with the YamlMember attribute. Just set the alias and you should be good. I recommend not using a naming convention when using the attribute to avoid weird issues with name conversions. Let me know if this doesn’t work for you.

**Comment by totpero** [comment]
This help me, thanks 👍
