### ISSUE TITLE
WithEnforceNullabilty() has unpredictable behavior with classes having both nullable reference type and value type

### ISSUE THREAD

**Issue by popemkt** [aaubry/YamlDotNet#1018]
**Describe the bug**

When deserializing to a class with both nullable reference and value types members, YamlDotNet considers the nullabe value type to not accept null values. 

I suspect it's coming from the reflection checks only checking if a member allows null using the presence of `NullableAttribute`, which fails if it's a `TValueType?` (this won't generate a `NullableAttribute`). But I've seen strange cases where the compiler doesn't even generate `NullableAttribute `on a reference type, so I won't be too sure about that.

**To Reproduce**
Using latest version: 16.2.1

Create a new console project with .net8
**Program.cs**
```
#nullable enable
using YamlDotNet.Serialization;

var deserializer = new DeserializerBuilder().WithEnforceNullability().Build();
var yaml = @"
TestString: null
TestBool: null
";
var test = deserializer.Deserialize<NonNullableClass>(yaml);

public class NonNullableClass
{
    public string? TestString { get; set; }
    public bool? TestBool { get; set; }
}
```
Result:

`Unhandled exception. (Line: 2, Col: 1, Idx: 2) - (Line: 2, Col: 11, Idx: 12): Strict nullability enforcement error.
`

**Comment by popemkt** [comment]
Update, the example will give an error when I use the exact setup as in [one of the tests](https://github.com/aaubry/YamlDotNet/blob/7bed5cf0750c7ca58ba69ad8c07f6eb136080540/YamlDotNet.Test/Serialization/DeserializerTest.cs#L377-L396), so only a nullable reference type 

```
#nullable enable
using YamlDotNet.Serialization;

var deserializer = new DeserializerBuilder().WithEnforceNullability().Build();
var yaml = @"
TestString: null
";
var test = deserializer.Deserialize<NonNullableClass>(yaml);

public class NonNullableClass
{
    public string? TestString { get; set; }
}
```
Result:  `Unhandled exception. (Line: 2, Col: 1, Idx: 2) - (Line: 2, Col: 11, Idx: 12): Strict nullability enforcement error.
`
Here's the lowered version of the class (no `NullableAttribute` on the property)
```
[NullableContext(2)]
[Nullable(0)]
public class NonNullableClass
{
  [CompilerGenerated]
  [DebuggerBrowsable(DebuggerBrowsableState.Never)]
  private string <TestString>k__BackingField;

  public string TestString
  {
    [CompilerGenerated] get
    {
      return this.<TestString>k__BackingField;
    }
    [CompilerGenerated] set
    {
      this.<TestString>k__BackingField = value;
    }
  }

  public NonNullableClass()
  {
    base..ctor();
  }
}
```

I think this is because way the compiler generate `NullableAttribute` is really unreliable to base the checks on.

**Comment by EdwardCooke** [comment]
I’m not at a computer for a bit. But. In your second example, what happens when you put a non nullable, no question mark, string in there? What is generated? I wonder if there’s an optimization where if all properties/members are nullable then it only puts the nullable attributes at the class level and not on individual properties and fields. That’s just a guess though.

**Comment by popemkt** [comment]
I guess you might be right,
Here's the version without `?`
```
[NullableContext(1)]
[Nullable(0)]
public class NonNullableClass
{
  [CompilerGenerated]
  [DebuggerBrowsable(DebuggerBrowsableState.Never)]
  private string <TestString>k__BackingField;

  public string TestString
  {
    [CompilerGenerated] get
    {
      return this.<TestString>k__BackingField;
    }
    [CompilerGenerated] set
    {
      this.<TestString>k__BackingField = value;
    }
  }

  public NonNullableClass()
  {
    this.<TestString>k__BackingField = "Default";
    base..ctor();
  }
}
```

**Comment by popemkt** [comment]
@EdwardCooke did you have any time to look at this?

**Comment by EdwardCooke** [comment]
Thanks for the reminder. I just did some digging. Looks like there is some optimization that happens with nullable properties at the compiler level.

https://github.com/dotnet/roslyn/issues/39133

I have implemented the required changes so we should be good once I cut a release for it.
