### ISSUE TITLE
IYamlTypeConverter and FullObjectGraphTraversalStrategy do not seem to work well together

### ISSUE THREAD

**Issue by atruskie** [aaubry/YamlDotNet#103]
Hi,

I'm currently trying to create a custom type converter for my code. In particular I'm trying to serialize and deseralize `FileInfo` and `DirectoryInfo` types. Serializing these types is just a convenience - we are working around needing to serialize them at all with proxy properties.

But, after registering my attempt at a custom converter, I still get the same exception as I did without registering the converter. 

The root cause, is that the FileInfo type has an infinite/recursive object graph - triggering the traversal exception. Debugging the problem, I found that the `FullObjectGraphTraversalStrategy` class does not take into consideration the custom converters... and traverses down the type anyway.

I think, the correct behaviour should be more like: if the current type is handled by a custom converter, it should be treated as a ?`scalar`? and the object graph should not be traversed down further for that node.

I'd be happy to help patch/add this behaviour (if you desire) but I need a few hints... I'm not quite sure where I should put this custom converter check (or what the resulting type should be).

Btw, this is a fantastic project, I appreciate the hard work of all the contributors!

**Comment by agc93** [comment]
Was there an update or solution to this issue? I recently ran into the same thing trying to serialize a `FileInfo` object. Will registering an `IYamlTypeConverter` implementation work?

**Comment by atruskie** [comment]
@agc93 - at least from my end I never worked out how to get past this problem. I just used `[YamlIgnore]` on the `FileInfo` properties and added additional proxy properties that exposed the `FullName` as a string.

**Comment by Beatsleigher** [comment]
This is a five year-old issue and it hasn't even been looked at by @aaubry 
That's kind of sad, actually.

**Comment by aaubry** [comment]
This has been fixed for a while, although I can't say for sure when. It is just this issue that did not get updated. This was probably tracked in a different issue. The following code works as expected:

```c#
using System;
using System.IO;
using YamlDotNet.Core;
using YamlDotNet.Core.Events;
using YamlDotNet.Serialization;

namespace SerializeFileInfo
{
    class Program
    {
        static void Main(string[] args)
        {
            var serializer = new SerializerBuilder()
                .WithTypeConverter(new FileInfoTypeConverter())
                .Build();

            var file = new FileInfo(@"c:\Windows\notepad.exe");

            serializer.Serialize(Console.Out, new { file });
        }
    }

    public class FileInfoTypeConverter : IYamlTypeConverter
    {
        public bool Accepts(Type type) => type == typeof(FileInfo);

        public object ReadYaml(IParser parser, Type type)
        {
            var scalar = parser.Expect<Scalar>();
            return new FileInfo(scalar.Value);
        }

        public void WriteYaml(IEmitter emitter, object value, Type type)
        {
            var fileInfo = (FileInfo)value;
            emitter.Emit(new Scalar(fileInfo.FullName));
        }
    }
}
```

@Beatsleigher I don't have enough time to review all issues and sort them out, but if you want to help, you're welcome :)

**Comment by Beatsleigher** [comment]
@aaubry Sorry, the harsh comment was out of frustration. But at least it got your attention ;)

I ended up mimicking your code from the repository:

DirInfoConverter:
`using System.IO;
    using YamlDotNet.Core;
    using YamlDotNet.Core.Events;
    using YamlDotNet.Serialization;

    public class DirInfoConverter : IYamlTypeConverter {

        /// <summary>
        /// Gets a value indicating whether the current converter supports converting the specified type.
        /// </summary>
        /// <param name="type"></param>
        /// <returns></returns>
        public bool Accepts(Type type) => type == typeof(DirectoryInfo);

        /// <summary>
        /// Reads an object's state from a YAML parser.
        /// </summary>
        /// <param name="parser"></param>
        /// <param name="type"></param>
        /// <returns></returns>
        /// <exception cref="InvalidDataException">Invalid YAML content.</exception>
        public object ReadYaml(IParser parser, Type type) {
            var value = ((Scalar)parser.Current).Value;
            parser.MoveNext();
            return new DirectoryInfo(value);
        }

        /// <summary>
        /// Writes the specified object's state to a YAML emitter.
        /// </summary>
        /// <param name="emitter"></param>
        /// <param name="value"></param>
        /// <param name="type"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteYaml(IEmitter emitter, object value, Type type) {
            emitter.Emit(new Scalar(null, null, (value as DirectoryInfo).FullName, ScalarStyle.Any, true, false));
        }
    }`

FileInfoConverter:
`using System.IO;
    using YamlDotNet.Core;
    using YamlDotNet.Core.Events;
    using YamlDotNet.Serialization;

    public class FileInfoConverter : IYamlTypeConverter {

        /// <summary>
        /// Gets a value indicating whether the current converter supports converting the specified type.
        /// </summary>
        /// <param name="type"></param>
        /// <returns></returns>
        public bool Accepts(Type type) => type == typeof(FileInfo);

        /// <summary>
        /// Reads an object's state from a YAML parser.
        /// </summary>
        /// <param name="parser"></param>
        /// <param name="type"></param>
        /// <returns></returns>
        /// <exception cref="InvalidDataException">Invalid YAML content.</exception>
        public object ReadYaml(IParser parser, Type type) {
            var value = ((Scalar)parser.Current).Value;
            parser.MoveNext();
            return new FileInfo(value);
        }

        /// <summary>
        /// Writes the specified object's state to a YAML emitter.
        /// </summary>
        /// <param name="emitter"></param>
        /// <param name="value"></param>
        /// <param name="type"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteYaml(IEmitter emitter, object value, Type type) {
            emitter.Emit(new Scalar(null, null, (value as FileInfo).FullName, ScalarStyle.Any, true, false));
        }

    }`

I know you can't look at each and every issue, it's just sometimes hard to accept that issues can go under the radar for years, even after they've been commented on years after the issue itself was posted.

**Comment by aaubry** [comment]
I understand and would prefer to not have issues open for so long, but some were created during a period where I could not dedicate any time to this. At the moment I am able to spend a bit more time but I haven't been able to look into old issues. I'm currently focusing on writing documentation because I noticed that many issues or questions were easily solvable if you knew how, but I can't expect people to figure that out just by looking at the implementation.

**Comment by Beatsleigher** [comment]
That's understandable. Didn't mean to offend you if I did. 
I'm glad you're dedicating more time in to documenting the lib, that's thrown me off quite a few times because there are barely any docs. Usually it's come down to looking on SO and hoping you answered the questions lol
