### ISSUE TITLE
Visual Studio 2012 add-in support

### ISSUE THREAD

**Issue by dsaf** [aaubry/YamlDotNet#106]
It seems that the add-in no longer supports Visual Studio 2012. Would it be possible to roll this change back?

http://visualstudiogallery.msdn.microsoft.com/34423c06-f756-4721-8394-bc3d23b91ca7
(there is another complaint in the comment section of that page)

It would be nice, since Visual Studio 2012 is a milestone version where Microsoft stopped supporting multiple products (e.g. XNA, Windows Phone 7.1). Visual Studio 2013 is a less important version released to fill the gap between version 2012 and version 2014 (coming this September).

Thank you.

**Comment by aaubry** [comment]
Closing this because the issue probably no longer exists. Please open a new issue if you still encounter this bug.
