### ISSUE TITLE
Non-specific node tag problem

### ISSUE THREAD

**Issue by rncor** [aaubry/YamlDotNet#107]
I have some Ruby generated YAML files, which uses non-specific node tags (chapter 8.2 for YAML 1.1 specification, chapter 6.9.1 for YAML 1.2 specification). It's single exclamation mark before node, which purpose is to force basic interpretation (differently specified for 1.1 and 1.2 standards) of node value.

Unfortunately such non-specific node tags causes YamlDotNet.Core.SyntaxErrorException

![yamldotnet-non-specific-tag-problem](https://cloud.githubusercontent.com/assets/6603214/4201036/4039c0fc-3819-11e4-9dce-27eab9848bce.png)
## The issue can be reproduced with YAML code snippet from YAML specification.

Best regards
Rik

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
