### ISSUE TITLE
Deserialization: no way to specify general key to property mapping

### ISSUE THREAD

**Issue by ghost** [aaubry/YamlDotNet#108]
Deserialization would be easier if we could define and use general key to property mapping rules. 
Basically like INamingConvention but in reverse way.

For example deserializing:

```
person:
    full name: Bob
    age: 15
    eats open-mouthed: yes
```

into

```
class Person
{
    public string FullName { get; set; }
    public int Age { get; set; }
    public bool EatsOpenMouthed { get; set; }
}
```

would be much easier if we could define and use general mapping like:

Key -> PascalCase

Currently one must FOR ALL properties either:
1) use [YamlAlias]
2) hardcode property name and use it in INamingConvention

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
