### ISSUE TITLE
Serializing also fields and not just properties will make life easier

### ISSUE THREAD

**Issue by oscarsan** [aaubry/YamlDotNet#117]
I have an small problem, I'm using structures for 2 purposes, deserialize and serialize from Yaml files but also to download it to a realtime system which needs Marshaled variables. So for example

```
public struct Configuration
    {
        public NameValue Name;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
        public BoolValue[] AllowedInDirection; 
   }
```

In this case the BoolValue is something that I need to Marshal in order to been able to download it to the final component. Converting this in a property in order to been able to use the Deserializer and Serializer is quite big work, I will need to create different structures for the realtime component and for the YAML file and that is not go.

So, why not to make this marvelous component so that it will be also possible to serialize a deserialize fields and not just properties inside a class or structure.

**Comment by svermeulen** [comment]
This would also play a lot more nicely with Unity since Unity serialization does the opposite (requires that serializable data be in fields and not in properties)

**Comment by zatherz** [comment]
Bump

**Comment by FullStackForger** [comment]
+1 from me here.  YamlDotNet is awesome but making it work with unity generates lots of unnecessary work.

**Comment by PathogenDavid** [comment]
It is worth pointing out that this is preventing serialization of ValueTuple since they use public fields.

**Comment by aaubry** [comment]
This has been added to [release 5.4.0](https://github.com/aaubry/YamlDotNet/releases/tag/v5.4.0).
