### ISSUE TITLE
Cryptic exception in case of duplicated keys

### ISSUE THREAD

**Issue by vasily-kirichenko** [aaubry/YamlDotNet#120]
```yaml
Key1: 0
Key1: 0
```
```
(Lin: 0, Col: 0, Chr: 0) - (Lin: 0, Col: 0, Chr: 0): Error while deserializing node [Mapping start [anchor = , tag = , isImplicit = True, style = Block]]
```
It's completely unclear that the problem is the key duplicating. We've just wasted 30 minutes to find why our 200-lines yaml was not parsed after git merge.

**Comment by aaubry** [comment]
Can you provide more context? What type were you deserializing into? Did you check the InnerException for more details?

**Comment by aaubry** [comment]
This is not always an error - https://dotnetfiddle.net/KVjxjG
Could you elaborate on what would have been the expected result?

**Comment by aaubry** [comment]
Closing due to lack of feedback.

**Comment by superyyrrzz** [comment]
> This is not necessarily an error - https://dotnetfiddle.net/KVjxjG

I would expect an error in this sample, as YAML restricts that each of the keys is unique: http://yaml.org/spec/1.1/#mapping/information%20model

**Comment by hengoren** [comment]
@aaubry Revisiting this, is there any way to enforce unique keys in a yaml file? I found [this](https://stackoverflow.com/questions/30510704/is-it-possible-to-disallow-duplicates-in-yaml-file) on stackoverflow, but it seems a bit dated
