### ISSUE TITLE
Can't deserialize to interface that inherits properties from other interfaces

### ISSUE THREAD

**Issue by emddudley** [aaubry/YamlDotNet#121]
I would like to deserialize to an interface that inherits properties from other interfaces, but v3.5.1 does not currently appear to support that. Is there a possibility of adding support for this?

    public interface IBase
    {
        int Id { get; set; }
    }
    
    public interface IDerived : IBase
    {
        int SomeValue { get; set; }
    }
    
    public interface ITopLevel
    {
        IDerived SomeDerived { get; set; }
    }

    // Suppose that SomeObjectFactory maps interface types to concrete types
    var deserializer = new Deserializer(new SomeObjectFactory());
    
    // This triggers a SerializationException, "Property 'Id' not found on type 'IDerived'."
    var out = deserializer.Deserialize<ITopLevel>(someYamlWithId);

I believe this occurs because the `GetPublicProperties()` methods in [Portability.cs](https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet/Helpers/Portability.cs) do not detect when the provided type is an interface. If it's an interface, calling [Type.GetProperties()](https://msdn.microsoft.com/en-us/library/aky14axb) will only return the properties defined on the interface itself, and none of the inherited properties. To get properties an interface inherits from other interfaces you need to do something like:

    public static IEnumerable<PropertyInfo> GetPublicProperties(this Type type)
    {
        var bindingFlags = BindingFlags.Instance | BindingFlags.Public;
        if (!type.IsInterface) { return type.GetProperties(bindingFlags); }
        return (new Type[] { type })
            .Concat(type.GetInterfaces())
            .SelectMany(i => i.GetProperties(bindingFlags));
    }

(via [GetProperties() to return all properties for an interface inheritance hierarchy](http://stackoverflow.com/q/358835/111327) on StackOverflow)

**Comment by aaubry** [comment]
This is definitely a bug. Are you able to attempt to fix it? If so, please submit a pull request. Otherwise, let me know and I will attempt to fix this quickly.

**Comment by emddudley** [comment]
See pull request #123.
