### ISSUE TITLE
New feature: Ability to specify scalar style in YAML output

### ISSUE THREAD

**Issue by matthewrwilton** [aaubry/YamlDotNet#122]
Hi

I'd like to be able to control what the scalar style of properties is in the serialised YAML. If you think such a feature is worthwhile I'd be happy to have a go at adding it in.

My thoughts on implementing this would be to add an additional property to the YamlMemberAttribute where the scalar style can be specified.

Is this something you'd be interested in receiving a pull request for?

**Comment by aaubry** [comment]
Sure, this feature could be useful. I agree that YamlMember is the appropriate location to specify that. Thanks

**Comment by matthewrwilton** [comment]
Great! I'll work on this and submit it as a pull request.
