### ISSUE TITLE
DefaultValue is ignored in Deserializer

### ISSUE THREAD

**Issue by robertmuehsig** [aaubry/YamlDotNet#124]
I tried to provide a "default" via the DefaultValue attribute, but it seems that the deserializer ignores this property.

Sample-Code: https://dotnetfiddle.net/hJ2NFd

```
    public class Order
    {
        [DefaultValue(true)]
        public bool DoubleCheckThis { get; set; }
        ...
    }
```

Output:
Order
DoubleCheckThis False

Is this currently supported?

**Comment by artganify** [comment]
Has this been implemented? I'm also looking for an answer.

**Comment by vain0** [comment]
Note: This is because ``Activator.CreateInstance`` ignores `DefaultValueAttribute`.

**Comment by scriptator** [comment]
Is there any update on that problem? If not, what's the recommended way of handling defaults during deserialization?

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.

**Comment by Vladimir35** [comment]
It is really a pity that it has not been fixed yet.
See also https://github.com/aaubry/YamlDotNet/issues/300

**Comment by aaubry** [comment]
I have provided an answer in #465
