### ISSUE TITLE
Extend deserializer to support populating instantiated objects

### ISSUE THREAD

**Issue by ddevault** [aaubry/YamlDotNet#130]
Json.Net allows you do do something like this:

```
JsonConvert.PopulateObject(string, object);
```

Any properties that aren't found in the JSON are left alone on the object. Is something similar possible for YamlDotNet?

**Comment by Predelnik** [comment]
+1, for now I convert to Json and use Json.net for this.

**Comment by EdwardCooke** [comment]
This issue appears to be abandoned, I'm going to close it.
