### ISSUE TITLE
Not listed at yaml.org

### ISSUE THREAD

**Issue by kwill** [aaubry/YamlDotNet#136]
I discovered this library via comments at http://stackoverflow.com/questions/42071/net-yaml-library As mentioned there it looks very well-maintained! Perhaps it should be listed in the C#/.NET section at http://yaml.org ?

**Comment by aaubry** [comment]
I added the link to the site [one year ago](https://github.com/yaml/yaml-org-site/commit/aa582ec406f37299bc0ee757ccac9372abba2920), but it seems that the site has not been updated since. I will ping the mailing list to see what's going on.

**Comment by aaubry** [comment]
The site yaml.org now lists YamlDotNet. Hurray!
