### ISSUE TITLE
Indent the source code with spaces instead of tabs

### ISSUE THREAD

**Issue by aaubry** [aaubry/YamlDotNet#143]
It seems that most people prefer to use spaces instead of tabs. In order to make it easier for everyone to contribute, maybe we should update the source code to use that convention?

I'd like to gather at least a few comments from contributors before moving forward.

**Comment by LavenderMoon** [comment]
That's the Visual Studio default, so that's likely why. Most people writing C# on Windows probably don't even think about it.

**Comment by aaubry** [comment]
True. In the past, the default was tabs, that's why I stuck to it :)

**Comment by LavenderMoon** [comment]
Honestly, if it wasn't for version control, I don't think many C# devs would care about tabs vs spaces. If only git auto-converted that the way it did for new-lines.
