### ISSUE TITLE
Serializing enum values to json

### ISSUE THREAD

**Issue by ingridelin** [aaubry/YamlDotNet#146]
When I serialize a class containing an enum value to json, it ends up with the enum name with no quotes, which results in an invalid json file. I'd like it to serialize as a string, how would I go about doing that? I've used [YamlMember(typeof(string))] on all my enum values for now, but would ideally like to be able to serialize all enum values to string, since adding this property is easily forgotten when adding new class members.

``` csharp
using YamlDotNet.Serialization;

public class Program
{
    public enum Primitive {Sphere, Cube}
    public Primitive type {get; set;}

    public static void Main()
    {
        var serializer = new Serializer(SerializationOptions.EmitDefaults | SerializationOptions.JsonCompatible);
        serializer.Serialize(System.Console.Out, new Program());
    }
}
```

The code above serializes to this:

``` json
{
  "type": Sphere
}
```

I would like it to serialize to this:

``` json
{
  "type": "Sphere"
}
```

**Comment by JogoShugh** [comment]
I see the same behavior. Any luck on this?

**Comment by rakelkar** [comment]
+1 https://dotnetfiddle.net/RqYguF
