### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by adrianmihalko** [aaubry/YamlDotNet#147]
Dear aaubry,

Sorry for the off topic.

Can you please write me your e-mail address?

I want to ask about this app, I hope you are the author (I think from the name).

http://www.codeproject.com/Articles/20994/Using-multiple-keyboards-with-different-layouts-on

**Comment by aaubry** [comment]
Hi,

I'd rather not post my email address here, to reduce spam. You can contact-me using this form - http://kontactr.com/user/brisemec. Thanks
