### ISSUE TITLE
Option for indenting behavior (mapping of sequence)

### ISSUE THREAD

**Issue by Yankas** [aaubry/YamlDotNet#15]
The library does not seem to indent a mapped sequence by default like this:

```
Key:
- item1
- item2
- item3
```

Often the alternative can improve readability or at the very least look much nicer

```
Key:
  - item1
  - item2
  - item3
```

I'd suggest an option for either the Emiter/Serializer or each mapping to change this behavior.

If this functionality already exists, my apology I was not able to find anything related in the  API.

**Comment by MiYanni** [comment]
Is there any update on this? Recently, I was comparing serialization output from `YamlDotNet` to another source. That source had tabbed arrays, and my serialization from `YamlDotNet` did not. `SharpYaml` has this feature as [IndentLess](https://github.com/xoofx/SharpYaml/blob/master/SharpYaml/Serialization/SerializerSettings.cs#L139). Unfortunately, I cannot use `SharpYaml` as they do not properly support anchors.

**Comment by jelkevanhoorn** [comment]
Is there any update on this issue?
In my current editors the list cannot be folded in the first example, but can be folded in the second example, so an option to accomplish the second example would be very helpful
