### ISSUE TITLE
Named tags consume the first character

### ISSUE THREAD

**Issue by evan-erdos** [aaubry/YamlDotNet#150]
Before I figured out how to register tags with the `Deserializer`, I was using named tags like aliases for my namespaces (because for it to work without registering tags, I had to have the exact, name-mangled string for the runtime type, e.g., MyEngine.MyClass`1[T]+someNestedClass).

Anyways, named tags appear to consume the first character of whatever they're assigned to. When I used something like this:

```
%TAG !typeAliasThing! MyNamespace.MyClass+Subclass
```

I would get an error saying that it couldn't find `yNamespace.MyClass+Subclass`, the fully-qualified type name, without the first character. When I added an underscore to the front of all my types (probably any character works) it compiled & ran, and serialized my classes just fine, e.g.,

```
%YAML 1.1
%TAG !type! _MyNamespace.OtherNamespace.
---    

Some Object: !type!ClassName &anchor_if_you_want
    stuff: /some\s+cool(regex)?/ # custom type resolver, baby! regex literals!
    et: "cetera"
```

Since there's a workaround, this isn't really critical.

**Comment by matthijskooijman** [comment]
I believe that the first character [is consumed here](https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet/Serialization/NodeTypeResolvers/TypeNameInTagNodeTypeResolver.cs#L37):

     currentType = Type.GetType(nodeEvent.Tag.Substring(1), true);

I suspect that this is intended to consume the ! in front of the typename? Not sure, though.

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
