### ISSUE TITLE
AddFirst

### ISSUE THREAD

**Issue by tallesl** [aaubry/YamlDotNet#151]
Hi,

I'm using the library to "finish" a half baked yaml given by the user (by adding some properties to it).

I noticed I can append a property with `YamlMappingNode.Add`.
It's possible to insert a property at the beginning? (Something like [JSON.NET's AddFirst](http://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JContainer_AddFirst.htm)).

**Comment by aaubry** [comment]
Sorry that I failed to answer this in a timely maner. `YamlMappingNode` uses a `Dictionary<,>` internally, so the order of the entries is not even defined. Maybe it would make sense to use a list instead, and add methods to insert at the beginning?

**Comment by tallesl** [comment]
There's [OrderedDictionary](https://msdn.microsoft.com/library/System.Collections.Specialized.OrderedDictionary) too.
