### ISSUE TITLE
Serialize comments

### ISSUE THREAD

**Issue by asbjornu** [aaubry/YamlDotNet#152]
I haven't found a way to do this, so please excuse my lack of knowledge if this is possible, but I would love to be able to serialize comments attached to properties somehow. If this isn't possible, I'm thinking it could be solved by attaching an attribute to the property, like so:

``` c#
[YamlMember(Alias = "foo")]
[YamlComment("This is the foo. Use it with care.", CommentPlacement.Above)]
public string Foo { get; set; }
```

Serializing this would give something like this:

``` yaml
# This is the foo. Use it with care.
foo: bar
```

With a possible value of `CommentPlacement.After`, it would end up like this:

``` yaml
foo: bar # This is the foo. Use it with care.
```

The `CommentPlacement` enumeration could perhaps be some sort of `ICommentSerializationConvention` instead. Not sure how to best solve this. Would you be interested in a pull request for this?

**Comment by aaubry** [comment]
You are right that this not possible to do right now. According to the [YAML specification](http://www.yaml.org/spec/1.2/spec.html#id2767100),
> Comments are a presentation detail and must not have any effect on the serialization tree or representation graph. In particular, comments are not associated with a particular node.

However, the Parser and Emitter are both able to understand parse and emit comments, so it should be possible to implement that quite easily. If you want to implement this, you will probably need to implement an additional `IObjectGraphVisitor` that would take care of emitting the comments.

**Comment by asbjornu** [comment]
@aaubry Thanks for the information. Do you have any preference on how it is implemented? Is the `YamlComment` attribute a good solution, or would you prefer something else? Is the naming OK? How about the `CommentPlacement` enum; is it consistent with the rest of the serialization system?

**Comment by aaubry** [comment]
I was thinking that you would want to implement that for your own project. I am not sure that this should be a feature of YamlDotNet. Including this in the serializer would risk bloating the code for a use case that few people actually care about, but I am willing to discuss it. If you would like to share your implementation with others, an option would be to create a NuGet package that would contain the types that you will create, and maybe some extension methods to make it easy to register them in a serializer instance.

Of course, if you need to make changes to YamlDotNet itself to make it possible to implement emitting comments, and such changes are made in a reusable way that might be useful for other extensions, I'll gladly merge them.

**Comment by asbjornu** [comment]
@aaubry I see. I was of the impression that this **had** to be developed internally inside YamlDotNet, but if it's possible to do externally, I'll of course give that a go first. Thanks! :)

**Comment by asbjornu** [comment]
@aaubry Finally finding time to look at this, I'm having trouble understanding how I can plug my own implementation of `IObjectGraphVisitor` into the `Serializer.Serialize()` method. I'm able to send in an `IEmitter`, but that doesn't seem to give me the tools I need to inject comments into the stream.

I know it's much to ask, but could you please be so kind as to provide a more complete example of how I can accomplish this? Thanks!

**Comment by asbjornu** [comment]
@aaubry I've taken yet another jab at this, by forking YamlDotNet this time, and digging deep into the `Serializer` and how it goes about its business. I found that I can just do `new Emitter(TextWriter)` and serialize to that instead.

This gives me **some** control, but the `Emitter` class doesn't give me much leeway in terms of customization; all methods are non-virtual and/or private, so I basically have to re-implement the `IEmitter` interface and wrap the `Emitter`, which again leaves me with the `public void Emit(ParsingEvent @event)` method, which seems to be too late in the process for me to discover custom attributes on the properties containing the documentation I'd like to output as comments.

So, I'm still stuck trying to figure out how to implement this without extending or changing YamlDotNet in any way. Pointers? Ideas?

**Comment by donaldgray** [comment]
Has there been any movement on this? I'm looking to use YamlDotNet for outputting RAML and there's a requirement that the document starts with a comment documenting the RAML version number, e.g. `#%RAML 0.8`

**Comment by andrejohansson** [comment]
In this [StackOverflow post](https://stackoverflow.com/questions/29728353/yamldotnet-generate-comments-during-poco-serialization) you mention that it´s possible to createe a `YamlDocument` and add comments. Can you provide an example?

```
var keyNode = new YamlScalarNode("mykey");
var valueNode = new YamlScalarNode("myvalue");                

valueNode.AddComment("mycomment"); // I am looking for something like this

var kvp = new KeyValuePair<YamlNode, YamlNode>(keyNode, valueNode);
var typeNode = new YamlMappingNode(kvp);
var instanceList = new YamlSequenceNode(typeNode);
var doc = new YamlDocument(instanceList);
```

**Comment by Patrikkk** [comment]
Hey. Sorry to bump this. It's been 2 years since this was discussed. I'm curious, is it possible today, to serialize comments?
I would like some automatic/dynamic documentation to the data which is serialized.

**Comment by aaubry** [comment]
Hi. Nothing has been developed specifically to serialize comments. I have created [a sample that shows a way to implement this yourself](https://dotnetfiddle.net/8M6iIE).

The approach is as follows:
1. Register an `ITypeInspector` that checks the presence of the `[Description]` attribute, and returns a custom `IObjectDescriptor` that contains that information.
2. Register an `IObjectGraphVisitor` that checks if the object descriptor contains a comment, and if so, emits that comment.

While this works, there are some problems in the code, because it violates the Liskov substitution principle. In order to be able to add this kind of customizations, there should be some mechanism to add metadata to the `IObjectDescriptor` object.
