### ISSUE TITLE
YamlDotNet.RepresentationModel.Serialization is missing?

### ISSUE THREAD

**Issue by nowox** [aaubry/YamlDotNet#154]
I just downloadaed `YamlDotNet` with the two dependencies and I opened it on VisualStudio 2010 and VisualStudio 2015. I get plenty of errors like this: 

```
Severity	Code	Description	Project	File	Line
Error	CS0234	The type or namespace name 'RepresentationModel' does not exist in the namespace 'YamlDotNet' (are you missing an assembly reference?)	YamlDotNet.PerformanceTests.v1.2.1	C:\Users\John\Desktop\YamlDotNet-master\YamlDotNet-master\PerformanceTests\YamlDotNet.PerformanceTests.v1.2.1\Program.cs	24
```

What did I miss?

**Comment by aaubry** [comment]
You are probably trying to compile old code. The `YamlDotNet.RepresentationModel.Serialization` namespace was renamed to `YamlDotNet.Serialization` [some time ago](https://github.com/aaubry/YamlDotNet/commit/fb597f907aa8b080f98b7603eab5271e872af2cd). Simply removing "RepresentationModel" should fix the code, but let me know if you need further assistance.
