### ISSUE TITLE
Unicode encoding not serialized based on ScalarType

### ISSUE THREAD

**Issue by aodpi** [aaubry/YamlDotNet#159]
I have a yaml document which has unicode characters. When I indicate the `YamlMember` attribute with specific `ScalarType` during Serialization it does not apply that `ScalarType` to the strings that contain Unicode characters. Example:

![yml](http://i.imgur.com/MwNeLAV.png)

en,ro,ru have their `ScalarType` set to `ScalarType.SingleQuoted`, as you can see the last, ru, has it's `ScalarType` set to `ScalarType.DoubleQuoted`, I guess it's a value by default in case of an error during Serialization.

**Comment by aaubry** [comment]
What encoding are you using? If you are not using Unicode, non-ASCII characters need to be escaped, thus preventing the use of single-quoted scalars.

**Comment by aodpi** [comment]
I obtain the data with the help of deserialization, then I make changes in the application, after that I use serialization of changed data to write these changes to the yaml file. I wasn't able to find some Serialization settings regarding encoding. Maybe the problem isn't in Encoding after all.

**Comment by aodpi** [comment]
Escaping doesn't help either :(

**Comment by aaubry** [comment]
I have tested this scenario and I confirm that this is a bug in YamlDotNet. The detection of the encoding type is broken. I will fix that and public a new version.

**Comment by aodpi** [comment]
Wow thanks, i'm glad i helped, somehow.
