### ISSUE TITLE
Enum Dictionary Round Trip fails

### ISSUE THREAD

**Issue by pablinos** [aaubry/YamlDotNet#163]
Hi,

I have a property on an object that uses and enum as a dictionary key:

```csharp
public Dictionary<TransportType, String> DefaultProviders
        {
            get;
            set;
        }
```

Where TransportType is the following enum:

```csharp
public enum TransportType
    {
        Email,
        Sms,
        Push
    }
```

The object serializes fine with the enum values appearing. The problem is that when I deserialize the result I get an exception saying that the property DefaultProviders is not found. I'm assuming it's because it's looking for a property of a different type.

Any ideas how to get this working?

**Comment by aaubry** [comment]
I did a simple test that is working correctly - https://dotnetfiddle.net/1Id5Eq.
What exactly are you trying to do? Please provide more information so that I can help you.

**Comment by pablinos** [comment]
Hi, yes it is working correctly, sorry! 

I'd copied some code that was from another project and it had the CamelCaseNamingConvetion on the deserializer, but not on the serializer so the Yaml wasn't of the same format.

I should have written my own test before posting...

**Comment by aaubry** [comment]
No problem. I'm glad that you found the bug.
