### ISSUE TITLE
Backslashes are incorrectly represented

### ISSUE THREAD

**Issue by replaysMike** [aaubry/YamlDotNet#165]
I noticed that backslashes specified in the YAML end up as double backslashes when deserializing to a yaml object.

Sample:

```
using (var r = new StreamReader(filename))
{
    var deserializer = new Deserializer(namingConvention: new CamelCaseNamingConvention());
    var yamlObject = deserializer.Deserialize(r);
}
```

In the case of using YAML for converting to JSON schema, this is a problem because regular expression patterns are incorrect.

**Comment by aaubry** [comment]
Can you elaborate on this issue? [I tried to parse a JSON in a fiddle](https://dotnetfiddle.net/9lcm1t), and it seems to work as expected.

**Comment by replaysMike** [comment]
I think this can be filed as not a bug then. I was under the assumption that json did not require backslashes to be encoded within the string, and I will need to decode/unescape these on my own.
