### ISSUE TITLE
Guid conversion to JSON is unquoted

### ISSUE THREAD

**Issue by replaysMike** [aaubry/YamlDotNet#166]
When converting from YAML to JSON, the GuidConverter is not handling Guid's correctly. They must be quoted strings according to JSON spec.

```
var js = new Serializer(SerializationOptions.JsonCompatible | SerializationOptions.DisableAliases, namingConvention: new CamelCaseNamingConvention());

using (var w = new StringWriter())
{
    js.Serialize(w, o);
    string json = w.ToString();

    /*Fix for issue #165, duplicate backslashes produced by YamlDotNet */
    json = json.Replace(@"\\", @"\");

    return json;
}

```

**Comment by aaubry** [comment]
I confirm that this is a bug; I'll see what can be done to fix it.

**Comment by replaysMike** [comment]
awesome thanks. I thought this might have been happening in the underlying json library as microsoft's javascript serialize also behaves this way, but I didn't check to see if you had rolled your own.
