### ISSUE TITLE
DefaultObjectFactory crashes when trying to instantiate a non-generic interface

### ISSUE THREAD

**Issue by aaubry** [aaubry/YamlDotNet#167]
At https://github.com/aaubry/YamlDotNet/blob/2b78ca887b62923f922e5b5c614b472584f8f05e/YamlDotNet/Serialization/ObjectFactories/DefaultObjectFactory.cs#L45

**Comment by EdwardCooke** [comment]
This issue appears to be abandoned, I'm going to close it.
