### ISSUE TITLE
Deserialization with YamlDotNet.RepresentationModel.YamlStream does not handle null values

### ISSUE THREAD

**Issue by agross** [aaubry/YamlDotNet#170]
I'm trying to use YamlDotNet with PowerShell and [this piece of code](https://github.com/dfinke/PowerYaml/blob/master/PowerYaml.psm1#L44-L49).

Basically, it reads the yaml document using the YamlStream API and then handles nodes in the root document.

It seems that whenever I use `null`, `~` or an empty hash value to denote a null value the parse just gives me the plain text associated with the node. Basically this makes it impossble to detect nulls as I always see the literal string. Here's an example in C# of what I'm doing: https://dotnetfiddle.net/8gjSxo

**Comment by aaubry** [comment]
That's an open issue. You should be able to get that information from the Tag property, but that is not implemented in the correct place. For now, the only part that correctly handles nulls, is the serialization namespace. If you are able to use it, it will work better for your needs: https://dotnetfiddle.net/sM7Vz2

**Comment by agross** [comment]
Thanks for the information!

I wonder how well deserialzation works if the document structure is not known in advance with nested hashes, arrays etc. that are combined in the yaml.

Here's an example of what I'm looking forward to parse:

https://github.com/dnugleipzig/deploy/blob/master/spec/powershell/Deployment/lib/Invoke-Deployment.Tests.ps1#L305

From your experience, do you think it's possible to load into a dictionary?

**Comment by aaubry** [comment]
This would definitely work. If you do not specify the type when deserializing, the following conversions are assumed:
* mapping -> `Dictionary<object, object>`
* sequence -> `List<object>`
* scalar -> `string`

**Comment by agross** [comment]
Thanks! :+1:
