### ISSUE TITLE
Change sequence style

### ISSUE THREAD

**Issue by reimund** [aaubry/YamlDotNet#176]
Is it possible to change the sequence style when serializing documents?

For example, from:

```
- Item 1
- Item 2
```

To:
`[Item 1, Item 2]`

I could not find any good documentation or examples of how you would do this.

I've fiddled with a custom converter a bit and almost got something working, but I could not figure out how to get rid of the quotes (ie I got ['Item 1', 'Item 2'] and also never found a good way to deal with nested sequences.

Any pointers appreciated.

**Comment by reimund** [comment]
I managed to get something working with my custom TypeConverter, but I had to modify the signature of `IYamlTypeConverter.WriteYaml`.

This is how my `WriteYaml` ended up.
```
public void WriteYaml(IEmitter emitter, IObjectDescriptor value, IObjectGraphTraversalStrategy traversalStrategy, IObjectGraphVisitor visitor)
{
    var enumerableType = ReflectionUtility.GetImplementedGenericInterface(value.Type, typeof(IEnumerable<>));
    var itemType = enumerableType != null ? enumerableType.GetGenericArguments()[0] : typeof(object);
    var typeResolver = (ITypeResolver)new DynamicTypeResolver();

    emitter.Emit(new SequenceStart(null, null, true, SequenceStyle.Flow));
    foreach (var item in (IEnumerable)value.Value)
    {
        traversalStrategy.Traverse(new ObjectDescriptor(item, typeResolver.Resolve(itemType, item), itemType), visitor);
    }
    emitter.Emit(new SequenceEnd());
}
```

Perhaps there is an easier way without editing the source?

I could also just edit `EventInfo.cs` and set `this.Style = SequenceStyle.Flow;` but that PR would never pass :)

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
