### ISSUE TITLE
Save YamlStream to json format

### ISSUE THREAD

**Issue by elios264** [aaubry/YamlDotNet#182]
As of right now YamlStream is perfectly capable of loading json documents, I checked in docs that the library is also able to save to json format (with no indent option :cry:  ) using:

`new Serializer(SerializationOptions.JsonCompatible)`

But there is currently no efficient way to save a YamlStream JsonCompatible, the only workaround I found is to save the yamlstream in a file, then read it with the Deserializer to a dynamic object,
then serialize again with the serializer now using the SerializationOptions.JsonCompatible option

**Comment by aaubry** [comment]
It is [now possible](https://github.com/aaubry/YamlDotNet/commit/2b3b398fcab54bab5cd489dda8012f87ccd716db) to serialize instances of YamlMappingNode, YamlSequenceNode and YamlScalarNode. You cannot serialize a YamlStream or YamlDocument, but you could serialize the root node of the first document in your stream. The emitted document should respect the `JsonCompatible` option.
