### ISSUE TITLE
Deseralize on sequence files?

### ISSUE THREAD

**Issue by Zifrian** [aaubry/YamlDotNet#188]
I'm having the hardest time deserializing a yaml file that is basically a sequence. I'm using vb.net and have tried everything to no avail. A mapped file works beautifully but when I get a sequence file it won't run.

Here is the data formatted in the file:

```
-   itemID: 0
    itemName: (none)
-   itemID: 1
    itemName: System
-   itemID: 2
    itemName: Central Bank
-   itemID: 3
    itemName: Market
-   itemID: 4
    itemName: Station
-   itemID: 5
    itemName: Temp"
```

For the mapped files, I use this code (for another class and it works) but it doesn't work here:

```
Public Class invName
    Public Property itemID As Long
    Public Property itemName As String
End Class

Public Sub ImportFile(FilePath as String)
        Dim Names As Dictionary(Of Long, invName)

        Dim Deserializer = New Deserializer() 
        Dim InputText = New StringReader(File.ReadAllText(FilePath))
        Names = Deserializer.Deserialize(Of Dictionary(Of Long, invName))(InputText)

End Sub
```

It doesn't work for sequence files, which makes sense because the Dictionary class doesn't work with sequences (I think) but I'm not sure how to get it to work any other way. With mapped files the function will give me this awesome list but here the closest I can get is basically the StringReader. I've went to the object browser and tried most of the options there but I can't get it to output the nice format as with mapped files.

Any help?

**Comment by aaubry** [comment]
A YAML sequence corresponds to a .NET list. You should try to deserialize as a `List(Of invName)`.

**Comment by Zifrian** [comment]
Hey, thanks for the response. I'm not sure why I didn't figure it out earlier but it works great! Appreciate all the work you did on this library.

For reference, if anyone else is having similar issues, to import a sequence file as described above, just use this code in vb.net:

Dim YAMLRecords As New List(Of invNames)
Dim DS = New Deserializer() ' Don't use a naming convention

YAMLRecords = DS.Deserialize(Of List(Of invNames))(New StringReader(File.ReadAllText(YAMLFile)))

Also for reference, for anyone looking at a mapped file, here is the code I use:

Dim DS = New Deserializer() ' Don't use a naming convention
Dim YAMLRecords As New Dictionary(Of Long, eveIcon)

YAMLRecords = DS.Deserialize(Of Dictionary(Of Long, eveIcon))(New StringReader(File.ReadAllText(YAMLFile)))
