### ISSUE TITLE
OverridePropertyDescriptor doesn't lookup properties properly.

### ISSUE THREAD

**Issue by veleek** [aaubry/YamlDotNet#190]
Currently, the `Deserializer` creates a type inspector like this.

    typeDescriptor.TypeDescriptor =
        new CachedTypeInspector(
            new YamlAttributesTypeInspector(
                new YamlAttributeOverridesInspector(
                    new NamingConventionTypeInspector(
                        new ReadableAndWritablePropertiesTypeInspector(
                            new ReadablePropertiesTypeInspector(
                                new StaticTypeResolver()
                            )
                        ),
                        namingConvention
                    ),
                    overrides
                )
            )
        );

Using a simple class like this:
```
public class Foo
{
	public bool IsRequired { get; set; }
}
```

And overrides:

```
var yao = new YamlAttributeOverrides();
var isRequiredAttribute = new YamlMemberAttribute();
isRequiredAttribute.Alias = "Required";
yao.Add(typeof(Foo), "IsRequired", isRequiredAttribute);
```

The `NamingConventionTypeInspector` returns an `IPropertyDescriptor` with the name **isRequired**.  Then the `YamlAttributeOverridesInspector` wraps this with an `OverridePropertyDescriptor`.  Later on in the serialization process `GetCustomAttribute` is called on the descriptor which checks the types (`Foo` in this case) for properties with the name `isRequired`.  This returns nothing because of the casing mismatch and as a result it skips the AttributeOverride lookup.  

So, that's the whole issue and I believe the solution is relatively simple.  Swapping the order of the `YamlAttributeOverridesInspector` and `NamingConventionTypeInspector` should be enough to resolve the issue.  I would assert that the `NamingConventionTypeInspector` should be placed after **both** the `YamlAttributesTypeInspector` and `YamlAttributeOverridesInspector` so that naming conventions are applied to overrides as well.

The `GetProperties` calls on the inspectors give this chain:

**YamlAttributeOverridesInspector (and lower):** IsRequired 
**YamlAttributesTypeInspector:** Required
**NamingConventionTypeInspector:** required 

Thoughts?

**Comment by aaubry** [comment]
Thanks for reporting this. Let me look into this and add some failing tests.

**Comment by aaubry** [comment]
I have added a unit test that reproduces the problem, and added a fix for the issue. Swapping the order of the two inspectors helped solve the problem, but I also had to change the implementation of `YamlAttributeOverrides` because it relied on being able to find a property with the current name, which made no sense.

Would you mind to take a look and confirm that this fixes the issue?

Thanks

**Comment by veleek** [comment]
Made a comment on the CR related to the moving the NamingConvention a little higher.  I'll try and validate this for you tomorrow.

**Comment by aaubry** [comment]
I replied to your comment. The order does not need to be changed because the overrides does not change the name of the property. Instead, it replaces the custom attributes of the property, and then YamlAttributesTypeInspector will use the name from the attribute to override the naming convention.
If they are swapped, the naming convention will be applied afterwards.

I think this behavior is better because it is less surprising, although I imaginge that someone might want to apply the naming convention on top of the name override. I am working on adding the ability to customize the composition of the internal components of the serializer and deserializer. This will allow to have this behavior, if needed.

**Comment by veleek** [comment]
Yeah, the way that I was thinking about it was if I had a class like this, I imagine it having implied attributes:

```
class Foo
{
    [YamlMemberAttribute(Alias = "Name")]
    public string Name;
}
```

If I don't do anything, it will use "Name" as the output.  Then, on top of that I apply a naming convention which lowercases it to "name".

With the current ordering, I have to be aware of what NamingConvention is being used and when I add my overrides I have to explicitly say Alias = "name", and if at some point in time someone else goes in and changes the NamingConvention to UpperCaseNamingConvention, then the code will break until someone goes in and changes the attribute overrides to use Alias = "NAME".

That being said, if there's a way for me to control/customize it, then I fine with just leaving it as is for now.  I made another comment on how the Matches method is implemented that you may run into with multiple overrides for different classes that I uncovered as I was debugging another problem I was having.  It doesn't appear to be impacting my use case though.

**Comment by aaubry** [comment]
Sorry, I have been really busy and this issue was left behind. I will look at this again tomorrow to see in which state this was left.

**Comment by aaubry** [comment]
I have updated the [pull request](https://github.com/aaubry/YamlDotNet/pull/193) with changes that adapt to recent code changes, and also fix the behavior. So now if an alias is specified for a property, the alias is applied first, then the naming convention updates it. This behavior can be seen in [this test](https://github.com/aaubry/YamlDotNet/pull/193/files#diff-708522b2dc08a762ee5b6d15eb33ce18R1280). We have a property named `IsRequired`, aliased to `Required`, and we are using `CamelCaseNamingConvention`. The serializer serializes the property as `required`, and the deserializer expects that name also.
