### ISSUE TITLE
[Question] Is it possible to specify inline serialization?

### ISSUE THREAD

**Issue by psicus78** [aaubry/YamlDotNet#191]
Hi,
is there any option to serialize sequences in inline format?
I mean something like this:

 --- # Shopping list
 [milk, pumpkin pie, eggs, juice]

Thanks

**Comment by aaubry** [comment]
Currently, there is no support for that. It should be possible to add that to the `ScalarStyleAttribute`.

**Comment by odkken** [comment]
Any update on this?  It would be nice for lists of classes:

SomeStuff:
- {Property1: 5, Property2: asdf}
- {Property1: 1, Property2: jkl;}

**Comment by yariker** [comment]
Why is this issue closed? Inline syntax is not something special, is is a part of the spec.

**Comment by aaubry** [comment]
It is closed because this was a question, and the question has been answered. We can open an issue to track the need for a way to request inline style for sequences and mappings. Would you like to do it ?

**Comment by yariker** [comment]
Just created one, check #454. Thanks!
