### ISSUE TITLE
Implement a similar method like RegisterTagMapping for the serializer.

### ISSUE THREAD

**Issue by jmattheis** [aaubry/YamlDotNet#192]
As found out in here: http://stackoverflow.com/q/38248697/4244993
There is no way of actually setting a custom Tag for a class inside the serialization.

In my opinion there are 2 options
1. Add the method `RegisterTagMapping(string tag, Type type)` also to the serializer
2. Add a custom attribute `[YamlTag("CustomTag")]` which can be added to a class.

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. In the meantime, this has been implemented.
