### ISSUE TITLE
Cannot define alias for enum members

### ISSUE THREAD

**Issue by t123yh** [aaubry/YamlDotNet#195]
For example I have a member

```
    public enum ComparisonStrictLevel
    {
        None = 0,
        TextOnly = 1,
        IncludeLineBreaker = 2,
        IncludeSpaces = 3,
        Strict = 4,
        AlwaysDiffer = 5
  }
```

And it is used in a class:

```
        [YamlMember(Alias = "strict_level")]
        public ComparisonStrictLevel StrictLevel { get; set; }
```

But I want yaml like this:

```
   strict_level: text_only
```

Impossible to add a `YamlMember` attribute to enum members because it is only for properties.
I think there should be a attribute to indicate alias for enum members.

**Comment by solvingJ** [comment]
This appears to be similar to this question. The response there was that it would be a neat feature, but has not been completed as of yet (4 years ago). 

https://github.com/aaubry/YamlDotNet/issues/30
