### ISSUE TITLE
Is there anyway  to Parse prefab that had convert to text file ?

### ISSUE THREAD

**Issue by wangjianpeng** [aaubry/YamlDotNet#197]
I had use binary2text covert prefab file to text file. how can i read this file format  by exist library ?

**Comment by aaubry** [comment]
I am sorry but I have no knowledge of Unity. Usage questions should be asked on [StackOverflow](http://stackoverflow.com/questions/tagged/yamldotnet), and tagged with [yamldotnet](http://stackoverflow.com/tags/yamldotnet/info). Thanks
