### ISSUE TITLE
Anchors are used but not generated

### ISSUE THREAD

**Issue by Sbreitzke** [aaubry/YamlDotNet#198]
When serializing a list of objects where every object has a parent ID (GUID) the child will reference the parent's id using an anchor but the anchor itself will not be declared.
- Id: 1c49bc54-d0e3-494e-8fd7-b9ffd8c1892a
  Name: Parent
- Id: dd54864a-61f7-4d73-b89d-9bd4e4c2c8f4
  Parent: *o0
  Name: Child

Complete code sample reproducing the problem at SO: http://stackoverflow.com/questions/38807331/yamldotnet-does-set-references-correct

**Comment by aaubry** [comment]
Thanks for reporting this bug, and sorry for the delay. I have successfully reproduced the bug, and I am working on a fix.

**Comment by aaubry** [comment]
With the latest version of the code, this problem no longer occurs. I am not sure which release fixed that, but in the next release, this problem will be gone for sure.

**Comment by nhnponyo** [comment]
I think this problem is not fixed yet.

**Comment by aaubry** [comment]
Can you provide some code that reproduces the problem? That would really help.
Thanks

**Comment by nhnponyo** [comment]
[YamlMember(Alias = "abc")]
public string[] Abc
{
	get;
	set;
}
I serialized this property, and I got this file.
abc: &o0 []

**Comment by nhnponyo** [comment]
Thank you so much for reply.
I am very painful with this problem so long long ago..
This problem intermittently occurred so often.

**Comment by aaubry** [comment]
I tried your code and the behavior seems correct. Please compare [this fiddle](https://dotnetfiddle.net/t6JI5U) with your code and see what is different. Can you create a fully working program that reproduces the problem?

**Comment by nhnponyo** [comment]
can I send codes to your email?

**Comment by nhnponyo** [comment]
Thank you again!! Thankyou

**Comment by aaubry** [comment]
I would prefer if you posted it here so that other people can participate in the discussion. But if for some reason you can't post it here, you can send it to my email.

**Comment by aaubry** [comment]
I probably won't be able to look into this problem today, but tomorrow I will get back to you.

**Comment by nhnponyo** [comment]
Before you came back, I would post here the codes with proper format.
good day! <3<3

**Comment by nhnponyo** [comment]
I solved the problem while making some test cases 
but I don't know why it is working.
I made class like this
var x = new X { Abc = data.abc }); // data is some dummy loaded from file

and I fixed it like this
var x = new X { Abc = new List<string>(blahblah) });

I can't understand. Is it my mistakes?
I'm sorry to bother you at work.. thank you!

**Comment by aaubry** [comment]
I don't know. The best would be if you sent your code, or put it on ditnetfiddle.net, or something like that.

**Comment by nhnponyo** [comment]
`		public class Abc
		{
			public Abc(string[] test)
			{
				Test = test;
			}
			public string[] Test
			{
				get;
				set;
			}
		}

		[TestMethod]
		public void TestExport()
		{
			string[] dummy1 = new string[0];
			string[] dummy2 = new string[1] { "test" };

			var a = new System.Collections.Generic.List<Abc>();
			a.Add(new Abc(dummy2));
			a.Add(new Abc(dummy1));
			a.Add(new Abc(dummy1));
			a.Add(new Abc(dummy2));
			a.Add(new Abc(dummy2));

			using (var writer = new System.IO.StreamWriter(new System.IO.FileStream("test.yml", System.IO.FileMode.Create)))
			{
				var serializer = new YamlDotNet.Serialization.Serializer(YamlDotNet.Serialization.SerializationOptions.EmitDefaults,
					new YamlDotNet.Serialization.NamingConventions.UnderscoredNamingConvention());
				serializer.Serialize(writer, a);
				writer.Flush();
			}

		}`

**Comment by nhnponyo** [comment]
And I got

- test: &o1
  - test
- test: &o0 []
- test: *o0
- test: *o1
- test: *o1

**Comment by nhnponyo** [comment]
thank you!
fiddle:https://dotnetfiddle.net/t6JI5U

**Comment by aaubry** [comment]
This output seems correct. When an object appears in multiple places inside the graph, it is emitted only once with an [anchor](http://www.yaml.org/spec/1.2/spec.html#id2765878). The other locations simply refer to it using an [alias node](http://www.yaml.org/spec/1.2/spec.html#alias//).
If you whish to disable that behavior, you can use this:
```C#
// var serializer = new Serializer();
var serializer = new SerializerBuilder()
	.DisableAliases()
	.Build();
```

**Comment by nhnponyo** [comment]
It was my fault. I didn't know that multiple appearance of one object emit just one anchor.
I would try to read doc more hard. Thank you!!
