### ISSUE TITLE
Create proper docs

### ISSUE THREAD

**Issue by masaeedu** [aaubry/YamlDotNet#199]
Thought I'd create an issue to track this since this is a major stumbling block for getting started with the library.

**Comment by aaubry** [comment]
Hi,

Thanks for bringing this up. I agree that we really need to address this issue.
I would need somebody to lead this effort. My time has been really limited lately, still I am willing to help, but I cannot take care of it alone.

**Comment by masaeedu** [comment]
@aaubry I have had to drop YAML config work due to other time constraints but will look into doc comments and generated docs when I return to the feature.

**Comment by aaubry** [comment]
Documentation work has been started. Currently most of the Serializer has been documented, and part of the Deserializer. Some other topics are also being worked on. You can check the current state on the [wiki](https://github.com/aaubry/YamlDotNet/wiki#documentation).
