### ISSUE TITLE
YamlVisitor is marked as obsolete, but no YamlVisitorBase class exists

### ISSUE THREAD

**Issue by masaeedu** [aaubry/YamlDotNet#200]
The 3.9.0 release on nuget does not include a YamlVisitorBase class, and yet the YamlVisitor class is marked obsolete.

**Comment by forbjok** [comment]
I'm having the same issue. Although it looks like there should be a YamlVisitorBase class from the github source code, it is not in the official 3.9.0 version.

**Comment by aaubry** [comment]
Thanks for reporting this problem. This has been [fixed](https://github.com/aaubry/YamlDotNet/commit/0f74bc3fd4f207882fa342ed78e15eae86faf122#diff-c3c38526104592e40606efd5a2c993dc) on master, and will be included in the next release.
