### ISSUE TITLE
TargetInvocationException when serializing exception

### ISSUE THREAD

**Issue by thomaslevesque** [aaubry/YamlDotNet#212]
This test fails:

```
    [Fact]
    public void SerializeExceptionWithStackTrace()
    {
        var ex = GetExceptionWithStackTrace();
        var serializer = new Serializer();
        string yaml = serializer.Serialize(ex);
        Assert.Contains("GetExceptionWithStackTrace", yaml);
    }

    static Exception GetExceptionWithStackTrace()
    {
        try
        {
            throw new ArgumentNullException("foo");
        }
        catch (Exception ex)
        {
            return ex;
        }
    }
```

It throws a `TargetInvocationException`; the `InnerException` is an `InvalidOperationException` with the following message:

> Method may only be called on a Type for which Type.IsGenericParameter is true.

I don't know if serializing exceptions is a supported scenario, but even if it's not, the current behavior looks like a bug.

Interestingly, the same test with an exception without a stacktrace (i.e. an exception which has never been thrown) succeeds:

```
    [Fact]
    public void SerializeExceptionWithoutStackTrace()
    {
        var ex = GetExceptionWithoutStackTrace();
        var serializer = new Serializer();
        string yaml = serializer.Serialize(ex);
        Assert.Contains("foo", yaml);
    }

    static Exception GetExceptionWithoutStackTrace()
    {
        return new ArgumentNullException("foo");
    }
```

**Comment by aaubry** [comment]
This is not exactly a bug. The exception has a property, `TargetSite`, that is a `MethodInfo` and that is set when the exception is thrown. Apart from the fact that it probably does not make sense to serialize a `MethodInfo` in the first place, its graph eventually leads to a property that throws a `TargetInvocationException`.
If you prevent the serialization of that property using the following code, the test passes:

```C#
var serializer = new SerializerBuilder()
    .WithAttributeOverride<Exception>(e => e.TargetSite, new YamlIgnoreAttribute())
     .Build();
```

**Comment by thomaslevesque** [comment]
Yes, it's roughly what I suspected.

The `YamlIgnoreAttribute` should let me work around the issue, thanks for that!

Maybe YamlDotNet should try to give a more meaningful error message, something like "Object of type `MethodInfo` cannot be serialized". Or maybe even provide an option to just skip members that can't be serialized.
