### ISSUE TITLE
Recover from File Corruption

### ISSUE THREAD

**Issue by DonabedKopoian** [aaubry/YamlDotNet#213]
I use the IYamlConvertible interface to both write object value to and read object values from a file.  If the power happens to failure during a write, then the last message becomes corrupted.  There doesn't appear a way to recover from this.

Example:

Library Collection: 2016-10-21
Books:
- Title: 1984
  Author: George Orwell
  Yea

The attribute Year is cut off, which throws a YamlDotNet.Core.SyntaxErrorException.  I've tried parser.SkipThisAndNestedEvents() as well as while (parser.Accept<MappingEnd>()) { parser.MoveNext(); } and they all throw exceptions.

In the meantime, I have a hack that looks at the message of the exception, and if it needs to, opens the file, appends a semi-colon, saves the file, and attempts to deserialize the file again.

I'd be willing to work on something like this that handles this by simply looking for either the end of the document or a mapping start of a new object, and just returns a null object when the exception is thrown (so it would be up to a developer to check objects to make sure they aren't null, which signals file corruption).

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
