### ISSUE TITLE
Yaml Aliases with underscores are ignored by serializer and deserializer

### ISSUE THREAD

**Issue by rabejens** [aaubry/YamlDotNet#215]
With a class like this:

```C#
public class Foo {

    [YamlMember(Alias = "foobar")]
    public string FooBar { get; set; }

    [YamlMember(Alias = "quux_bletch")]
    public string QuuxBletch { get; set; }

}
```

when serializing an object of this type, the `FooBar` property is correctly serialized to the `foobar` key whereas the `quux_bletch` key with the underscore is NOT used.

Version 3.8.0 which I used before did not exhibit this behaviour.

**Comment by aaubry** [comment]
Can you provide an example? I tried the following test:

```c#
[Fact]
public void X()
{
    var original = new YamlMemberDto
    {
        FooBar = "foo bar",
        QuuxBletch = "quux bletch",
    };

    var serializer = new Serializer();
    var yaml = serializer.Serialize(original);

    var deserializer = new Deserializer();
    var deserialized = deserializer.Deserialize<YamlMemberDto>(yaml);

    Assert.Equal(original.FooBar, deserialized.FooBar);
    Assert.Equal(original.QuuxBletch, deserialized.QuuxBletch);
}

public class YamlMemberDto
{

    [YamlMember(Alias = "foobar")]
    public string FooBar { get; set; }

    [YamlMember(Alias = "quux_bletch")]
    public string QuuxBletch { get; set; }

}
```

and it works as expected. The serialized yaml is:

```yaml
foobar: foo bar
quux_bletch: quux bletch
```

**Comment by rabejens** [comment]
Unfortunately not immediately, it happens in our company code which I am not allowed to post. I will try to reproduce this with a small test case and see if it occurrs again. If yes, I will provide the example.

What I see is that you use the constructors. When using these I get a deprecation warning. I used the builders to build the Serializer and Deserializer, and I explicitly stated the `CamelCaseNamingConvention` to have all properties without an alias stored in CamelCase.

With the CCNC and YamlDotNet 3.8.0 I get the expected behaviour (Aliases being output as-is) but with 4.0.0 and the explicit use of the CCNC only aliases without underscores get output correctly.

**Comment by aaubry** [comment]
It is true that the behavior with naming conventions has changed, because the previous behavior [was considered a bug](https://github.com/aaubry/YamlDotNet/issues/190#issuecomment-231901775).

What is happening is that the naming convention is applied after the alias, which means that the name suffers the following transformations: `QuuxBletch` -> `quux_bletch` -> `quuxBletch`.

However, you can revert to the previous behavior. The transformations are performed by a chain of `ITypeInspector`, each with its own responsibility, and the `SerializerBuilder` allows to control how this chain is constructed. What needs to be done is to swap the order of `YamlAttributesTypeInspector` and `YamlAttributesTypeInspector`, so that the attribute is applied after. The code to perform that is the following:

```C#
var serializer = new SerializerBuilder()
    .WithNamingConvention(new CamelCaseNamingConvention())
    // Workaround to remove YamlAttributesTypeInspector
    .WithTypeInspector(inner => inner, s => s.InsteadOf<YamlAttributesTypeInspector>())
    .WithTypeInspector(
        inner => new YamlAttributesTypeInspector(inner),
        s => s.Before<NamingConventionTypeInspector>()
    )
    .Build();

var deserializer = new DeserializerBuilder()
    .WithNamingConvention(new CamelCaseNamingConvention())
    // Workaround to remove YamlAttributesTypeInspector
    .WithTypeInspector(inner => inner, s => s.InsteadOf<YamlAttributesTypeInspector>())
    .WithTypeInspector(
        inner => new YamlAttributesTypeInspector(inner),
        s => s.Before<NamingConventionTypeInspector>()
    )
    .Build();
```

You can see it in action here: https://dotnetfiddle.net/CkJN3q

**Comment by aaubry** [comment]
Did this fix your problem? Or are you still encountering issues?

**Comment by rabejens** [comment]
Hi,

unfortunately I did not yet have time to test this since I have a lot of other things to do. Currently I have to get my current version of the software to work robustly (which is still on 3.8.0) but when I have the next period to "prettify" and update things I will give it a shot and let you know.

**Comment by aaubry** [comment]
No problem. I'll close the issue, but please reopen it this solution does not work for you.
