### ISSUE TITLE
SemanticErrorException is thrown in situations that seem to have nothing to do with semantic

### ISSUE THREAD

**Issue by mlaily** [aaubry/YamlDotNet#221]
Why would a `SemanticErrorException` be used, for example, when a token is missing, instead of a seemingly more appropriate `SyntaxErrorException`?

I noticed `SyntaxErrorException` only seem to be thrown from the `Scanner`, and `SemanticErrorException` from the `Parser`, but from and end-user perspective, this distinction makes little sense.

When an error is obviously caused by a syntax error, I think the proper exception should be thrown, regardless of where it happened.

What do you think?

**Comment by aaubry** [comment]
I agree. This distinction was inherited from the original implementation of libyaml in C.
How would you suggest that these errors should be handled?

**Comment by mlaily** [comment]
Like I said, I think `SyntaxErrorException` should be used instead of `SemanticErrorException` when the former is more appropriate, regardless of where in the code it happens (Scanner or Parser).

If you agree, I would be more than happy to submit a pull request for that.

**Comment by aaubry** [comment]
I agree. Please go ahead.

**Comment by aaubry** [comment]
I will close this issue as there has been no feedback. Feel free to reopen it if necessary.
