### ISSUE TITLE
YamlNode.ToString() does not generate valid Yaml

### ISSUE THREAD

**Issue by mlaily** [aaubry/YamlDotNet#224]
I find this unsettling, because it looks kind of like Yaml at first sight, but it isn't.

Is this by design? (Maybe to discourage using ToString() to output Yaml from a parsed stream?)

**Comment by aaubry** [comment]
That implementation intends to help while debugging, to provide a human-friendly view of each node. It does not produce yaml because some properties of the node are not obvious when serialized.

**Comment by mlaily** [comment]
What "not obvious when serialized" properties are you talking about?
The `ToString()` implementations seem very straightforward.

I think slight alterations, especially regarding the mapping nodes, would make it more easy to read and human-friendly.

Here is an example:

Currently, the following yaml
```
    a:
        - b
        -   - c
            - d
        - e
```
gives the following `ToString()`:
`{ { a, [ b, [ c, d ], e ] } }`

I think it would a lot more understandable if it were instead:
`{ a: [ b, [ c, d ], e ] }`
(which is, incidentally, valid yaml)
