### ISSUE TITLE
Make YamlNode comparable

### ISSUE THREAD

**Issue by JimiC** [aaubry/YamlDotNet#226]
I stumbled upon this use case, on one of my projects, where I needed to order the nodes by a specific key.
It was no big deal to make a `YamlNodeComparer` myself, but wondering if you are interested into implementing this in the source code.

If so, I can provide a PR.

**Comment by aaubry** [comment]
It might be interesting if you have a meaningful way to implement it.
How would nodes be compared? If you compare a mapping with a sequence, which is "greater"?

**Comment by aaubry** [comment]
I will close this issue as there has been no feedback. Feel free to reopen it if necessary.
