### ISSUE TITLE
Anchor name after deserialization

### ISSUE THREAD

**Issue by robintheilade** [aaubry/YamlDotNet#227]
I've been searching if it is possible to keep the name of the anchors in the deserialized object graph and from what I gather that is not possible and might even be against the idea of anchor names as they exists for serialization purposes.
That said, would it be too much of a mistake to introduce a way to keep the name in the object graph? I'm thinking a solution could be allow the programmer to use an attribute to let YamlDotNet know if a property is supposed to be used to store the name of the anchor, like this

`[YamlAnchorName]
public string Key
{
    get;
    set;
}`

The reason I would like to know the anchor names is that I'm building a generator that takes a YAML file and outputs a map. In that map I would like to output the anchor names for reference back to the YAML file. Otherwise the person responsible for the YAML file has to write duplicate anchor names for each instance.

**Comment by aaubry** [comment]
If you read the document as a `YamlDocument`, you have access to the anchor names. Wouldn't that be a that a better option?
Otherwise, you can implement `IValueDeserializer` to achieve that, since it is used to deserialize each object. The `Deserializer` is just a wrapper around that interface. See this example for a possible implementation: https://dotnetfiddle.net/HYhtdq

**Comment by aaubry** [comment]
If you need, it should be possible to also support setting the stored anchor when serializing, although I have not looked into it.

**Comment by robintheilade** [comment]
IValueSerializer fits my case better than YamlDocument. Thank you for suggesting them.

If you can see the value in having the YamlAnchorNameAttribute I can also do the coding and create a pull request for you.

**Comment by rohahn** [comment]
This sounds interesting. Is there also an easy way to control the anchor naming during serialization? I would like to use YamlDotNet to create a stable file format, that changes as little as possible during multiple deserialize, change, serialize cycles, so different versions of the files can be compared and merged easily.

**Comment by lyze237** [comment]
Sorry to bump this, but I've recently stumbled upon this problem as well.

I'd like to set specific names for anchors during serialization. 

Looked through the source code but it seems that it's a complicated thing to do, especially since I'm not really familiar with the inners of the library.

**Comment by thisisthedave** [comment]
I also need to store the anchor sometimes, for which I created a decorator implementation of `INodeDeserializer`. It's similar to @aaubry's suggestion of using a custom `IValueDeserializer`. Here's what it looks like: (I haven't attempted to compile this, so there may be errors.)
```
    private class MyAnchorGrabbingNodeDeserializer : INodeDeserializer
    {
        private readonly INodeDeserializer _nodeDeserializer;

        public MyAnchorGrabbingNodeDeserializer(INodeDeserializer nodeDeserializer)
        {
            _nodeDeserializer = nodeDeserializer;
        }

        bool INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func<IParser, Type, object> nestedObjectDeserializer, out object value)
        {
            // stash current anchor, e.g. &someImportantKey, to store in a field. This method is recursive, 
            // so store the name in a local variable before it's overwritten by a recursive call.
            var nodeEvent = parser?.Current as NodeEvent;
            string anchor = nodeEvent?.Anchor;
            object result;
            bool success = _nodeDeserializer.Deserialize(parser, expectedType, nestedObjectDeserializer, out result);
            if (result is IStoresAnchorAsKey && anchor != null)
            {
                ((IStoresAnchorAsKey).Key) = anchor;
            }
            value = result;
            return success;
        }
    }

    // Configure the deserializer to use my custom deserializer
    private static Deserializer MakeScriptableObjectDeserializer(ParsingState parsingState)
    {
        var deserializerBuilder = new DeserializerBuilder()
            .WithNodeDeserializer(
                inner => new MyAnchorGrabbingNodeDeserializer(inner), // stores anchor names
                s => s.InsteadOf<ObjectNodeDeserializer>());

        Deserializer deserializer = deserializerBuilder.Build();
        return deserializer;
    }

```

**Comment by Nidhi1819** [comment]
@aaubry 
I need to set specific names for anchors during serialization. I tried looking samples but there isn't any showing how to do this. I also tried to implement IYamlTypeConverter and could do something but alias are not generating. Would high appreciate if you help answer this.
