### ISSUE TITLE
Sample code not up to date

### ISSUE THREAD

**Issue by hakito** [aaubry/YamlDotNet#230]
The sample code at .net fiddle is written for Release 3.3.0 and is not compatible with 4.0.0. It would be great to have some sample code without having to look at the tests.

**Comment by aaubry** [comment]
Thanks for reporting this. I am looking for a way to ensure that the sample code stays up-to-date. Maybe the sample code should be converted to unit tests, and then included in a documentation page.
Do you have any suggestion?

**Comment by hakito** [comment]
I had some thoughts about it and agree, that putting the sample code in a test project is probably the only way to keep the sample code more up to date. (At least regarding breaking changes).

I'd suggest to put the sample code in separate test project and don't mix it with the real tests. At the readme I'd just refer to the sample code in the test project. Remove all links to the outdated sample code.

**Comment by aaubry** [comment]
I've added the existing samples to a test project, and made the necessary changes to make them pass. The next steps will be:
1. have a documentation page when one can see the samples along with their output
2. add more samples
