### ISSUE TITLE
DateTimeConverter

### ISSUE THREAD

**Issue by justinyoo** [aaubry/YamlDotNet#231]
Hi,

I know there's only one converter out-of-the-box, ie. [GuidConverter](https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet/Serialization/Converters/GuidConverter.cs).

YamlDotNet itself can convert string to DateTime automatically and vice-versa. However, if the date/time format is not that expected, it fails conversion. Would it be part of your roadmap to include those frequently used converters within the library at some stage? I can send a PR for `DateTimeConverter`, if you like.

It's probably related to #196 (DateTimeOffset) issue by the way.

Cheers,

**Comment by aaubry** [comment]
Hi,

Sure, it would be good to have a DateTimeConverter so that we can configure the conversion behavior. Please send a PR that adds it. Thanks

**Comment by justinyoo** [comment]
@aaubry Sure. Will send PR soon. Thanks for accepting my suggestion.
