### ISSUE TITLE
Strings converted to numbers

### ISSUE THREAD

**Issue by Untit1ed** [aaubry/YamlDotNet#237]
```
var swaggerDocument = new Dictionary<string, object>(){
   {"version", "2.0"}
};
var serializer = new Serializer();
var result = serializer.Serialize(swaggerDocument);
```

results in `- version: 2.0` instead of `- version "2.0"`

**Comment by replaysMike** [comment]
bump for this issue.

**Comment by replaysMike** [comment]
This is fixed in https://github.com/aaubry/YamlDotNet/pull/239 - but it will have to be reviewed & accepted by Antoine for accuracy - tests pass and fixes this issue.
