### ISSUE TITLE
Intrinsic Function potential implementation?

### ISSUE THREAD

**Issue by avishnyakov** [aaubry/YamlDotNet#243]
More of a question - what would it take to get intrinsic function implementation similar to [AWS Intrinsic Function Reference](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html)?

We are considering using YamlDotNet and keen to see if we could contribute or extend it to support some primitive intrinsic functions such as GetAttr, Join and a few more.

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
