### ISSUE TITLE
Serializing string with newlines adds extra lines

### ISSUE THREAD

**Issue by mwhouser** [aaubry/YamlDotNet#246]
YamlDotNet appears to double the end-of-line markers.

For example:

```c#
var obj = new
{
	Data = "123\n456"
};

var serializer = new YamlDotNet.Serialization.Serializer();
string yaml = serializer.Serialize(obj);
Console.WriteLine(yaml);
```

outputs the following:

```
Data: >-
  123

  456
```

Internally, when I inspect the `yaml` variable, the text includes `Data: >-\r\n  123\r\n\r\n  456\r\n`. So it is indeed adding an extra line.

Whereas I would expect it to be:

```
Data: >-
  123
  456
```

and internally `Data: >-\r\n  123\r\n  456\r\n`.

**Comment by hawkerm** [comment]
I'm not sure if I'm seeing the same issue here but in reverse with deserialization as well.

I'm trying to load in some text from a document section like this:

```
---
Some other text is here which starts our adventure...
There are many lines to this text.

Some are farther away then others and **bold**.
```

However, when I deserialize this the value only contains one newline where the blank line is instead of one at the end of each line.

```
parser.Current.ToString()
"Scalar [anchor = , tag = , value = Some other text is here which starts our adventure... There are many lines to this text.\nSome are farther away then others and **bold**., style = Plain, isPlainImplicit = True, isQuotedImplicit = False]"
```

**Comment by victor9000** [comment]
Adding the following attribute to your property solves this issue.
```
using YamlDotNet.Core;
using YamlDotNet.Serialization;
...
[YamlMember(ScalarStyle = ScalarStyle.Literal)]
public string MyProp { get; set; }
```

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
