### ISSUE TITLE
Support Deserializing to Cuncurrent collections

### ISSUE THREAD

**Issue by AlexanderBaggett** [aaubry/YamlDotNet#250]
What is awkward about this is this library can serialize the stuff just fine. But it fails at the deserialization phase.  That makes it awkward for developers who want to use the same data types in on both ends.

Either we have to do a bunch of casting and store it an different type than how we build our data,  or we have  to have entirely unique data structures on the deserialization phase. 

https://msdn.microsoft.com/en-us/library/system.collections.concurrent(v=vs.110).aspx

**Comment by AlexanderBaggett** [comment]
You could also allow us to pass in a Func<> of whatever type to handle unsupported collections. Either way, something needs to change.

**Comment by AlexanderBaggett** [comment]
It looks like it could be done by making a custom INodeDeserializer   based off of the IEnumerable one https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet/Serialization/NodeDeserializers/EnumerableNodeDeserializer.cs

**Comment by AlexanderBaggett** [comment]
The only thing is,  ReflectionUtlility doesn't appear to be in  YamlDotNet.Serialization.Utilities,  or YamlDotNet.Serialization,
 or YamlDotNet.Core,
or YamlDotNet.Core.Events.  So I don't have a substitution for it.

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
