### ISSUE TITLE
Enum properties do not serialize if set to the first value in the enum (position 0)

### ISSUE THREAD

**Issue by solvingj** [aaubry/YamlDotNet#251]
Removing original description of issue as it's more clearly demonstrated in the first comment below.

**Comment by solvingJ** [comment]
Here's a more pure demonstration of an issue.  You can run it here: 
https://dotnetfiddle.net/WT8jon

```
using System;
using YamlDotNet.Serialization;

public class SampleType
{
	public WorkingEnum BrokenEnumOne { get; set; }
	public WorkingEnum WorkingEnumOne { get; set; }
	public WorkingEnum WorkingEnumTwo { get; set; }
}

public enum WorkingEnum 
{
	First,
	Second,
	Third
}


public class Program
{
	public static void Main()
	{
		var serializer = new SerializerBuilder()
			.Build();
		
		SampleType sample = new SampleType
		{
			BrokenEnumOne = WorkingEnum.First,
			WorkingEnumOne = WorkingEnum.Second,
			WorkingEnumTwo = WorkingEnum.Third
		};
		
		var serialized = serializer.Serialize(sample);
		Console.Write(serialized);
	}
}
```

**Comment by aaubry** [comment]
This is a known (to me) issue. This is because default values are not emitted unless you call `.EmitDefaults()` on the `SerializerBuilder`. The intent was to not serialize properties as null, but as a side effect other default values ended up being dropped. There should probably be different settings to emit nulls and default values. Note that if the first value of the enum is not zero, it will be emitted correctly.

**Comment by solvingJ** [comment]
Ok, sounds good.  I'm glad there's a ticket now.  This way further people won't have to spend 3 hours debugging it and feeling stupid when trying to learn YamlDotNet.

**Comment by solvingJ** [comment]
So to clarify, the effective workaround is numbering the Enum and not using 0. 

For example: 

```
public enum WorkingEnum 
{
	First = 1,
	Second = 2,
	Third = 3
}

**Comment by RedlineTriad** [comment]
Could an attribute be implemented that determines whether or not the default value of a field/property is serialized?

**Comment by aaubry** [comment]
I have opened issue #427 that is related to your question. One of the points is the inclusion of such an attribute. Feel free to join the discussion and provide any feedback that might be relevant. I am closing the issue to avoid duplicate discussion.
