### ISSUE TITLE
Deserializing to an IEnumerable<T> fails with .SerializationException when deserializer tries to instantiate a base class with the properties of the child class in a nested class setup

### ISSUE THREAD

**Issue by AlexanderBaggett** [aaubry/YamlDotNet#252]
I took a look at this exception and am a bit confounded by it.

Basically, what your Deserializer is telling me is that it is looking for a **Child Class** property on a **Base Class** and can't find it.

Well no crap, that property only exists in the child class. Why is is trying to create an instance of this BaseClass?

Even more interesting is that none of the class hierarchy has a direct reference to this Base Class except through inheritance. 

 I could give you a code sample privately that demonstrates this.

**Comment by AlexanderBaggett** [comment]
I found this when I try to deserialize to an IEnumerable<X> instead of something more specific like a list or an array, etc.

**Comment by AlexanderBaggett** [comment]
Unhandled Exception: YamlDotNet.Core.YamlException: (Line: 21237, Col: 13, Idx: 788523) - (Line: 21237, Col: 13, Idx: 788523): Exception during deserialization ---> System.Runtime.Serialization.SerializationException: Property 'ProcessingReason' not found on type 'CaseDocumentBuilder.Import.Data.Employee+CoverageBase'.

**Comment by AlexanderBaggett** [comment]
``
  public class Employee
        {
            public EmployeeDemograhpics Demographics { get; set; }
            public EmployeeOccupation Occupation { get; set; }
            public IEnumerable<EmergencyContact> EmergencyContacts { get; set; }
            public IEnumerable<Dependent> Dependents { get; set; }
            public IEnumerable<Beneficiary> PrimaryBeneficiaries { get; set; }
            public IEnumerable<Beneficiary> ContingentBeneficiaries { get; set; }
            public string DashboardPreference { get; set; }
            public IEnumerable<EmployeeElection> Elections { get; set; }
            public IEnumerable<PreviousJob> EmployementHistory { get; set; }
            public IEnumerable<CoverageInforce> CurrentCoverage { get; set; }
            public IEnumerable<CoverageFuture> FutureCoverage { get; set; }
            public IEnumerable<CoverageTerminated> TerminatedCoverage { get; set; }



            public class CoverageBase
            {
                public Plan.AgeReduction AgeReduction { get; set; }
                // public COFS ChnageOfFamilyStatus {get;set;} //Allen says we don't need it
                public string Correlation { get; set; }
                //   public BenefitCred BenefitCredit{get;set;} //Allen said we aren't bringing this over either.
                public string BenefitType { get; set; }
                public string TPADomain { get; set; }
                public Plan.CostCalculation.EliminationPeriod EliminationPeriod { get; set; }
                public Plan.CoverageTier Tier { get; set; }
                public string TierType { get; set; } //get from L_General
                public string EmployeeCostDeductionCriteria { get; set; } //also from L_General
                public Plan.PrimaryPlanInformation AssociatedPlan { get; set; }

                public decimal? AnnualizedPremium { get; set; }
                public decimal? ApprovedCoverageAmount { get; set; }
                public decimal? ApprovedEmployeeCost { get; set; }
                public decimal? ApprovedEmployerCost { get; set; }
                public decimal? CoveragePriorAgeReduction { get; set; }
                public decimal? MonthlyEmployeeCostPostTax { get; set; }
                public decimal? MonthlyEmployeeCostPreTax { get; set; }
                public decimal? MonthlyEmployerCost { get; set; }
                public decimal? PendingCoverageAmount { get; set; }
                public decimal? PendingEmployeeCost { get; set; }
                public decimal? PendingEmployerCost { get; set; }
                public decimal? SalaryMultiplier { get; set; }
                public decimal? SalaryPercentageAmount { get; set; }

                public DateTime? ApplicationSignedDate { get; set; }
                public DateTime? InitialCobraStartDate { get; set; }
                public DateTime? ValidFrom { get; set; }
                public DateTime? ValidTo { get; set; }
                public DateTime? EffectiveEndDate { get; set; }
                public DateTime EffectiveStartDate { get; set; }
                public DateTime ElectionDate { get; set; }
                public DateTime? CobraAccepted { get; set; }

                public string CoverageName { get; set; }
                public string PCP { get; set; }
                public string PCP_ProviderName { get; set; }
                public string ItemType { get; set; }

                public bool IsCobraElection { get; set; }
                public bool IsExisitingPCPPatient { get; set; }
                public COFSEvent COFS { get; set; }

                public class COFSEvent
                {
                    public string RequestReason { get; set; } //L_General
                    public DateTime RequestDate { get; set; }
                    public DateTime EventDate { get; set; }
                    public bool IsRequestPending { get; set; }
                    public string ReviewerNotes { get; set; }
                    public bool IsApproved { get; set; }
                    public DateTime? ReviewDate { get; set; }
                    public string ReviewedByUserName { get; set; } ///dbo.User
                    public string RequestNotes { get; set; }

                }

            }
            public class CoverageInforce : CoverageBase
            {
              
                public string ProcessingReason { get; set; }
            }
''

**Comment by AlexanderBaggett** [comment]
And yes, these are nested classes.

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
