### ISSUE TITLE
What is needed to control the process of serialization (specifically for a struct)?

### ISSUE THREAD

**Issue by solvingj** [aaubry/YamlDotNet#253]
I've been reading the samples and documentation for a few days now and I've seen a ton of interesting methods and interfaces for customizing various behaviors.  Unfortunately, I still can't deduce how to achieve our goal. 

Here is the struct we're trying to serialize and deserialize.

https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/master/CSharpFunctionalExtensions/Result.cs

I was able to achieve this in Json.Net and we're struggling a bit with Mongo's Bson serializer, but we're getting closer.  

The logic for serializing this struct should be to check IsSuccess() first.  If true, we should serialize the property named "Value" which is generic type T and then stop.  If IsSuccess() is false, then we should serialize the Error property which is a string and then stop.  

Is it possible to introduce this logic?  Can you give any hints or assistance?

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
