### ISSUE TITLE
Serializing JObject to Yaml - "Object does not match target type"

### ISSUE THREAD

**Issue by solvingj** [aaubry/YamlDotNet#254]
Is there an obvious reason this code throws "Object does not match target type" exception?

```
    var jObj = JObject.Parse( @"{ 'this_will_error': 'some_value' }");
    var serializer = new Serializer();
    var yaml = serializer.Serialize(jObj);
```

**Comment by nishant-jain-94** [comment]
Facing same issue

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
