### ISSUE TITLE
Serialize a 0 int value

### ISSUE THREAD

**Issue by ranxian** [aaubry/YamlDotNet#258]
I tried to serialize
```
class A {
  public int number {get; set;} = 0;
}
```
when `number` is 0, there is nothing serialized. I was expecting something like
```
number: 0
```

**Comment by Bond-009** [comment]
Default values are not emitted unless you call .EmitDefaults() on the SerializerBuilder.

**Comment by aaubry** [comment]
Closing because this is a duplicate of #251

**Comment by aaubry** [comment]
I have opened issue #427 that is related to your question. Feel free to join the discussion and provide any feedback that might be relevant.
