### ISSUE TITLE
Two level <<

### ISSUE THREAD

**Issue by tauvinen** [aaubry/YamlDotNet#259]
Simplified example:

```
base: &level1
  X: "X"

base: &level2
  <<: *level1
  Y: "Y"

ok:
  <<: *level1

fail:
  <<: *level2
```

And basic usage like:
```csharp
var deserializer = new DeserializerBuilder().
                  .Build();
var parser = new MergingParser(new Parser(fileReader));
var confFile = deserializer.Deserialize<xxxx>(parser);

```

Deserialize results in exception: "Property '<<' not found on type 'XXX.base'". If "fail" reference is changed to "*level1" it works.

I am not certain if this should work, but would be logical?

**Comment by aaubry** [comment]
I would expect this to work, but the `MergingParser` is a bit of a hack, and maybe it does not handle recursivity. I will look into this when I can.
