### ISSUE TITLE
Scanner with skipComments = false doesn't work

### ISSUE THREAD

**Issue by hmuralt** [aaubry/YamlDotNet#260]
Setting the skipComments parameter of the scanner ctor to false will lead to a SemanticErrorException during parsing (used v. 4.2.0).

When using following parser:
`var parser = new Parser(new Scanner(input, false));`

with following example:
```
# Some comment
key: value
```

the parsing events will be:

1. StreamStart
2. DocumentStart
3. Comment
4. Scalar
5. DocumentEnd

MappingStart is missing after the comment parsing event and with the following MoveNext() call on the parser an exception is thrown:
-> SemanticErrorException: Did not find expected document start

No matter where the comments are located it will result in a SemanticErrorException after the first comment.

**Comment by aaubry** [comment]
This is definitely a bug. I'll look into fixing it. Thanks

**Comment by aaubry** [comment]
I think that I found the bug. I have added an unit test with your example and it passes now. If you can, I would like you to try using [version 4.2.1-issue-2600412 of the package](https://www.nuget.org/packages/YamlDotNet/4.2.1-issue-2600412), to confirm that it works as expected. Thanks

**Comment by hmuralt** [comment]
I've tried it out. It is working. Thank you very much.

**Comment by aaubry** [comment]
This fix has been merged into master, and is included in version 4.2.1, which was just released.
