### ISSUE TITLE
Values with white space-only lines are forcibly double-quoted

### ISSUE THREAD

**Issue by eeskildsen** [aaubry/YamlDotNet#261]
Say we have a class with a single property that's marked for literal scalar style:

```
public class MyProgram
{
    [YamlMember(ScalarStyle = ScalarStyle.Literal)]
    public string code { get; set; }
}
```

We need to deserialize the following:

```
code: |-
  if (condition1) {
    if (condition2) {
      // ...
    }
    // The below line is blank for readability but has spaces for consistent indentation
    
    if (condition3) {
      // ...
    }
  }
```
        
Deserialization succeeds, expect with respect to Environment.NewLine.

```
MyProgram { code="if (condition1) {\n  if (condition2) {\n    // ...\n  }\n  // The below line is blank for readability but has spaces for consistent indentation\n  \n  if (condition3) {\n    // ...\n  }\n}" }
```

However, on serialization, the literal style specification is ignored and double-quote style is used instead.

```
"code: \"if (condition1) {\\n  if (condition2) {\\n    // ...\\n  }\\n  // The below line is blank for readability but has spaces for consistent indentation\\n  \\n  if (condition3) {\\n    // ...\\n  }\\n}\"\r\n"
```

If the white space-only line is removed, the value is serialized as a literal as specified.

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
