### ISSUE TITLE
Allow serialization of classes without field names in YAML

### ISSUE THREAD

**Issue by ramon-garcia** [aaubry/YamlDotNet#262]
If a class has a single field, it should be possible to omit the field name when writting/reading.

This is specially useful for deserializing human-written configuration files. 

The current syntax is too verbose.

For instance, if one has a class Plus that represents some objects to be added

    class Plus {
          list<operands> operands { get; set; }
    };

the current syntax would be something like
```
!!plus
     operands: [ ....]
```
but it would be easier for the user not to have to write "operands:" at all, since it is totally redundant.

At present, this simplification can be achieved by writting a custom serializer (I am following this sample https://dotnetfiddle.net/90XZmu ).

But marking a field as default should be enough.

**Comment by ramon-garcia** [comment]
In addition, there should be examples for writing custom (de)serializers in the repository.

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
