### ISSUE TITLE
Serialization of numeric valid strings

### ISSUE THREAD

**Issue by Narazaka** [aaubry/YamlDotNet#265]
Is there a way to serialize a string that is valid as a number, like "001122" and "1_2_3", as a string?

I tryed as below

```c#
var builder = new SerializerBuilder();
builder.EmitDefaults();
var serializer = builder.Build();
var dic = new Dictionary<string, object> {
  {"key", "001122"},
  {"key2", "1_2_3"},
};
Console.WriteLine(serializer.Serialize(dic));
```

and output was

```yaml
key: 001122
key2: 1_2_3
```

then other yaml parser recognized as below (because of YAML specification)

```sh
js-yaml <<EOM
key: 001122
key2: 1_2_3
EOM
{
  "key": 594,
  "key2": 123
}
```

How can I serialize them as below?

```yaml
key: "001122"
key2: "1_2_3"
```

I read YamlDotNet/Core/Emitter.cs but I have no good idea. (no source value type check?)

**Comment by aaubry** [comment]
I don't think that it is currently possible to change this behavior. But I agree that it should be fixed. I'll assign myself to it and see what can be done.

**Comment by Psilax** [comment]
I created my own implementation of a ChainedEventEmitter based on feedback from StackOverflow to handle strings that parse to int's and force quotes around them.
To bad this issue has been open for so long.

**Comment by joepb** [comment]
3.5 years later and still no fix? :(

**Comment by EdwardCooke** [comment]
This issue was resolved in the 12.x releases.
