### ISSUE TITLE
Please include links to signed nuget everywhere

### ISSUE THREAD

**Issue by osdm** [aaubry/YamlDotNet#266]
Please include link to signed YAML (www.nuget.org/packages/YamlDotNet.Signed) to readme.md and  aaubry.net/pages/yamldotnet.html (which is referenced from yaml.org). I was stupid enough to believe that only unsigned version exists after reading that pages, didn't try to search nuget for them and spent an hour researching alternative solutions. 

Thanks!

**Comment by aaubry** [comment]
I'm sorry to hear about your experience. I have updated the documentation everywhere:
* [Readme](https://github.com/aaubry/YamlDotNet#installing)
* [wiki](https://github.com/aaubry/YamlDotNet/wiki#installing)
* [aaubry.net](http://aaubry.net/pages/yamldotnet.html)
Thanks for reporting this.
