### ISSUE TITLE
 Exception during deserialization

### ISSUE THREAD

**Issue by linwrui** [aaubry/YamlDotNet#272]
I have came up against difficulties:"{"(Line: 1, Col: 1, Idx: 0) - (Line: 2, Col: 1, Idx: 122): Exception during deserialization"}"The innermessage said that there are some property can not find on the type.The quetion is why ,I'm sure that the property is on the type.
Code:
```
`        
    public class OfficeInteractionModels 
    {
        public OfficeInteractionModels()
        {
            InteractionModels = new ObservableCollection<OfficeInteractionModel>();
        }
[YamlIgnore]
        public ObservableCollection<OfficeInteractionModel> InteractionModels { get; set; } 
        [YamlMember]
        public List<OfficeInteractionModel> InteractionModelList
        {
            get => InteractionModels?.ToList();
            set
            {
                foreach (var model in value)
                {
                    InteractionModels.Add(model);
                }
            }
        }}`

        internal static void YamlDeserialize(string input)
        {
            var deserializerBuilder = new DeserializerBuilder().WithNamingConvention(new CamelCaseNamingConvention());

            var deserializer = deserializerBuilder.Build();

            var result = deserializer.Deserialize<OfficeInteractionModels>(input);
            return result;
            //return new YamlDotNet.Serialization.DeserializerBuilder().Build().Deserialize<T>(input);
        }
```

deserializer-input:
!Test.OfficeInteractionModels,%20DataExplorer,%20Version=3.0.0.0,%20Culture=neutral,%20PublicKeyToken=null
InteractionModelList:
- InterationType: ExcelChart
  AnalysisClusterID: d1f0973c-a838-46cd-88bc-848f2125176c
  AnalysisClusterName: 111
  CreatorName: 2323
  FileFullName: 工作簿1
  OperatorID: 20177311628574896
  Tag: DE_20177311628574896
  Excel_WorksheetName: Sheet1
  HisDateTime: 2017/7/31 16:28:57
  Disposed: false

innerMessage:
{"Property 'InteractionModelList' not found on type 'Test.OfficeInteractionModels'."}
StackTrace:
"   在 YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)\r\n   在 YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)\r\n   在 YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)\r\n   在 YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)\r\n   在 DataExplorer.Extensions.StaticMethods.YamlDeserialize[T](String input) 位置 C:\\Users\\lwr\\Source\\Repos\\DataExplorer3.0\\wpf\\DataExplorer\\Extensions\\StaticMethods.cs:行号 63\r\n   在 DataExplorer.Model.OfficeInteractionModels.LoadFromFile() 位置 C:\\Users\\lwr\\Source\\Repos\\DataExplorer3.0\\wpf\\DataExplorer\\Model\\OfficeInteractionModel.cs:行号 50"

**Comment by SmGG** [comment]
@linwrui  what is the reason? I got the problem too

**Comment by SmGG** [comment]
I found the reason, feels like a moron, one of my property was set to private , it should be public! TAT
