### ISSUE TITLE
The saved ScalarNode with empty value is single quoted.

### ISSUE THREAD

**Issue by tvrend** [aaubry/YamlDotNet#273]
I loaded the following yaml:
**cache_size_mb:**

by yamlStream = new YamlStream();
     yamlStream.Load(input);

After save without modification I got:
**cache_size_mb: ''**

by yamlStream.Save(output, false);

In YamlDotNet\Core\Emitter.cs:
  private void AnalyzeScalar(Scalar scalar)
........
            if (value.Length == 0)
            {
                if (scalar.Tag == "tag:yaml.org,2002:null")
                {
.....
                }
                else
                {
.....
                     **scalarData.isBlockPlainAllowed = false;**
                }
             }

Why BlockPlain is not allowed for empty values?

If I change this to true, everything works fine and the empty value saved without single quoted.

What is your opinion?

ps: I found in the changelog:

Version 3.8.0
Fixes and improvements:
**Properly quote empty strings.**

But I do not need these properly quoted empty strings! :)

**Comment by tvrend** [comment]
In version 3.7.0 it works different way:

private void AnalyzeScalar(string value)
		{
			scalarData.value = value;

			if (value.Length == 0)
			{
				scalarData.isMultiline = false;
				scalarData.isFlowPlainAllowed = false;
				scalarData.isBlockPlainAllowed = true;
				scalarData.isSingleQuotedAllowed = true;
				scalarData.isBlockAllowed = false;
				return;
			}

			var flowIndicators = false;
                        var blockIndicators = false;

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.

**Comment by SkylineCookieMonster** [comment]
@aaubry I'm having the same issue as @tvrend had.
Wondering if there is an easy way to allow empty strings without the single quotes?
Otherwise might need to perform a 'replace all' after saving the yaml file.

**Comment by EdwardCooke** [comment]
According to the yaml spec, empty nodes could be treated by parsers as null values. I believe yamldotnet also sets the property to null when there is no value. Because of that, we quote empty, non null, strings so we can make sure they get round tripped to us and other parsers as empty, non-null strings.

Without looking into it more to verify, you might be able to use the YamlMember attribute and specify the quote style. Not sure how it will work with empty strings though.

https://yaml.org/spec/1.2.0/#id2585697

**Comment by SkylineCookieMonster** [comment]
Thanks for the explaination @EdwardCooke, for now we solved our problem with a string replace.
For the people that might be interested:
	StringBuilder sb = new StringBuilder();
	using (StringWriter sw = new StringWriter(sb))
	{
		_yaml.Save(sw, assignAnchors: false);
	}

	string yamlfile = sb.ToString();
	yamlfile = yamlfile.Replace(" ''" + Environment.NewLine, Environment.NewLine);
	return yamlfile;
