### ISSUE TITLE
Parses Version Numbers as Dates

### ISSUE THREAD

**Issue by splatteredbits** [aaubry/YamlDotNet#274]
Given this YAML:

    Version: 1.2.3

YamlDotNet parses this as a date/time, e.g. `1/2/2003 12:00:00 AM`. 

According to the [YAML specification](http://yaml.org/type/timestamp.html) only bare values that use ISO8601 format should be parsed as date/times.

I would expect this to get parsed as a string, e.g. `"1.2.3"`.

**Comment by aaubry** [comment]
This is definitely a bug. Let me see what can be done to fix it.

**Comment by EdwardCooke** [comment]
Without example code, I'm going with this is resolved.

```csharp
using YamlDotNet.Serialization;

var deserializer = new DeserializerBuilder()
    .Build();

var yaml = "Version: 1.2.3";

var value = deserializer.Deserialize(new StringReader(yaml)) as Dictionary<object, object>;

Console.WriteLine(value["Version"].GetType());
```

Results in
```text
System.String
```
