### ISSUE TITLE
Missing Nuget Dependencies

### ISSUE THREAD

**Issue by svanschu** [aaubry/YamlDotNet#275]
YamlDotNet seems to depend on Newtonsoft.Json. I had after update YamlDotNet exception because of missing Newtonsoft.Json dll

I looked into Nuget manager and didn't found an entry in the Dependencies list.

I saw that the YamlDotNet Exception searches for v9 of Json and I had installed v6, because another used nuget package uses v6 of Newtonsoft.Json.

After update Newtonsoft.Json to v9, the exceptions are gone.

**Comment by aaubry** [comment]
YamlDotNet does not depend on any other library. Maybe the dependency is in your own code?
If you post the full exception detail, I may be able to provide more help.

**Comment by svanschu** [comment]
Uhh that's a while ago. I should have made a screenshot. Sorry

My code does not have that dependency, but another library I use perhaps.

It works now after I played around with different version numbers of the used libraries.
