### ISSUE TITLE
YamlDotNet does not serialize tags on complex types

### ISSUE THREAD

**Issue by pkmnfrk** [aaubry/YamlDotNet#284]
Given a small sample of YAML:

```
test:
  prop: !foo yes
  prop2: !foo [ bar ]
```
When it gets parsed and reserialized again, prop2's value will be missing its tag:

```
test:
  prop: !foo yes
  prop2: [bar]
...
```

However, if you examine the parsed structure, then the NodeValue corresponding to the `bar` sequence has its Tag property set to `!foo`.

I'm not 100% sure if this is a legal case to begin with (the YAML specs are frustratingly vague about this), but it is required at the very least by Amazon's CloudFormation scripts, which can contain parts like:

```
        SshKey: !Join [ "\n", !Ref GitSSHKey ]
```

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
