### ISSUE TITLE
Strange Issue trying to desierialize a unity class name

### ISSUE THREAD

**Issue by TheAppsStudioLow** [aaubry/YamlDotNet#286]
Hi I am using your fanytastic example to deserialize a unity yaml file it almost works, the only issue I have is shown in this example 
--- !u!104 &2
RenderSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 6

Can not find property RenderSettings so it seems to be trying to find the property with the class name if I take out the RenderSettings: it works any suggestions for a fix

**Comment by aaubry** [comment]
It is not clear from your description what is your problem, Can you provide a more complete code sample?

**Comment by aaubry** [comment]
I will close this issue as there has been no feedback. Feel free to reopen it if necessary.
