### ISSUE TITLE
How to tell the Deserializer to NOT read Json?

### ISSUE THREAD

**Issue by qaqz111** [aaubry/YamlDotNet#287]
There is a `JsonCompatible` for `SerializerBuilder`, but I didn't found a corresponding one for `DeserializerBuilder`.

Or, is there a way to distinguish Yaml string and Json string accurately?

**Comment by aaubry** [comment]
The `DeserializerBuilder` does not have a "json compatible" setting because YAML is a superset of JSON, meaning that any JSON document is also a valid YAML document, so there's no need for any setting. The JSON document can be parsed as YAML transparently.

**Comment by qaqz111** [comment]
I see. Thanks for explanation.
