### ISSUE TITLE
Yaml load unity scene file(.unity) or prefab file question

### ISSUE THREAD

**Issue by hanbim520** [aaubry/YamlDotNet#292]
yaml load those two type files,but --- !u!29 &1     !u!1  can not be deserialized.I don't know how to solute it.When I save the file,the format is changed. I need help.
![image](https://user-images.githubusercontent.com/7490792/33165640-81f7846c-d072-11e7-8298-92db7652b4b4.png)

**Comment by hanbim520** [comment]
![image](https://user-images.githubusercontent.com/7490792/33196747-37b2e90a-d11c-11e7-9dc1-a064d1adb898.png)
 I found  handle and Suffix are removed to be anchor,so load and save file directly will be Different files

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
