### ISSUE TITLE
IgnoreUnmatchedProperties breaks anchors?

### ISSUE THREAD

**Issue by magnussuther** [aaubry/YamlDotNet#295]
Hi!

I am trying to make use of anchors to reduce duplication in my YAML file, see a tiny example below:

``` yaml
---
Foo: &text Bar

Bar: *text
```

As expected, Deserialize() fails with SerializationException as the property 'Foo' doesn't exist in the Thing I'm trying to deserialize into.  So I use .IgnoreUnmatchedProperties() to ignore those errors, but as a result this fails with AnchorNotFoundException ('Anchor 'text' not found').
I guess that unmatched property was filtered out before the anchor was resolved? Shouldn't the anchors be resolved first, such that Bar gets the value of Foo?

``` c#
class Thing
{
    public string Bar { get; set; }
    // public string Foo { get; set; }
}

[TestMethod]
public void AnchorNotFoundException()
{
    var yaml = @"---
                Foo: &text Bar

                Bar: *text";

    var deserializer = new DeserializerBuilder()
        .WithNamingConvention(new PascalCaseNamingConvention())
        .IgnoreUnmatchedProperties()
        .Build();

    var result = deserializer.Deserialize<Thing>(yaml); // YamlDotNet.Core.AnchorNotFoundException: '(Line: 4, Col: 30, Idx: 77) - (Line: 4, Col: 35, Idx: 82): Anchor 'text' not found'

    Assert.AreEqual("Bar", result.Bar);
}
```

Version: 4.2.3.

**Comment by zacharylayne** [comment]
I am running into this issue as well.

**Comment by zacharylayne** [comment]
I tried using a merge tag as as workaround and simply not defining new values to merge, which has an issue itself. I have something like this:

```
foo: &foo
  someValue: 0

bar: &bar
  <<: &foo
  someValue: 1

baz:
  <<: &bar # instead of : *bar
```

It doesn't throw an error, but at the same time it doesn't merge `bar` values with `foo`.

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
