### ISSUE TITLE
int is no serialized - IMHO a BIG BUG

### ISSUE THREAD

**Issue by HansHammel** [aaubry/YamlDotNet#298]
using v4.2.3.0 nuget package

```
public class SomeCommandMessage : ISomeCommandMessage
{
	public Guid MessageId { get; set; }
	public string Payload { get; set; }
	public int MessageCounter { get; set; }
}
//[...]
public static string ToYaml<T>(this T data)
{
	var stringBuilder = new StringBuilder();
	var serializer = new Serializer();
	stringBuilder.AppendLine(serializer.Serialize(data));
	return stringBuilder.ToString();//.Trim();
}
//[...]
var someCommandMessage = new SomeCommandMessage
{
	MessageId = Guid.NewGuid(),
	Payload = "please",
	MessageCounter = 0 //actually this is a i++
};
//[...]
await Console.Out.WriteLineAsync(someCommandMessage.ToYaml());
```

Output:
```
MessageId: 9509db75-f5e5-47cc-9054-347afba5f6cc
Payload: please
```

MessageCount is missing unless MessageCounter is declared as string

WTF is going wrong here ;-) !?

Greetings, OB.

**Comment by aaubry** [comment]
Since `0` is the default value of int, you need to specify that default values must be emitted when configuring the serializer:

```
var serializer = new SerializerBuilder()
    .EmitDefaults()
    .Build();
```

This behavior should be modified, because you are not the only one to run into this issue [#268] [#251] ...

**Comment by aaubry** [comment]
I have opened issue #427 that is related to your question. Feel free to join the discussion and provide any feedback that might be relevant.
