### ISSUE TITLE
Read-only System.Type properties cause System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by aaron-meyers** [aaubry/YamlDotNet#299]
A System.Type property on an object will cause a System.Reflection.TargetInvocationException to be thrown, even if the System.Type property is read-only.

The exception can be avoided by adding a [YamlIgnore] attribute on the property, or implementing a custom TypeInspector to ignore System.Type properties. It took some debugging effort for me to figure out what was going on though here so ideally this would be handled in YamlDotNet itself rather than throwing this obscure exception.

Not sure if the best solution though is to skip System.Type properties or maybe throw a specific exception when they are found (which could include some info like "System.Type properties are not supported by YamlDotNet and should be excluded using [YamlIgnore] attribute or a custom TypeInspector").

Sample code and exception attached.
[typeissue.cs.txt](https://github.com/aaubry/YamlDotNet/files/1653379/typeissue.cs.txt)
[exception.txt](https://github.com/aaubry/YamlDotNet/files/1653380/exception.txt)

**Comment by aaubry** [comment]
I'd rather not throw a specific exception for System.Type, as there are other types in the framework that cannot be serialized properly, and there's no reason to make a special case for System.Type.
The best approach is probably to handle this as Json.NET does: serialize System.Type as a string using its full name.

**Comment by aaubry** [comment]
Fixed in [https://github.com/aaubry/YamlDotNet/releases/tag/v4.3.0](release 4.3.0)
