### ISSUE TITLE
Is it possible to YamlAlias enum values?

### ISSUE THREAD

**Issue by bj0** [aaubry/YamlDotNet#30]
I was wondering if YamlAlias could be applied to enum values like they can with object properties.  

One useful application of this would be for strings that can't be a variable name.  For example:

```
enum Buttons
{
    ...

    [YamlAlias("go-home")]
    [Description("go-home")]
    GoHome,

    ...
}
```

This way the string "go-home" can be deserialized into an enum value.

**Comment by copygirl** [comment]
2 years have passed, is there a way to do this now, or is the feature request still open?

**Comment by solvingJ** [comment]
@aaubry Do you think you'll ever add support for this?

**Comment by aaubry** [comment]
I think that this would be a neat feature. I don't have much time to dedicate to this project at the moment, though. Of course, if someone implemented this and sent a pull request, I would gladly accept it :)

**Comment by solvingJ** [comment]
First i need to figure out how to get my enums to even serialize at all.  No examples of enum serialization.  The only reference to "enum" in the samples project is when converting Yaml to JSON.

**Comment by aaubry** [comment]
You don't need to do anything special. Just declare a property of that type: https://dotnetfiddle.net/RqYguF

**Comment by solvingJ** [comment]
I notice you used MyEnum.Second instead of MyEnum.First.  When I change to First it no longer works.  You must have noticed that.

**Comment by Matthew-Davey** [comment]
Does anyone know of an alternative library which supports enums?

**Comment by hydrojumbo** [comment]
@solvingj I did not look too deep but I believe that has to do with the serialization behavior with respect to default values. If you explicitly declare the enum's integer equivalents such that First is not = 0 (the default if undeclared), it works as expected:

```
public enum MyEnum {
	First = 1,
	Second = 2
}
```
To convince yourself, notice that if you set the values such that First has a default value, it works as it currently does:
```
public enum MyEnum {
	First = 0,
	Second = 1
}
```
I have yet to determine how to use attributes to override the name, which is what this issue is actually about.

**Comment by Nexxkinn** [comment]
That is stupid and should be changed. Seriously, why?

**Comment by aaubry** [comment]
This is an unintended consequence of not emitting default values. I intend to fix this eventually. If you want it sooner, you're welcome to submit a pull request.

**Comment by MiYanni** [comment]
Instead, I simply implemented a type converter for enum strings. This is similar to Newtonsoft's `[JsonConverter(typeof(StringEnumConverter))]`, except it is for all enums.

Decorate your enums like this (mine are generated from NJsonSchema):
```csharp
internal enum SecurityType
{
    [System.Runtime.Serialization.EnumMember(Value = @"apiKey")]
    ApiKey = 0,

    [System.Runtime.Serialization.EnumMember(Value = @"http")]
    Http = 1,

    [System.Runtime.Serialization.EnumMember(Value = @"oauth2")]
    Oauth2 = 2,

    [System.Runtime.Serialization.EnumMember(Value = @"openIdConnect")]
    OpenIdConnect = 3,
}
```

Then, use this type converter:
```csharp
public class YamlStringEnumConverter : IYamlTypeConverter
{
    public bool Accepts(Type type) => type.IsEnum;

    public object ReadYaml(IParser parser, Type type)
    {
        var parsedEnum = parser.Expect<Scalar>();
        var serializableValues = type.GetMembers()
            .Select(m => new KeyValuePair<string, MemberInfo>(m.GetCustomAttributes<EnumMemberAttribute>(true).Select(ema => ema.Value).FirstOrDefault(), m))
            .Where(pa => !pa.Key.IsNullOrEmpty()).ToDictionary(pa => pa.Key, pa => pa.Value);
        if (!serializableValues.ContainsKey(parsedEnum.Value))
        {
            throw new YamlException(parsedEnum.Start, parsedEnum.End, $"Value '{parsedEnum.Value}' not found in enum '{type.Name}'");
        }

        return Enum.Parse(type, serializableValues[parsedEnum.Value].Name);
    }

    public void WriteYaml(IEmitter emitter, object value, Type type)
    {
        var enumMember = type.GetMember(value.ToString()).FirstOrDefault();
        var yamlValue = enumMember?.GetCustomAttributes<EnumMemberAttribute>(true).Select(ema => ema.Value).FirstOrDefault() ?? value.ToString();
        emitter.Emit(new Scalar(yamlValue));
    }
}
```

Usage looks like this:
```csharp
// To deserialize:
var securityType = (new DeserializerBuilder().WithTypeConverter(new YamlStringEnumConverter()).Build()).Deserialize<SecurityType>(yamlText);
// To serialize:
var securityTypeYaml = (new SerializerBuilder().WithTypeConverter(new YamlStringEnumConverter()).Build()).Serialize(securityType);
```

**Comment by Nioux** [comment]
Hello,

I had this need, and the answer of MiYanni was working like a charm, but I changed the name of the attribute to match the YamlMember :
```
    public class YamlStringEnumConverter : IYamlTypeConverter
    {
        public bool Accepts(Type type) => type.IsEnum;

        public object ReadYaml(IParser parser, Type type)
        {
            var parsedEnum = parser.Consume<Scalar>();
            var serializableValues = type.GetMembers()
                .Select(m => new KeyValuePair<string, MemberInfo>(m.GetCustomAttributes<YamlMemberAttribute>(true).Select(ema => ema.Alias).FirstOrDefault(), m))
                .Where(pa => !String.IsNullOrEmpty(pa.Key)).ToDictionary(pa => pa.Key, pa => pa.Value);
            if (!serializableValues.ContainsKey(parsedEnum.Value))
            {
                if(parsedEnum.Value == "null")
                {
                    return null;
                }
                var value = parsedEnum.Value.Substring(0, 1).ToUpper() + parsedEnum.Value.Substring(1);
                return Enum.Parse(type, value);
            }

            return Enum.Parse(type, serializableValues[parsedEnum.Value].Name);
        }

        public void WriteYaml(IEmitter emitter, object value, Type type)
        {
            var enumMember = type.GetMember(value.ToString()).FirstOrDefault();
            var yamlValue = enumMember?.GetCustomAttributes<EnumMemberAttribute>(true).Select(ema => ema.Value).FirstOrDefault() ?? value.ToString();
            emitter.Emit(new Scalar(yamlValue));
        }
    }
```

I also remove the exception when no attribute was available, and capitalized the first character in this case, but I'm sure there are better ways for doing this.

**Comment by theficus** [comment]
Unfortunately this solution doesn't work if you want to ignore processing of certain enum values.

For example, in a case where you have something like this:

```csharp
public enum SomeEnum 
{
    [YamlIgnore]
    DoNotUse,
    [YamlMember(Alias="someValue")]
    SomeValue,
    [YamlMember(Alias="someOtherValue")]
    SomeOtherValue
}

public class SerializableClass 
{
    [YamlMember(DefaultValuesHandling = DefaultValuesHandling.OmitDefaults)]
    public SomeEnum SomeEnum
    {
        get;
        set;
    }
}
```

The expectation would be that the `YamlIgnore` value would be ignored and the SomeEnum value wouldn't be emitted in the YAML if it's set to `None`.

In theory, this should be as simple as just not emitting anything in WriteYaml, but this causes the serialization to fail with an error like this: `Expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS, got MappingEnd`. I'm assuming this is because by the time `WriteYaml` is called, there's an expectation that a value gets and there doesn't seem to be a way to say, "no, really, don't emit this". `Accepts()` only works at a type level.

I had to work around this by doing a hacky approach of doing something like:
```
[YamlIgnore]
public SomeEnum SomeEnum 
{ 
  get;
  set;
}

[YamlMember(DefaultValuesHandling = DefaultValuesHandling.OmitNull)]
public string SomeEnumSerializable => MyEnumParserThingy(this.SomeEnum);
```

Which of course works as expected, but it is a very inelegant solution to something that seems like the framework should handle natively. Despite this issue being closed, I don't see any good or obvious way to work around this. It's quite a frustrating limitation.

**Comment by EdwardCooke** [comment]
What it sounds like may be needed for your use case is another method on the type converter interface, something like ShouldIgnore(object value) or maybe a new interface. We would then call that before we serialize it. I think it would be best to open a new issue though since it’s different than this one.

**Comment by lgarczyn** [comment]
My version of the enum converter, not requiring the use of explicit attributes:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using JetBrains.Annotations;
using YamlDotNet.Core;
using YamlDotNet.Core.Events;
using YamlDotNet.Serialization;

// TODO: to remove on next release
// https://github.com/aaubry/YamlDotNet/issues/586
internal sealed class YamlStringEnumConverter: IYamlTypeConverter
{
    public bool Accepts(Type type) => type.IsEnum;

    private static string GetStringValue(MemberInfo member)
    {
        return
            member.GetCustomAttributes<EnumMemberAttribute>(true).FirstOrDefault()?.Value ??
            member.GetCustomAttributes<YamlMemberAttribute>(true).FirstOrDefault()?.Alias ??
            member.Name;
    }

    [NotNull]
    public object ReadYaml(IParser parser, Type type)
    {
        Scalar parsedEnum = parser.Consume<Scalar>();
        Dictionary<string, string> serializableValues =
            type.GetMembers(BindingFlags.Public | BindingFlags.Static)
                .ToDictionary(m => m.Name, GetStringValue);

        if (!serializableValues.ContainsKey(parsedEnum.Value))
        {
            throw new YamlException(parsedEnum.Start, parsedEnum.End, $"Value '{parsedEnum.Value}' not found in enum '{type.Name}'");
        }

        return Enum.Parse(type, serializableValues[parsedEnum.Value]);
    }

    public void WriteYaml(IEmitter emitter, object value, Type type)
    {
        if (value == null)
        {
            throw new YamlException("Value cannot be null");
        }
        MemberInfo enumMember = type.GetMember(value.ToString()).FirstOrDefault();

        if (enumMember == null)
        {
            throw new YamlException("Cannot find member info for enum value");
        }
        emitter.Emit(new Scalar(GetStringValue(enumMember)));
    }
}
```
