### ISSUE TITLE
DefaultValue attribute does not work during deserialization

### ISSUE THREAD

**Issue by stefashkaa** [aaubry/YamlDotNet#300]
Is there any mechanism to work around this issue(for example, a special attribute that sets the default values, but I did not find it)?
[YamlMember(Alias = "enabled")]
[DefaultValue(false)]
public Boolean Enabled { get; set; }

**Comment by Hebo-Y** [comment]
Running into same problem. Did you get a workaround for this?

**Comment by stefashkaa** [comment]
> Running into same problem. Did you get a workaround for this?

I don't exactly remember because it was one year ago... But for working with 'DefaultValue' attributes you can customize serializer/deserializer.

**Comment by Vladimir35** [comment]
DefaultValue is not being handled correctly :-( as described above. Is there an example of a custom serialized for that?

**Comment by aaubry** [comment]
I have provided an answer in #465
