### ISSUE TITLE
Null properties are not being serielized

### ISSUE THREAD

**Issue by mdmoura** [aaubry/YamlDotNet#310]
I have the following class:

    public class Conversion {
        public Int32? Id { get; set; }
        public String Unit { get; set; }
    }

Then I created the following Conversion where Id is null:

    Conversion conversion = new Conversion { Name = "something};

When I serialize it Id does not show on YAML file.

How can I end up with the following on YAML file?

    id: 
    unit: something

Thank You

**Comment by lassade** [comment]
call `EmitDefaults` when building your serializer

**Comment by mdmoura** [comment]
@lassade thank you

**Comment by aaubry** [comment]
I have opened issue #427 that is related to your question. Feel free to join the discussion and provide any feedback that might be relevant.
