### ISSUE TITLE
SyntaxErrorException on deserializing Json

### ISSUE THREAD

**Issue by springy76** [aaubry/YamlDotNet#312]
I have a Json string (produced by Active Collab) which gets deserialized by Newtonsoft.Json just fine. YamlDotNet throws a SyntaxErrorException "While parsing a quoted scalar, find unknown escape character".

The Json contains a string containing the escape sequence `\/` -- can't say what the standard says about it, but Newtonsoft.Json has no problems with it.

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
