### ISSUE TITLE
surround value with double quotes

### ISSUE THREAD

**Issue by dragouf** [aaubry/YamlDotNet#315]
I have number which I need to keep as string in my yaml and so I need to surround them with quotes.

I tried to find how to achieve that with your libraries but I didn't found how to achieve that.

Is there a way to do that ?

**Comment by aaubry** [comment]
You can use the `YamlMember` attribute to control this:

```c#
public class QuotedInt
{
	[YamlMember(ScalarStyle = ScalarStyle.DoubleQuoted)]
	public int Value { get; set; }
}
```

[example](https://dotnetfiddle.net/LrfVZ4)

**Comment by dragouf** [comment]
Thanks, unfortunately I serialize a dynamic object and I can't do this.

I ended up doing something like this but I'm really not sure it's the best solution especially the typeof(Object) condition :

```
public class QuoteSurroundingEventEmitter : ChainedEventEmitter
{
    public QuoteSurroundingEventEmitter(IEventEmitter nextEmitter)  : base(nextEmitter)
    { }

    public override void Emit(ScalarEventInfo eventInfo, IEmitter emitter)
    {
        if(eventInfo.Source.StaticType == typeof (Object))
            eventInfo.Style = ScalarStyle.DoubleQuoted;
            base.Emit(eventInfo, emitter);
    }
}
```

and use it like this :
```
var serializer = new SerializerBuilder()
                .WithEventEmitter(nextEmitter => new QuoteSurroundingEventEmitter(nextEmitter))
                .Build();
```

**Comment by lvpeng2016** [comment]
cool

**Comment by daniol** [comment]
Use WithQuotingNecessaryStrings():
`var serializer = new YamlDotNet.Serialization.SerializerBuilder().WithQuotingNecessaryStrings().Build();`
