### ISSUE TITLE
Wrongly serializaliztion of number with leading zeros

### ISSUE THREAD

**Issue by sekkit** [aaubry/YamlDotNet#317]
protocol_type: server_api
protocol_uid: 137PQCQPSZ7382CU6EIKW2YVIU
oid: 0000000002
protocol_name: add_friend
has_cb: true
func_args:
- ArgName: friend_uid
  ArgTypeName: Str
  ArgValue: 0000000004
callback_args:
- ArgName: ok
  ArgTypeName: Bool
- ArgName: msg
  ArgTypeName: Str

this dateset is wrong.
the correct form should be "ArgValue: '0000000004'" instead of integer. Because orginal object is string type.

with jsoncompatible option, this issue can be avoided.
BUT pyyaml will produce correct result with default setting.

**Comment by sekkit** [comment]
Any progress on this issue?

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.
