### ISSUE TITLE
Is there a way to honour JsonExtensionData on an object?

### ISSUE THREAD

**Issue by pms1969** [aaubry/YamlDotNet#322]
I'm trying to use YamlDotNet to serialise a swaggerDoc (provided by swashbuckle) object into yaml.

the Json is serialised correctly with the vendor extensions being rendered at the parameter level.  However, when serialising as yaml, the extensions are output as an array of "extensions".  Looking at the swaggerDoc definition for Operation, the Extensions property is annotated with `[JsonExtensionData]`, which tells the json serialiser to treat the dictionary as if it were a set of properties.  I've basically lifted the code from [this stackoverflow post](https://stackoverflow.com/a/49695626/186184)

The output I get is:
```yaml
    get:
      tags:
      - Thing
      summary: Gets a thing
      consumes: []
      produces:
      - text/plain
      - application/json
      - text/json
      parameters: {}
      responses:
        200:
          description: Thing
          schema:
            type: array
            items:
              $ref: '#/definitions/Thingy'
      extensions:
        x-vendor-extension:
          type: http
          http-method: GET
          uri: https://localhost/
          request-parameters:
            integration.request.header.x-custom-header: "a value'"
```

And what I want to output is:
```yaml
    get:
      tags:
      - Thing
      summary: Gets a thing
      consumes: []
      produces:
      - text/plain
      - application/json
      - text/json
      parameters: {}
      responses:
        200:
          description: Thing
          schema:
            type: array
            items:
              $ref: '#/definitions/Thingy'
      x-vendor-extension:
        type: http
        http-method: GET
        uri: https://localhost/
        request-parameters:
          integration.request.header.x-custom-header: "a value'"
```

Any help would be greatly appreciated.

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.

**Comment by VisualBean** [comment]
I came across the same problem now - is there a solution to this? 
A YamlDotNet equivalent of `JsonExtensionData` ?
