### ISSUE TITLE
yaml with BOM

### ISSUE THREAD

**Issue by dragouf** [aaubry/YamlDotNet#324]
when I have a yaml with BOM at the begining of the file I get something like : 

(Line: 2, Col: 5, Idx: 44) - (Line: 2, Col: 5, Idx: 44): Mapping values are not allowed in this context.

Is there something to do to load file even if they have a BOM ?

**Comment by aaubry** [comment]
I will close this issue as there has been no feedback. Feel free to reopen it if necessary.
