### ISSUE TITLE
Serializer.Serialize() adds a "\r\n" after serialized data.

### ISSUE THREAD

**Issue by tommymh** [aaubry/YamlDotNet#327]
Is there a way to disable this?  I realize its almost definitely intended functionality, but I'm serializing into a MemoryStream and don't need this extra line break.

**Comment by fatto** [comment]
They use (this)[https://github.com/aaubry/YamlDotNet/blob/f96b7cc40a0498f8bafdeb49df3aa23aa2c60993/YamlDotNet.Test/StringExtensions.cs#L30] on Test so I guess no!?

**Comment by tommymh** [comment]
It seems to me like this is not an example of best practices.  You shouldn't have to worry about extra data being inserted when you serialize/deserialize an object.

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if this is still an issue.
