### ISSUE TITLE
Does not correctly convert nested lists

### ISSUE THREAD

**Issue by btusakul** [aaubry/YamlDotNet#329]
If I read in a file that contains the following YAML: 
 ```
- test1
-   - test2
     - test3
```

Then run the following code: 

$fileStream = new-object System.IO.StringReader([string]$yamlString)
$yamlStream = New-Object YamlDotNet.RepresentationModel.YamlStream
$yamlStream.Load([System.IO.TextReader]$fileStream)

the output treats 'test2' and 'test3' as values in the same list as 'test1', even though 'test2' and 'test3' should be in a nested list.

**Comment by aaubry** [comment]
It seems to be parsing correctly - https://dotnetfiddle.net/l3T3Fz
I get a top-level sequence with two elements, and the second is another sequence with two scalars. Can you double check?

**Comment by aaubry** [comment]
I will close this issue as there has been no feedback. Feel free to reopen it if necessary.
