### ISSUE TITLE
Deserializing arbitrary YAML without creating types?

### ISSUE THREAD

**Issue by fj** [aaubry/YamlDotNet#332]
Is there a way to use YamlDotNet to deserialize YAML to raw strings, lists, or dictionaries when the structure of the YAML isn't known in advance and can be arbitrary? For example, is `ExpandoObject` a possibility?

**Comment by aaubry** [comment]
Sure, either [deserialize to `Object`](https://dotnetfiddle.net/D08adG), or use [YamlStream to load the document(s)](https://dotnetfiddle.net/rrR2Bb).

Deserializing as object:
```c#
var deserializer = new DeserializerBuilder().Build();
var result = deserializer.Deserialize<object>(yaml);
```

Using YamlStream:
```c#
var stream = new YamlStream();
stream.Load(new StringReader(yaml));
// Read stream.Documents
```

**Comment by aaubry** [comment]
Id you deserialize to object, the following default types will be used:

| Node Type | CLR type |
|--|--|
| scalar | String |
| sequence | List<Object> |
| mapping | Dictionary<Object, Object> |

**Comment by fj** [comment]
Thanks! In this case the `Dictionary`'s values would always be one of `String`, `List`, or another `Dictionary`, right?

**Comment by aaubry** [comment]
Exactly. Unless a node has a tag, the above types will be used depending on the node's type. If the node has a tag, you will need to register a tag mapping, indicating which .NET type corresponds to that tag.

**Comment by bjorg** [comment]
Is there an easy what to change the default type for mapping to `Dictionary<string, object>`?

**Comment by ohads-MSFT** [comment]
> Id you deserialize to object, the following default types will be used:
> 
> Node Type	CLR type
> scalar	`String`
> sequence	`List<Object>`
> mapping	`Dictionary<Object, Object>`

This is really useful information, is it documented anywhere?
