### ISSUE TITLE
How get value by key?

### ISSUE THREAD

**Issue by vurf** [aaubry/YamlDotNet#334]
I have rich yaml content, how get value by yaml key?
e.g

```
Configs:
    Pdf:
        Content: tou.pdf
```

And I need value tou.pdf. Do you have any method for find by key `GetValue("Configs.Pdf.Content")` and return tou.pdf?

**Comment by vurf** [comment]
@Iamsodarncool , no, I changed my job )))

**Comment by Iamsodarncool** [comment]
lol fair enough

**Comment by aaubry** [comment]
Sorry for not answering sooner. There's no json-path-like syntax, but you could achieve something similar by deserializing to `dynamic`. This is the same as deserializing to `object` and will cause the deserializer to use `Dictionary<,>`, `List<>` and `string` for mappings, sequences and scalars respectively. Then you can take advantage of dynamic's syntax to write:

```c#
var deserializer = new DeserializerBuilder().Build();
var res = deserializer.Deserialize<dynamic>(yaml);

string value = res["Configs"]["Pdf"]["Content"];
```

**Comment by Iamsodarncool** [comment]
Awesome, thank you!
