### ISSUE TITLE
The Deserialization example appears to be outdated

### ISSUE THREAD

**Issue by wegry** [aaubry/YamlDotNet#335]
Using YamlDotNet 5.0.1 it looks like the example linked from http://aaubry.net/pages/yamldotnet.html is no longer valid. It links to https://dotnetfiddle.net/HD2JXM.

Using a constructor argument for namingConvention appears to be what's busted. I believe the correct code looks something like the following (forgive the non-C# example):

```f#
let deserializer =
    new DeserializerBuilder()
    |> fun x -> x.WithNamingConvention(new CamelCaseNamingConvention()).Build()

deserializer.Deserialize<Order>(input)
```

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion, but thank you for reporting this error. In the meantime the documentation has moved and now [correctly indicates the proper way to select the naming convention](https://github.com/aaubry/YamlDotNet/wiki/Serialization.Deserializer#withnamingconventioninamingconvention).
