### ISSUE TITLE
NuGet Package version issue

### ISSUE THREAD

**Issue by apavelm** [aaubry/YamlDotNet#336]
Hi there!
Could you please comment the situation around https://github.com/andrewlock/NetEscapades.Configuration/issues/26

Very likely that YamlDotNet needs a little fix

**Comment by aaubry** [comment]
I have commented on that thread. It turns out that there is indeed a bug in the build script, but the root of that situation is that one should not attempt to use different major releases.

**Comment by apavelm** [comment]
Thank you. Very appreciate.
