### ISSUE TITLE
how to serialize multiline strings without double quotes

### ISSUE THREAD

**Issue by s2quake** [aaubry/YamlDotNet#340]
hello

i want to serialize following string without double quotes.

    "type\r\n \r\na"

the exepected result is as:

    type
     
    a

but if there is space after \r\n characters, the strings are surrounded of double quotes.

I'd appreciate it if you could tell me how to serialize multiline string without surrounding double quotes.

here is sample code

    var yamlSerializer = new SerializerBuilder().Build();
    var text1 = yamlSerializer.Serialize("type\r\n\r\na"); 
    var text2 = yamlSerializer.Serialize("type\r\n \r\na");

and new line output twice. i think it's a bug.

    var text1 = yamlSerializer.Serialize("type\r\n\r\na");

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if this is still an issue.
