### ISSUE TITLE
Deserialization: Respect readonly properties

### ISSUE THREAD

**Issue by HerrRiebmann** [aaubry/YamlDotNet#342]
Deserialize properties with just a getter raises the following exception:
> Exception during deserialization
> at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
> 

To deserialize readonly properties, you can use the DerserializerBuilder:
(_Which is not very intuitive on first use_)
```C#
var deserializer = new YamlDotNet.Serialization.DeserializerBuilder()
                                    .IgnoreUnmatchedProperties().Build();
```
It would be possible to use **true** as the initial value. But I think it just covers the exception, not the cause. The **IgnoreUnmatchedProperty** should raise an error, if the yaml contains a property, which does not exist. But not, if it exists and is readonly.
Most other known serializer respect the Property/Field-access, right from the start.

Example which fails at **id** without overriding the property:
```C#
    public class Room
    {
        public Room(string type, int no, bool free)
        {
            RoomType = type;
            No = no;
            Free = free;
            LastModify = DateTime.Now;
        }

        private string _roomType = string.Empty;
        public string RoomType
        {
            get { return _roomType; }
            set {
                if (_roomType != value)
                {
                    _roomType = value;
                    LastModify = DateTime.Now;
                }
            }
        }

        private int _no;
        public int No
        {
            get { return _no; }
            set
            {
                if (_no != value)
                {
                    _no = value;
                    LastModify = DateTime.Now;
                }
            }
        }

        public string Id => $"{_roomType}.{_no}";

        private DateTime _lastModify = DateTime.Now;
        public DateTime LastModify
        {
            get { return _lastModify; }
            set
            {
                if (_lastModify == value)
                    return;
                _lastModify = value;
                Notify();
            }
        }

        private bool _free;
        public bool Free
        {
            get { return _free; }
            set
            {
                if (_free == value)
                    return;
                _free = value;
                LastModify = DateTime.Now;
                Notify();
            }
        }
    }
```

The GetProperty-Method might return **_null_** in that case.

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if this is still an issue.
