### ISSUE TITLE
Naming conventions on .Net Core

### ISSUE THREAD

**Issue by MrTarantula** [aaubry/YamlDotNet#344]
I'm attempting to deserialize an object in .Net Core 2.1 but receive an error `Property 'sitename' not found on type 'Configuration'`. Here's the class:

```C#
public class Configuration
{
    public string SiteName { get; set; }
    public string HostName { get; set; }
}
```

And here's how I'm building the deserializer:

```C#
using (var input = File.OpenText(Path.Combine(Directory.GetCurrentDirectory(), configFile)))
{
    var config = new YamlDotNet.Serialization.DeserializerBuilder()
    .WithNamingConvention(new PascalCaseNamingConvention()).Build().Deserialize<Configuration>(input);
}
```

If I change the property names either in the YAML file or in the class, it works. But isn't the whole point of naming conventions that I don't have to?

**Comment by aaubry** [comment]
The naming convention specifies how names are translated from how member names are mapped from .NET to YAML. They all assume a standard naming convention in .NET, and thus are named after the convention used in YAML. Using the `PascalCaseNamingConvention` would mean that your `SiteName` property would also be named `SiteName` in YAML. If you had used `CamelCaseNamigConvention`, the property would be named `siteName` in YAML.
In your case the naming convention seems to be all lowercase. There's no built-in naming convention like that in YamlDotNet, so you have two choices:
* Create your own naming convention by implementing `INamingConvention`
* Change your YAML document to use a built-in naming convention. You can choose one of these:
  * [CamelCase - siteName](https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet/Serialization/NamingConventions/CamelCaseNamingConvention.cs)
  * [PascalCase - SiteName](https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet/Serialization/NamingConventions/PascalCaseNamingConvention.cs)
  * [Underscored - site_name](https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet/Serialization/NamingConventions/UnderscoredNamingConvention.cs)
  * [Hyphenated - site-name](https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet/Serialization/NamingConventions/HyphenatedNamingConvention.cs)

**Comment by MrTarantula** [comment]
I see. My thought process was wrong. I only need to deserialize so my understanding was that I was taking underscored YAML and mapping to Pascal case members, so I needed `PascalCaseNamingConvention`. Thanks for the clarification.
