### ISSUE TITLE
Creating a new IYamlTypeConverter

### ISSUE THREAD

**Issue by craigb** [aaubry/YamlDotNet#346]
I have a data type that adds a small piece of annotation to the object model that I want to deserialize to. I want this to be an optional piece of metadata because the file becomes overly verbose if I strictly use the object in question.

``` csharp
/// <summary>
/// Wrapper for types that understands how to merge
/// </summary>
/// <typeparam name="T"></typeparam>
public class ConfigElement<T>
{
    /// <summary>
    /// Create a config element with a given value and specified merge behavior
    /// </summary>
    /// <param name="value"></param>
    /// <param name="mergeBehavior"></param>
    public ConfigElement(
        T value = default,
        MergeBehavior mergeBehavior = MergeBehavior.Ignore)
    {
        Value = value;
        MergeBehavior = mergeBehavior;
    }

    public T Value { get; }

    public MergeBehavior MergeBehavior { get; }
}
```

My goal is to allow users to specify just a `Value` and get an implied default value for the `MergeBehavior`. I'm very new to the codebase, my questions are:
1. Should this be implemented in an `IYamlTypeConverter` or an `INodeDeserializer`? I can't really understand the specific differences between these.
2. What facility I should use to backtrack when I'm parsing? I won't be able to know, for instance, whether the object being parsed is a `ConfigElement<Dictionary<string, string>>` or not until I extract it and look at it. Would the RepresentationModel be appropriate for this?

**Comment by aaubry** [comment]
I'm sorry I was unable to answer this question in a timely fashion. As you have certainly moved on to other things, I will close this issue, but feel free to reopen it if this is still an issue.
