### ISSUE TITLE
No interfaces for serializers?

### ISSUE THREAD

**Issue by grofit** [aaubry/YamlDotNet#350]
I have a scenario where I want to convert some json to yaml and this looks like the easiest path, but one worrying thing is that there is no interface for `Serializer` or `Deserializer` so it is difficult to mock, is there any reason why there is no `IYamlSerializer` or `IYamlDeseralizer` or anything which those classes implement so we can then just use that as the contract and mock the `Serializer` dependencies for unit testing etc?

**Comment by aaubry** [comment]
There's no particular reason for that. If you want to extract the interfaces and submit a pull request, I will publish an updated package immediately.

**Comment by grofit** [comment]
Closing this as the merge has added interfaces.
