### ISSUE TITLE
SerializerBuilder should take a Recursion Limit/maxRecursion as an argument

### ISSUE THREAD

**Issue by dbpiper** [aaubry/YamlDotNet#352]
Currently the Recursion Limit/maxRecursion for SerializerBuilder/objectGraphTraversalStrategyFactory seems to be hardcoded to 50. 

This is quite inflexible. As it means that someone who happens to have a tree with a depth greater than 50 (for example an application I am writing: [Kata](https://github.com/dbpiper/Kata/)) simply gets the error "Too much recursion when traversing the object graph." Ideally this would be simply changed to an optional argument in SerializerBuilder.

The 50 number is used 
on what is currently line 72 in the SerializerBuilder constructor:
`objectGraphTraversalStrategyFactory = (typeInspector, typeResolver, typeConverters) => new FullObjectGraphTraversalStrategy(typeInspector, typeResolver, 50, namingConvention ?? new NullNamingConvention());`

Link to file with hard coded value: [SerializerBuilder ](https://github.com/aaubry/YamlDotNet/blob/50dadfbe0d642a931cafe01237e3e735cfe4aeb6/YamlDotNet/Serialization/SerializerBuilder.cs).

**Comment by aaubry** [comment]
I totally agree. I have a method named [WithMaximumRecursion](https://github.com/aaubry/YamlDotNet/pull/353/files#diff-86074b6acff29ccad667aca741f62ac5R83) that allows you to specify the value for the limit.
A pre-release package should be available on NuGet soon. I would apreciate if you could try it and confirm if it addresses your needs. The version is [`5.1.1-issue-352-max-recursion0504`](https://www.nuget.org/packages/YamlDotNet/5.1.1-issue-352-max-recursion0504)

**Comment by dbpiper** [comment]
Yep that fixes the depth issue!

**Comment by aaubry** [comment]
Release 5.2.0 includes these changes. It should be available in a few minutes.
