### ISSUE TITLE
Convert the properties names from snake_case to PascalCase

### ISSUE THREAD

**Issue by mdmoura** [aaubry/YamlDotNet#355]
I am using snake_case on an YAML file and deserializing it as follows:

      var deserializer = new DeserializerBuilder()
        .WithNamingConvention(new PascalCaseNamingConvention())
        .Build();     

      var result = deserializer.Deserialize(new StringReader(yaml)); 

I get an object where the properties names are still in snake_case like 'is_active', etc.

I need to convert the properties names from snake_case in the YAML to PascalCase in the deserialized object.

How can I do this?

**Comment by aaubry** [comment]
You should specify `UnderscoredNamingConvention` instead of `PascalCaseNamingConvention`. That's the name that is used in YamlDotNet.

**Comment by mdmoura** [comment]
>> You should specify UnderscoredNamingConvention instead of PascalCaseNamingConvention. That's the name that is used in YamlDotNet.

Yes, I did that:

            var deserializer = new DeserializerBuilder()
                .WithNamingConvention(new UnderscoredNamingConvention())
                .Build();            

            var content2 = new StringReader(@"
              name: john
              postal_code: 1000
            ");                

            var result = deserializer.Deserialize(content2);    

And result has two `KeyValuePair` where the keys are: 
`name` and `postal_code` and I need to be `Name` and `PostalCode`.

Am I missing something?

**Comment by aaubry** [comment]
Yes, the naming convention is applied to object properties, not dictionary keys. There's currently no support to achieve that.
