### ISSUE TITLE
$ref OpenApi style implementation question

### ISSUE THREAD

**Issue by jrouaix** [aaubry/YamlDotNet#357]
Hello, i'm looking for a way to implement some reference based imports in yaml documents. 
The same way OpenApi/Swagger does it : https://swagger.io/docs/specification/using-ref/

Do you have an idea about how to do this using YamlDotNet ?

P.S. :
Otherwise I think i'll just use a regex replace some strings ... but it's not as fun !

**Comment by gwicksted** [comment]
You have to do some manual work AFAIK.

Have the following in your model class then after loading the main yaml file, parse the Ref string and load either a local reference to something like `#/definitions/Name` or an external url.  Then have a member named "Schema" of the expected type.  Then it'll either deserialize inline schemas or have a ref that you have to post-process.

```c#
        [YamlMember(Alias = "$ref")]
        public string Ref { get; set; }
```

**Comment by aaubry** [comment]
You could probably achieve this using a strategy similar to this - https://dotnetfiddle.net/Q2HCSY
This code allows to include other documents by using the `!include` tag:
```yaml
- one
- !include two.yml
- three
```

**Comment by jrouaix** [comment]
@aaubry Well I really need that to be compatible with swagger definitions $ref.
I first made a version replacing the json/yaml node in plain $ref location. Then reused it for a "merge" behavior. The code is not pretty ...
https://github.com/BeezUP/dotnet-codegen/blob/master/Dotnet.CodeGen/Schemas/SwaggerSchemaLoader.cs
