### ISSUE TITLE
.NET core NuGet package doesn't have full information

### ISSUE THREAD

**Issue by vplauzon** [aaubry/YamlDotNet#364]
Nothing Earth shattering issue here.

Simply put, https://www.nuget.org/packages/YamlDotNet/ has much more information than https://www.nuget.org/packages/YamlDotNet.NetCore/.

The former has a project site, source code, license info, etc.  .  The latter has minimalist information.

In order to find this site I did need to find the "Full .NET" package and see this site on it.

**Comment by aaubry** [comment]
The package that you mention, https://www.nuget.org/packages/YamlDotNet.NetCore/ has been published by someone else and does not belong to this project. There's not much we can do to prevent this.
