### ISSUE TITLE
Camel casing

### ISSUE THREAD

**Issue by vplauzon** [aaubry/YamlDotNet#365]
I've used a vanilla deserializer, i.e.

            var deserializer = new Deserializer();
            var obj = deserializer.Deserialize<MyType>(content);

I can deserialize a YAML file if the casing of properties match.  But as soon as I have a property in yaml 'article', it can't be mapped to the 'Article' property of the .NET object.

I saw that with a DeserializerBuilder I could override with WithNodeDeserializer maybe.

But before I try this I wanted to know if there was a simple way of accepting case-insensitive mapping?

Cheers

**Comment by vplauzon** [comment]
Ok...  I found what I was looking for in https://github.com/aaubry/YamlDotNet/issues/355.

Basically:

            var deserializer = new DeserializerBuilder()
                .WithNamingConvention(new CamelCaseNamingConvention())
                .Build();

does the job nicely.

**Comment by aaubry** [comment]
cool 👍
