### ISSUE TITLE
Serializing a class drived from Dictionary loose other properties

### ISSUE THREAD

**Issue by mkokabi** [aaubry/YamlDotNet#371]
Hi,
I have a class as:
`    public class X : Dictionary<string, string>
    {
        public int IntProp { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var x = new X() { { "a", "1"}, {"b", "2"}};
            x.IntProp = 123;
            var st = new SerializerBuilder().Build().Serialize(x);
            var y = new DeserializerBuilder().Build().Deserialize<X>(st);
            // st is 
            // a: 1
            // b: 2
            // and  y.IntProp is 0.
        }
    }`

**Comment by aaubry** [comment]
This is by design. Otherwise you would also see properties such as `Keys` or `Count` in the serialized YAML. If you need more control you may want to implement `IYamlConvertible` or register a custom `IYamlTypeConverter`.
