### ISSUE TITLE
This operation is only valid on generic types

### ISSUE THREAD

**Issue by bonesoul** [aaubry/YamlDotNet#373]
We can't deserialize based on interfaces i guess?

**Comment by bonesoul** [comment]
okay got my answer thanks; https://github.com/aaubry/YamlDotNet/blob/5ec2dd75704d6dced41c0d49ff5528f3797d1068/YamlDotNet.Test/Serialization/ObjectFactoryTests.cs#L44

**Comment by aaubry** [comment]
Ok, good!
