### ISSUE TITLE
TypeResolver obsolete for DeserializerBuilder

### ISSUE THREAD

**Issue by hakito** [aaubry/YamlDotNet#377]
It seems the TypeResolver is not used in a **de**serializer. So the method DeserializerBuilder.WithTypeResolver makes no sense.

**Comment by ikudjoi** [comment]
Is there a replacement of some kind available?

**Comment by aaubry** [comment]
The TypeResolver is used indirectly by the `ObjectNodeDeserializer` inside the deserializer.

**Comment by waclaw66** [comment]
Hello @aaubry,
is your answer still relevant?
Because `Resolve` method from `ITypeResolver` passed to `WithTypeResolver` is never called using  release 8.1.0. Therefore I have to use the approch from https://github.com/aaubry/YamlDotNet/issues/101#issuecomment-50288845 to detect value types.

> 
> 
> The TypeResolver is used indirectly by the `ObjectNodeDeserializer` inside the deserializer.

**Comment by aaubry** [comment]
You are correct. That interface will only be used when reading the value of a property, which doesn't occur frequently during deserialization. It could still be used in to read read-only properties whose value is to be udated, for example, when deserializing a sequence into an existing collection.
