### ISSUE TITLE
YamlMappingNode missing newlines for certain parts of multiline string

### ISSUE THREAD

**Issue by paulirwin** [aaubry/YamlDotNet#380]
I'm parsing a YAML file using `YamlStream`. 

Here's the anonymized relevant section my input file:
```YAML
queries:
    MyQuery:
        query: >
            SELECT  a,
                    b,
                    c
            FROM Foo
            INNER JOIN Bar ON Foo.a = Bar.z
            WHERE Foo.a = 123
```

Approximate code equivalent to access string value:
```C#
var yaml = new YamlStream();
yaml.Load(stream);
var root = (YamlMappingNode)yaml.Documents[0].RootNode;
var queries = (YamlMappingNode)root.Children["queries"];
var myQuery = (YamlMappingNode)queries.Children["MyQuery"];
var query = myQuery.Children["query"].ToString()
```

Expected value:
```
SELECT  a,
        b,
        c
FROM Foo 
INNER JOIN Bar ON Foo.a = Bar.z 
WHERE Foo.a = 123
```

Actual value:
```
SELECT  a,
        b,
        c
FROM Foo INNER JOIN Bar ON Foo.a = Bar.z WHERE Foo.a = 123
```

For some reason, it preserves the newlines if the indention level changes, but it loses the newlines for lines at the same indention level. Please let me know if I'm using the API wrong, or if this is a bug.

**Comment by aaubry** [comment]
This happens because of the folding indicator (`>`) that you are using. I need to dig a bit more to see if the behavior that you are observing is 100% correct, but in any case you probably want to use `|` instead of `>`.

**Comment by paulirwin** [comment]
I confirmed that using `|` solved the problem, thanks! But I'll leave this open if you want to confirm the `>` behavior still.

**Comment by aaubry** [comment]
The behaviour is consistent with the spec and other YAML parsers.
