### ISSUE TITLE
Consider merging YamlDotNet.Signed and YamlDotNet packages

### ISSUE THREAD

**Issue by aaron-meyers** [aaubry/YamlDotNet#390]
I'd like to propose that the YamlDotNet.Signed package be deprecated and that the YamlDotNet package include strong-named assemblies, starting with the next major version (e.g. 6.0).

We've found YamlDotNet to be very useful (on Microsoft Power BI team) as have many others (over 3M downloads on Nuget as of writing). It is clear from the Nuget download numbers that there is interest in the signed package (fewer downloads than the unsigned one but not by that much, 1.9M vs. 1.1M currently). By maintaining separate Signed and unsigned packages there is a real risk that other libraries will take a dependency on one or the other and type conflicts will then occur in an application when I try to reference one library that depends on YamlDotNet.Signed and another library that references YamlDotNet (unsigned).

Microsoft's published guidelines on strong-naming are that OSS libraries use strong names and do not publish separate strong-named and unsigned packages.
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

**Comment by aaron-meyers** [comment]
This would of course be a breaking change which is why it would only make sense to do it in a major version release.

**Comment by aaubry** [comment]
I've been reading about this topic, including the link that you provided. One of the main obstacles regarding signing the assemblies, strict assembly loading, seems to have been removed in modern versions of .NET. Therefore it seems that merging both packages would do little harm.

I still don't see what is the point of signing the assembly if the key is public though, which is the case for YamlDotNet, and seems to be the official recommendation. What benefit does this provide ?

**Comment by aaron-meyers** [comment]
A couple things: first of all, the guidance for many years has been that strong names are not a security feature, because it was shown a long time ago that they can be compromised (digital signatures such as Authenticode are instead useful for validating that an assembly hasn't actually been tampered with, which we use in our shipping assemblies). They were originally considered a security feature in conjunction with partial trust scenarios but those were deprecated a long time ago since it was found impossible to adequately sandbox .NET code (I have a bit of history with this as a Microsoft product I worked on was one of the first to rely partial trust in a shipping product and we had to do major rework in a later version to stop depending on it). Strong names are now considered to be only useful for assembly identity and not security. More info here: https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies

Since the strong name isn't a security feature, there's no problem with checking in the key, because it isn't intended to assert that the code came from anywhere in particular.

From the article I originally linked on the benefits to strong-naming an assembly:

> One important aspect of strong naming is that it's viral: a strong named assembly can only reference other strong named assemblies. If your library isn't strong named, then you have excluded developers who are building an application or library that needs strong naming from using it.
> 
> The benefits of strong naming are:
> 1. The assembly can be referenced and used by other strong-named assemblies.
> 2. The assembly can be stored in the Global Assembly Cache (GAC).
> 3. The assembly can be loaded side by side with other versions of the assembly. Side-by-side assembly loading is commonly required by applications with plug-in architectures.
> 

For my scenario, #1 is the only reason to need a strong-named assembly, which is essentially a backwards-compatibility argument. We have a massive codebase with hundreds of assemblies and the standard practice is still to strong-name all of our assemblies, if only because the cost of changing this is quite high. So I still need a strong-named assembly so it can be referenced by all of our assemblies which are strong-named.

#2 isn't needed for most applications (or even advised), but #3 could be interesting in some cases where you have an application that supports plug-ins and I want to use two plug-ins that depend on different (incompatible) versions of YamlDotNet (e.g. v2 and v5). This is a very real possibility with something as ubiquitous as Newtonsoft.Json although probably less likely with YamlDotNet (but maybe somday? ;-))

So besides the compatibility argument for applications that strong-name their own assemblies, the benefit of strong naming and not having separate strong-named/not-strong-named packages basically comes down to scenarios where there are multiple components that depend on YamlDotNet that I want to use in an application. This may not have happened to anyone using YamlDotNet today but could perhaps happen in the future.

**Comment by aaubry** [comment]
Thanks for the feedback. After getting some additional advice, I have decided to merge the packages, as you suggested. I'll do that asap, hopefully in the next few hours.

**Comment by aaron-meyers** [comment]
Thanks! It looks like you can unlist a package from nuget.org (which doesn't break existing dependencies but removes it from search results), so when you're ready you should be able to unlist the YamlDotNet.Signed package to move people to the unified YamlDotNet package.
https://docs.microsoft.com/en-us/nuget/policies/deleting-packages

**Comment by aaubry** [comment]
I've released [version 6.0.0](https://github.com/aaubry/YamlDotNet/releases/tag/v6.0.0) that merges the packages. Let's hope that this won't cause problems to users!

**Comment by aaubry** [comment]
The YamlDotNet.Signed packages were all unlisted except version 6.0.0, which is an empty package that depends on YamlDotNet 6.0.0, to help with the transition.

**Comment by aaron-meyers** [comment]
Great! I think you'll want to update the README.md Installing section (https://github.com/aaubry/YamlDotNet#installing) which still mentions the Signed package.

**Comment by aaubry** [comment]
Done. Thanks.
