### ISSUE TITLE
Deserialize crashes with serialised System.Data.dataSet

### ISSUE THREAD

**Issue by brewmanz** [aaubry/YamlDotNet#392]
YamlDotNet.Serialization.Deserializer.Deserialize throws YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 2, Col: 1, Idx: 5): Exception during deserialization ---> System.Runtime.Serialization.SerializationException: Property 'DefaultViewManager' not found on type 'System.Data.DataSet'.

version = 6.0.0.0

Sample code (BTW- your 'Insert Code' loses CR/LF - maybe someone could fix that?):

         Dim str = "", ser = New YamlDotNet.Serialization.Serializer(), deser = New YamlDotNet.Serialization.Deserializer
        Dim ds = New DataSet
        Assert.AreEqual("NewDataSet", ds.DataSetName)
        ds.DataSetName = "MyDS"
        Dim dt = New DataTable
        dt.TableName = "MyDT"
        Dim dc = New DataColumn
        dc.ColumnName = "MyDC"
        dc.DataType = GetType(String)
        dt.Columns.Add(dc)
        ds.Tables.Add(dt)
        Dim dr = dt.NewRow
        dr.ItemArray = New Object() {"MyValue"}
        dt.Rows.Add(dr)
        Assert.AreEqual(1, ds.Tables.Count)
        Assert.AreEqual("MyDT", ds.Tables(0).TableName)
        Assert.AreEqual(1, ds.Tables(0).Columns.Count)
        Assert.AreEqual("MyDC", ds.Tables(0).Columns(0).ColumnName)
        Assert.AreEqual(1, ds.Tables(0).Rows.Count)
        Assert.AreEqual("MyValue", ds.Tables(0).Rows(0)(ds.Tables(0).Columns(0)))
        Assert.AreEqual("MyDS", ds.DataSetName)
        str = ser.Serialize(ds)
        ds = deser.Deserialize(Of DataSet)(str) 
        Assert.AreEqual(1, ds.Tables.Count)
        Assert.AreEqual("MyDT", ds.Tables(0).TableName)
        Assert.AreEqual(1, ds.Tables(0).Columns.Count)
        Assert.AreEqual("MyDC", ds.Tables(0).Columns(0).ColumnName)
        Assert.AreEqual(1, ds.Tables(0).Rows.Count)
        Assert.AreEqual("MyValue", ds.Tables(0).Rows(0)(ds.Tables(0).Columns(0)))
        Assert.AreEqual("MyDS", ds.DataSetName)

**Comment by aaubry** [comment]
By default the serializer emits all properties that are readable. The `DefaultViewManager` property is read-only, so the deserializer cannot assign it. You may try calling `EnsureRoundtrip()` on the `SerializerBuidler` to instruct it to ignore read-only properties, but I don't know if the result will be useful.
To serialize a type as complex as a DataTable, you may need a custom `IYamlTypeConverter`.
