### ISSUE TITLE
How to receive deserialization callbacks for "sanitizing" the object?

### ISSUE THREAD

**Issue by tfgstudios** [aaubry/YamlDotNet#397]
Hey. Great library!
I don't find any info about how to just sanitize the object after being deserialized by the internal deserializer. Is this possible?
I saw IYamlConvertible, but this requires me to manually serialize the properties. I'll do this, if needed, but I still can't figure it out, as there's no example use-case under samples.
Thanks

**Comment by aaubry** [comment]
You can use the same strategy as [this sample](https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet.Samples/ValidatingDuringDeserialization.cs).
