### ISSUE TITLE
How to handle omitted key?

### ISSUE THREAD

**Issue by am11** [aaubry/YamlDotNet#402]
This is in relation to the PR https://github.com/aaubry/YamlDotNet/pull/401.

I started tackling the more comprehensive test: https://github.com/yaml/yaml-test-suite/blob/data/4ABK/test.event. It was failing line 6, 8 and 11 as below:

```diff
- master
+ PR

- =VAL ://foo.com
+ =VAL :http://foo.com

- =VAL :omitted value:
+ =VAL :omitted value

.. and line 11 throws on both
```

PR fixes first two issues. However for the third one,  `=VAL :omitted key`, scanner is classifying it as a `Value` token, which we ignore while generating events in parser and throw exception:

https://github.com/aaubry/YamlDotNet/blob/cc70e04bc88466a1432c9fbd5869c7efe49fbfad/YamlDotNet/Core/Parser.cs#L559-L562

I think there are at least two approaches:

* consider adding `string` value in `Value` token and case in parser `if(token is Value value) { /* generate scalar event here */}`
* update the scanner to classify omitted key as a (special) case of scalar

Which one would make more sense?

**Comment by aaubry** [comment]
I'm not sure about this one. I didn't know that the key could be omitted. Couldn't this be handled as if the key was `null` ? This seems consistent with [this part of the specification](https://yaml.org/spec/1.2/spec.html#id2786563):
> YAML allows the node content to be omitted in many cases. Nodes with empty content are interpreted as if they were plain scalars with an empty value. Such nodes are commonly resolved to a “null” value.

**Comment by am11** [comment]
Thanks, I was able to satisfy some cases including `4ABK`, by adjusting the conditions such that blank key is scanned as a `Scalar`.

However spec test `6M2F` expects:

```yaml
&a a: &b b
: *a
```

to produce:

```json
{
  "a": "b",
  "": "a"
}
```

To satisfy this case, we need to produce scalar with empty value for key on line 2 as well, but so far I could not figure out the distinguishable characteristics for this one to prevent scanner entering `FetchValue`.

I will push the existing changes (after PR-403 is in), as it is an improvement overall and does not regress.
This issue can track the said spec: https://github.com/yaml/yaml-test-suite/blob/data/6M2F

**Comment by aaubry** [comment]
Ok, this sounds like a good plan.

**Comment by am11** [comment]
With two tweaks in scanner together with few adjustments in parser, `6M2F` is also green. :)

Had to took a detour as there was a regression found in `DocumentEnd` handling since the spec runner was added. PR-404 hardens the executor so the false-positive cases (tests that should cause parsing error according to spec but parser does not throw) are properly whitelisted; PR also satisfies three specs related to `DocumentEnd`. 

Omitted key fix branch is currently based on top of PR-404 one. Once that goes in, I will rebase and create a new PR.
