### ISSUE TITLE
Why use YamlScalarNode for keys?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [aaubry/YamlDotNet#423]
How come the keys in `YamlMappingNode` are wrapped in `YamlScalarNode`:s? Is it to support numeric keys? If so, I can't find that functionality (admittedly after only a cursory look)

**Comment by aaubry** [comment]
Keys in mappings can be arbitrary nodes, as [described in the YAML specification](https://yaml.org/spec/1.2/spec.html#key:%20value%20pair//):
> (...) In particular, keys may be arbitrary nodes (...)
So the key is not wrapped in `YamlScalarNode`, it hust happens to be a scalar, but could as well be a `YamlMappingNode` or `YamlSequenceNode`...

**Comment by bjorn-ali-goransson** [comment]
Oh, my ... Thanks.
