### ISSUE TITLE
How do I serialize PSObjects?

### ISSUE THREAD

**Issue by felixfbecker** [aaubry/YamlDotNet#424]
[`PSObject`s](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.psobject?view=pscore-6.2.0) are the dynamic objects used by PowerShell. They implement `IDynamicMetaObjectProvider` and `ISerializable`.

However, when I try to serialize them with `Serializer.serialize()`, it fails with `Exception calling "Serialize" with "1" argument(s): "Too much recursion when traversing the object graph"`.

I tried writing a custom `ITypeInspector` but it wasn't clear to me how I would make it only apply to `PSObject`s and let other classes be handled like the default behaviour.

Is there any guide how to serialize a `PSObject` / `ISerializable` / `IDynamicMetaObjectProvider` with YamlDotNet?

**Comment by aaubry** [comment]
I am not familiar with `PSObject` and `IDynamicMetaObjectProvider`, but you are correct that you should implement `ITypeInspector` to support them.
The `ITypeInspector` interface should be implemented as a decorator, so that it handles what it can (perhaps `IDynamicMetaObjectProvider` in this case) and delegates to the next inspector for the remaining cases. Something like this:

```c#
class DynamicMetaObjectProviderTypeInspector : ITypeInspector
{
    private readonly ITypeInspector innerTypeDescriptor;

    public DynamicMetaObjectProviderTypeInspector (ITypeInspector innerTypeDescriptor)
    {
        this.innerTypeDescriptor = innerTypeDescriptor;
    }

    public IEnumerable<IPropertyDescriptor> GetProperties(Type type, object container)
    {
        if (typeof(IDynamicMetaObjectProvider).IsAssignableFrom(type))
        {
            // The interface should probably be clarified,
            // but in practice this is called during serialization, with container != null
            var dynamicObject = (IDynamicMetaObjectProvider)container;
            // TODO: Use dynamicObject to return a list of IPropertyDescriptor (should be a new class)
        }
        return innerTypeDescriptor.GetProperties(type, container);
    }

    public IPropertyDescriptor GetProperty(Type type, object container, string name, bool ignoreUnmatched)
    {
        if (typeof(IDynamicMetaObjectProvider).IsAssignableFrom(type))
        {
            // As discussed above, the interface should probably be clarified,
            // but in practice this is called during deserialization, with container == null
            // Since the object is dynamic, we should probably always
            // return a IPropertyDescriptor for any property name.
            // TODO: return an implementation of IPropertyDescriptor (should be a new class)
        }
        return innerTypeDescriptor.GetProperty(type, container, name, ignoreUnmatched);
    }
}
```

You would then register the type inspector like this:

```c#
var serializer = new SerializerBuilder()
    .WithTypeInspector(inner => new DynamicMetaObjectProviderTypeInspector (inner))
    .Build();
```

I don't known exactly how `IDynamicMetaObjectProvider` should be used, but I guess that you should be able to figure that out.

Let me know if this is useful or if you have any difficulties implementing this, I'm interested in knowing how it goes. If you want, we can add your implementation to YamlDotNet so that other can benefit from it, but that's up to you.

**Comment by felixfbecker** [comment]
Ah, that makes sense! I looked at `ReadablePropertiesTypeInspector` to see how to do it. The only thing I couldn't figure out is that it gets a `TypeResolver` and uses that to resolve a type override. I left that part out since I don't know how to get a reference to the `TypeResolver`. I also ignored attributes and always return the dynamic type for the static type.

The last issue I noticed, potentially related, was that the `CamelCaseNamingConvention` was not being applied. Everything was PascalCase like in the input object.

```csharp
serializer = new SerializerBuilder()
                .WithTypeInspector(inspector => new PSObjectTypeInspector(inspector))
                .WithNamingConvention(new CamelCaseNamingConvention())
                .Build();
```

**Comment by aaubry** [comment]
That's because the naming conventions are applied by a different `ITypeInspector`. You can register your own after that one and it should work:

```c#
serializer = new SerializerBuilder()
        .WithTypeInspector(inspector => new PSObjectTypeInspector(inspector))
        .WithNamingConvention(new CamelCaseNamingConvention(), s => s.After<NamingConventionTypeInspector>())
        .Build();
```

I'm typing this from memory so there might be a syntax error, but it should be mostly correct.

**Comment by felixfbecker** [comment]
Yeah `WithNamingConvention()` doesn't take a second parameter :/

**Comment by aaubry** [comment]
That's what happens when I try to reply on my phone :disappointed:
I've updated the comment. The parameter belongs to the `WithTypeInspector` method.

**Comment by aaubry** [comment]
I'm going to close this issue. If you have further questions, please reopen it. Thanks
