### ISSUE TITLE
Sample LoadingAYamlStream runtime type cast exception

### ISSUE THREAD

**Issue by LeiYangGH** [aaubry/YamlDotNet#425]
I installed YamlDotNet 6.0.0.0 via nuget into my .net 4.5 project. and tried the sample, but exception thrown at runtime:

```
            var mapping =
                (YamlMappingNode)yaml.Documents[0].RootNode;
```

> System.InvalidCastException
>   HResult=0x80004002
>   Message=Unable to cast “YamlDotNet.RepresentationModel.YamlScalarNode”to “YamlDotNet.RepresentationModel.YamlMappingNode”。
>   Source=VoiceLangsOperator

I translated some words from original languages but the meanning should be same.

**Comment by aaubry** [comment]
That's weird. The sample [runs correctly in CI](https://ci.appveyor.com/project/aaubry/yamldotnet/build/tests). Can you describe in more detail what you did ?

**Comment by LeiYangGH** [comment]
Sorry, I made a mistake, passing a filename to `Document`. The issue should be closed now.
