### ISSUE TITLE
YamlDotNet does not write accurately equal to yaml being loaded

### ISSUE THREAD

**Issue by kokizzu** [aaubry/YamlDotNet#426]
Example input file any scene from Unity3D. Example code:
```
var input = new StringReader(File.ReadAllText("Scene1.unity"));
var yaml = new YamlStream();
yaml.Load(input);
var tw = File.CreateText(sc.path + ".yaml");
yaml.Save(tw);
```
Verification shell command:
`diff Scene1.unity Scene1.unity.yaml` 
^ got totally different result

![image](https://user-images.githubusercontent.com/1061610/62908097-752fe180-bda0-11e9-8314-4e85001fd9ae.png)

**Comment by aaubry** [comment]
Please try using the `Save()` overload that takes a boolean:

```
var input = new StringReader(File.ReadAllText("Scene1.unity"));
var yaml = new YamlStream();
yaml.Load(input);
var tw = File.CreateText(sc.path + ".yaml");
yaml.Save(tw, false);
```

The default behaviour is to assign anchors to nodes, but that feature has some issues.

**Comment by aaubry** [comment]
I will close this issue as there has been no feedback. Feel free to reopen it if necessary.

**Comment by lx1988** [comment]
This problem still exists，
I already use yaml.Save(tw, false);
but The format is still wrong

**Comment by EdwardCooke** [comment]
Can you paste raw yaml and a small reproduction of code for the problem? That’ll help immensely. But the difference looks like anchors.
