### ISSUE TITLE
How to prevent Serializer to change value types : "2" => 2

### ISSUE THREAD

**Issue by jrouaix** [aaubry/YamlDotNet#428]
Hello, 

I have hard time trying to change json swagger to yaml

![image](https://user-images.githubusercontent.com/2705498/63435928-10bbf480-c428-11e9-838a-6bcd4c202258.png)

Please what is the correct SerializerBuilder magic trick to disable yaml serializer changing types behavior ?

**Comment by jrouaix** [comment]
The problem here is the swagger property value should be the string "2.0" and not the number 2.0

**Comment by aaubry** [comment]
There is no semantic difference in YAML between `2.0` and `"2.0"`. Both are alternative representations of the same scalar. If you really want quotes, you can annotate your property with YamlMemberAttribute and set the ScalarStyle property.

**Comment by aaubry** [comment]
To further clarify, types in YAML are indicated using tags. Having quotes has no influence on the type.

**Comment by jrouaix** [comment]
Well I understand that it doesn't matter for YAML, but it matters for the swagger editor :

![image](https://user-images.githubusercontent.com/2705498/63502006-e83a0600-c4cc-11e9-8152-952660d19c4f.png)

Also I cannot make a propertly typed .net object with YamlMemberAttribute to handle this as my original json is made from dynamic transformations in the jObject itself.

Do you see an entrypoint in your library where I can plug the behavior "if it's a string put quotes"

**Comment by aaubry** [comment]
You should be able to achieve what you want by registering an IEventEmitter that overrides the style of scalars. I can't provide the exact code because I am away from my computer, but it would be similar to the example from the documentation:

https://github.com/aaubry/YamlDotNet/wiki/Serialization.Serializer#witheventemitter

Override the method for scalars and if needed check the event info to see if the value was a string. Let me know if this helps.

**Comment by jrouaix** [comment]
Ok, this did the job, thank you! : 

``` csharp
class RespectTypesEventEmitter : ChainedEventEmitter
{
    public RespectTypesEventEmitter(IEventEmitter nextEmitter) : base(nextEmitter) { }

    public override void Emit(ScalarEventInfo eventInfo, IEmitter emitter)
    {
        if(eventInfo.Source.Type == typeof(string))
        {
            eventInfo.Style = ScalarStyle.DoubleQuoted;
        }
        base.Emit(eventInfo, emitter);
    }
}
```
Now everything is "typeish_correct" (event if it should not matter in yaml ok)

![image](https://user-images.githubusercontent.com/2705498/63763688-8101c480-c8c5-11e9-8ce1-52b9030b9100.png)

Do you see a way I can have the property names non quotes, and only the values quoted ? I don't see enough info in `ScalarEventInfo` to tackle this problem.

But for now, it's ok, swagger does not complain anymore.

**Comment by aaubry** [comment]
The only thing that comes to my mind would be to also override the `Emit()` methods that take `MappingStartEventInfo`, `MappingEndEventInfo`, `SequenceStartEventInfo` and `SequenceEndEventInfo` and track whether the current scalar is a value or a key.

Here is a possible implementation:

```c#
class ForceQuotedStringValuesEventEmitter : ChainedEventEmitter
{
    private class EmitterState
    {
        private int valuePeriod;
        private int currentIndex;
        
        public EmitterState(int valuePeriod)
        {
            this.valuePeriod = valuePeriod;
        }
        
        public bool VisitNext()
        {
            ++currentIndex;
            return (currentIndex % valuePeriod) == 0;
        }
    }
    
    private readonly Stack<EmitterState> state = new Stack<EmitterState>();
    
    public ForceQuotedStringValuesEventEmitter(IEventEmitter nextEmitter)
        : base(nextEmitter)
    {
        this.state.Push(new EmitterState(1));
    }

    public override void Emit(ScalarEventInfo eventInfo, IEmitter emitter)
    {
        if (this.state.Peek().VisitNext())
        {
            if(eventInfo.Source.Type == typeof(string))
            {
                eventInfo.Style = ScalarStyle.DoubleQuoted;
            }
        }
            
        base.Emit(eventInfo, emitter);
    }

    public override void Emit(MappingStartEventInfo eventInfo, IEmitter emitter)
    {
        this.state.Peek().VisitNext();
        this.state.Push(new EmitterState(2));
        base.Emit(eventInfo, emitter);
    }

    public override void Emit(MappingEndEventInfo eventInfo, IEmitter emitter)
    {
        this.state.Pop();
        base.Emit(eventInfo, emitter);
    }

    public override void Emit(SequenceStartEventInfo eventInfo, IEmitter emitter)
    {
        this.state.Peek().VisitNext();
        this.state.Push(new EmitterState(1));
        base.Emit(eventInfo, emitter);
    }

    public override void Emit(SequenceEndEventInfo eventInfo, IEmitter emitter)
    {
        this.state.Pop();
        base.Emit(eventInfo, emitter);
    }
}
```
You can see it in action here: https://dotnetfiddle.net/lTZ8rm

**Comment by jrouaix** [comment]
thanks @aaubry ! a dream come true !
