### ISSUE TITLE
Different serialization output: three dots in the end of serialized yaml

### ISSUE THREAD

**Issue by joostas** [aaubry/YamlDotNet#436]
**Serialize simple value to yaml:**
```cs
var serializer = new Serializer();
var output = serializer.Serialize(42);
```
output: `"42\r\n...\r\n"` (three dots at the end)

**Serialize array value to yaml**:
```cs
var serializer = new Serializer();
var output = serializer.Serialize(new int[]{42});
```
output: `"- 42\r\n"` (no dots at the end)

**Question:** Why same serialization setup produces different output in the end of document (`...`)?
**Question:** Is it possible to "hide" three dots when converting simple value?

---
Versions tested:
* 6.1.2
* 7.0.0
* 8.0.0-emit-default-values0565

**Comment by aaubry** [comment]
This is unexpected, and probably a bug. I'll try look into it tommorow and get back to you.

**Comment by lampenlampen** [comment]
I'm using `YamlStream` and also get the three dots at the end of the document.

``` c#
var yamlStream = new YamlStream(new YamlDocument(
    new YamlMappingNode(
        new YamlScalarNode("test"), new YamlScalarNode("42"))));

var stringWriter = new StringWriter();
yamlStream.Save(stringWriter);

// stringwriter: "test: 42\r\n...\r\n"
```

Is this indented? Is it possible to disable the emitting of the three dots?

Thanks

YamlDotNet version: 8.0.0

**Comment by Fonata** [comment]
The 3 dots `...` are a valid, optional part of the formal YAML file format and indicate the end of a document.

**Comment by geferon** [comment]
It's been a while, and saving with a YamlStream still adds the three dots at the end of the file, is there any way to disable it?
It's been more than a year since the last reply, dunno if @lampenlampen is still active but, have you found a way to disable them?

**Comment by queil** [comment]
@geferon and any other person that land here with the 3 dots. Try serialization instead of saving the stream. https://stackoverflow.com/questions/50878627/yamdocument-to-text-representation-end-with-3-dots
