### ISSUE TITLE
InvalidCastException when indexing YamlNode

### ISSUE THREAD

**Issue by andrewsav-datacom** [aaubry/YamlDotNet#437]
In this code:

```csharp
    string Document = @"---
            receipt:    Oz-Ware Purchase Invoice";
	var input = new StringReader(Document);
	var yaml = new YamlStream();
	yaml.Load(input);
	object bz1 = yaml.Documents[0].RootNode[0];
```

The last line produces exception:

```text
Unable to cast object of type 'YamlDotNet.RepresentationModel.YamlMappingNode' to type 'YamlDotNet.RepresentationModel.YamlSequenceNode'.


at YamlDotNet.RepresentationModel.YamlNode.get_Item(Int32 index)
```
It is quite unexpected that a simple indexing operation throws an `InvalidCastException`  exception.

This is in 7.0.0 (latest) Nuget package,

**Comment by aaubry** [comment]
This is because that indexer is meant to be used for sequence nodes. Since your root element is a mapping node, using that indexer doesn't make sense.
What would you expect this to do instead of throwing an exception ?

**Comment by AndrewSav** [comment]
At the very minimum I would expect exception to tell me that.

To me it feels like a bizzare design choice for a class. A class (`YamlMappingNode`) supports an indexer, but the indexer does not make sense for the class? Why does it impement it at all then?

I'm not criticizing, I'm just preplexed, to me this is very non-obvious.

**Comment by aaubry** [comment]
Well, the exception is telling you that, kind of 😛. But of course there's room for improvement, and a clearer error message would be helpful.

Regarding the design choice, I agree that it may be surprising, but honestly I don't know how it could be improved. This indexer is part of a family of members that aim to make it simpler to navigate into a YAML document when its structure is known. Before I added those members, to achieve the same, a lot of casts were needed:

```c#
((YamlMappingNode)((YamlSequenceNode)yaml.Documents[0].RootNode)[0])["someKey"];
```

instead of:

```c#
yaml.Documents[0].RootNode[0]["someKey"];
```

Of course you have to know the structure of the document, otherwise the code will throw exceptions, but it would be the same with casts.

I'm open to suggestions on how this could be improved, of course. If you have ideas, please share them. Thanks!

**Comment by AndrewSav** [comment]
@aaubry Do you happen to know how Json .net  (newtonsoft) solves this problem? They must have the same problem, don't thay? I would not be surprised if they are content with the casts, simply because it's easier to understand for a programmer.

**Comment by aaubry** [comment]
It seems that Json.NET has a simmilar approach: https://www.newtonsoft.com/json/help/html/LINQtoJSON.htm

**Comment by aaubry** [comment]
I have changed the code so that more descriptive exceptions are thrown. I don't think that there is much more that can be done to improve this. I think that it is better to have this than be forced to cast, as these indexers are most useful for exploratory purposes.

**Comment by andrewsav-datacom** [comment]
Yes. I just had a look.

In Json.Net terms Node will be Jtoken, Sequence will be JArray, and mapping will be JObject.

So here is functionally equivalent code for Json:

```
	string jsonString = @"{""a"":""b""}";
	JToken tokenThatObject = JToken.Parse(jsonString);
	var val = tokenThatObject[0];
```

Executing this will result in:

```
ArgumentException: Accessed JObject values with invalid key value: 0. Object property name expected
```

You have a similar one now:

```
ArgumentException: Accessed 'Mapping' with an invalid index: 0. Only Sequences can be indexed by number.
```

I think this is adequate.

**Comment by andrewsav-datacom** [comment]
Thank you for taking time to look into this.

**Comment by aaubry** [comment]
Thanks for the feedback!
