### ISSUE TITLE
Allow deserialize for classes with internal visibility

### ISSUE THREAD

**Issue by ravertid** [aaubry/YamlDotNet#441]
When using the `YamlDotNet.Serialization.IDeserializer` interface, we are not able to pass in types that have an access modifier of 'internal'. The typical way of testing an internal class is by adding the following assembly directive in the containing project's AssemblyInfo.cs.

`[assembly: InternalsVisibleTo("Testing.Namespace")]`

If we had the following AssemblyInfo.cs for a project that contained a class named SampleClass, then we are able to use the class within the test methods in the given 'Testing.Namespace' namespace, but we are note able to deserialize it using the YamlDotNet deserializer. Below is an example scenario.

Given this class
```
internal class SampleClass
{
    public string SampleClassProperty { get; set; }
}
```
In a project that contains this AssemblyInfo.cs
```
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Testing.Namespace")]
```
And an attribute SampleYamlAttribute which uses IDeserializer

`Deserializer.Deserialize<SampleClass>(SampleYamlFile, typeof(SampleClass))`

This works
```
namespace Testing.Namespace
{
    [TestMethod]
    [SampleYamlAttribute(nameof(Tests))]
    public void SampleTest()
    {
        var sample = new SampleClass();
        Assert.IsNotNull(sample);
    }
}
```

However, this does not

```
namespace Testing.Namespace
{
    [TestMethod]
    [SampleYamlAttribute(nameof(Tests))]
    public void SampleTest(SampleClass sample)
    {
        (test goes here...)
    }
}
```

The error given is [Error CS0051](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0051).

**Comment by aaubry** [comment]
This has nothing to do with YamlDotNet, it is a feature of the C# language. The compiler is giving an error because exposing the SampleClass type as a parameter of a public method is inconsistent with that class' visibility. You need to make either the SampleTest method or it's containing class internal.
