### ISSUE TITLE
Aliasing attributes

### ISSUE THREAD

**Issue by Vraiment** [aaubry/YamlDotNet#442]
Hi

I have a project where the classes in the data model already has some custom attributes describing how they should be serialized in binary:

```C#
class MyClass
{
    [SerializableProperty(Order = 1)
    public int Int { get; set; }

    // ...
}
```

I'd like to reuse this properties instead of using `[YamlMember]` everywhere and which would imply duplicating the information in both attributes. In a way to provide my own "*alias*" to `YamlMemberAttribute`.

The two chunks of information I'm interested "*aliasing*": the `YamlMemberAttribute.Order` property and the `YamlMemberAttribute.Alias` property, ex:

```C#
[SerializableProperty(Order = 1, Alias = "something_else")]
public int Int { get; set; }
```

**Comment by aaubry** [comment]
This should be relatively easy to accomplish. You will need to implement the `ITypeInspector` interface to add that support. The implementation could be similar to [this one](https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet/Serialization/YamlAttributesTypeInspector.cs).

Then you register your implementation like this:
```c#
var serializer = new SerializerBuilder()
    .WithTypeInspector(
        inner => new MyTypeInspector(inner),
        s => s.InsteadOf<YamlAttributesTypeInspector>())
    .Build();
```
This will completely replace the `YamlMember` and `YamlIgnore` attributes handling with your own. If you prefer to keep that functionality, use the following registration instead:
```c#
var serializer = new SerializerBuilder()
    .WithTypeInspector(
        inner => new MyTypeInspector(inner),
        s => s.Before<YamlAttributesTypeInspector>())
    .Build();
```

Let me know if you encounter any issue.

**Comment by Vraiment** [comment]
Thanks, it worked!
