### ISSUE TITLE
Emit comments

### ISSUE THREAD

**Issue by bjornbouetsmith** [aaubry/YamlDotNet#444]
Hi,

I am trying to use this library to control configuration for a program I am making - I have made it possible to get the program to dump a default configuration to std out.

Is it some how possible to get YamlDotNet to emit yaml comments for each property/type it emits?

Ideally it would be built into YamlDotNet via an attribute, like the below code - and a formatter that controls whether or not to emit comments.

i.e.
````c#
  var serializer = new SerializerBuilder()
.WithNamingConvention(PascalCaseNamingConvention.Instance)
.WithComments().Build();

public class MyConfig
{
   [YamlComment("Log Configuration blah blah")]
    public LogConfiguration Logging {get;set;}
}


public class LogConfiguration
{
     [YamlComment("Directory where all log files will be saved")]
     public string LogDirectory {get;set;}="/var/log";
}
````
Which would get serialized like:
```
#Log Configuration blah blah
Logging:
    #Directory where all log files will be saved
    LogDirectory: /var/log
```
I have looked at the code and it seems straightforward to implement this inside YamlDotNet, but I am not sure how to implment it outside, and it would be a nice built in feature.

It would make it really easy for people to create self documenting configuration, so they don't have to manually update descriptions of how to configure something, they could just add a [YamlComment] if they wanted to emit a comment with a property to describe what it controls and how values will be interpreted.

**Comment by aaubry** [comment]
Please see #152, which contains the following sample: https://dotnetfiddle.net/8M6iIE
The sample achieves something very similar to what you are looking for. Please reopen the issue if you need further assistance.
