### ISSUE TITLE
Handling of integer values with leading zeros

### ISSUE THREAD

**Issue by neil-hudson-SQC** [aaubry/YamlDotNet#447]
I encountered situation this morning where the parser was reporting "Additional non-parsable characters are at the end of the string" on certain lines with numeric values on them that were being parsed into an integer field.  My analysis went from:
- Can't see any extra characters to on the line '    RetailJStoreId: 0008'
- It must be treating the character sequence '0008' as a backspace to
- Can you turn off this treatment to
- Workaround change '0008' to '8'
- There are a number of other numbers that also behave in the same way and will need leading zeros removing.

So the issue and the workaround is understood but the question is - Is there a way to prevent this treatment of leading zeros?  From a 'human readable' and data compatibility perspective having numbers with leading zeros is a 'common' if not even 'good' practice. Could we make the type a string and handle the conversion ourselves or would that suffer the same conversion? Even if that would work the extra processing outside the parser does not seem optimal.  Is there a parser option, or can one be added, to avoid leading zeros causing this issue?

**Comment by aaubry** [comment]
This is because integers staring with zero are interpreted as octal, and 8 is not a valid octal number. This comes from the YAML 1.1 spec. Currently there's no easy way to change this behavior.

**Comment by aaubry** [comment]
From your code this seems to be an identifier rather than a number, so you should probably treat it as a string instead, which would avoid the problem.

**Comment by neil-hudson-SQC** [comment]
Ok. Thanks for the rapid feedback.  Yes, you are correct, the field is an identifier and thanks for the clarity that a string based solution would work.  I did not realise that there was an implicit interpretation of numbers starting with zero as Octal, that seems counter intuitive given that Yaml is meant to be "human readable" and that is not how humans think.  Any way I have the option now and will close the issue. Thanks again.

**Comment by aaubry** [comment]
I'm glad that you are able to work around your problem. Actually, the 1.2 spec no longer suggests that format for octal numbers. When the ongoing work on schemas is complete, it should be easier to control this behavior.
