### ISSUE TITLE
Serializer emits default values

### ISSUE THREAD

**Issue by greuelpirat** [aaubry/YamlDotNet#450]
After updating to 8.0.0 the Serializer

```
var serializer = serializerBuilder
                    .DisableAliases()
                    .BuildValueSerializer();
```

is emitting default values altough .EmitDefault() is not called. Has this behaviour changed? How can I disable this with 8.0.0?

**Comment by aaubry** [comment]
Yes, this behaviour has changed. You can read more about it in the [release notes](https://github.com/aaubry/YamlDotNet/releases/tag/v8.0.0), which you should always read before upgrading to a different major version.

**Comment by greuelpirat** [comment]
I must apologize. I did not check the release notes. sorry.

**Comment by aaubry** [comment]
No worries 👍. I realize that my response was a bit harsh, sorry about that.
