### ISSUE TITLE
No setter dictionary property deserialization

### ISSUE THREAD

**Issue by powerumc** [aaubry/YamlDotNet#455]
I have a yaml file.
```yaml
---
Name: aaa
Age: 12
Props:
  "text/html": a
```

And I have a class.
```csharp
public class YamlData
{
    public string Name { get; set; }
    public int Age { get; set; }
    public Dictionary<string, string> Props { get; } = new Dictionary<string, string>();
}
```

Specially, `YamlData.Props` dictionary has only get accessor.

For deserializing,
```csharp
var deserializerBuilder = new DeserializerBuilder()
                .IgnoreUnmatchedProperties()
                .Build();

var data = deserializerBuilder.Deserialize<YamlData>(File.ReadAllText("test.yaml"));
```

`data.Props` dictionary count is zero.
if I put the `set` on `Props` property, It is well.
But I can not change the `YamlData.Props` in code.

How to resolve these problem?

**Comment by EdwardCooke** [comment]
I believe this is fixed now with no comments in over 4 years. Closing it. If you still have problems open a new issue.
