### ISSUE TITLE
DefaultValuesHandling is not a valid named attribute argument because it is not a valid attribute parameter type

### ISSUE THREAD

**Issue by Phyksar** [aaubry/YamlDotNet#466]
DefaultValuesHandling attribute is not usable in Visual Studio 2019, I assume this is because it is declared as nullable enum.

https://github.com/aaubry/YamlDotNet/blob/bb70515e2bf481f55806c082524a4e7bf79cc3ef/YamlDotNet/Serialization/YamlMember.cs#L61

When using it on a class field compiler outputs following message:
```
Severity  Code    Description
Error	  CS0655  'DefaultValuesHandling' is not a valid named attribute argument because it is not a valid attribute parameter type
```

**Comment by aaubry** [comment]
Thanks for reporting this problem. I'll look into this and get back to you, hopefully tomorrow.

**Comment by aaubry** [comment]
Of course you're right. We can't use nullables in custom attributes. I'll fix that.
