### ISSUE TITLE
Is there a way to not save emojis as code points?

### ISSUE THREAD

**Issue by Kwoth** [aaubry/YamlDotNet#472]
Hello, I'm trying to save unicode emojis to a yaml file, but they get saved as utf-8 code points.

I've tried changing encoding on StreamWriter to no avail.

The below code outputs `A: "\U0001F604\U0001F4AF\U0001F4A5"` instead of `A: "😄💯💥"`
```cs
using System.IO;
using System.Text;
using YamlDotNet.Core;
using YamlDotNet.Serialization;

namespace TestYaml
{
    public class Test
    {
        public string A { get; set; } = "😄💯💥";
    }

    public class Program
    {
        static void Main(string[] args)
        {
            var serializer = new SerializerBuilder()
                .Build();

            using (var textStream = new StreamWriter("./test.yml", false, Encoding.UTF8))
            {
                serializer.Serialize(new Emitter(textStream), new Test());
            }
        }
    }
}
```

Any help is appreciated. 
Thanks

**Comment by aaubry** [comment]
The [YAML specification](https://yaml.org/spec/1.2/spec.html#printable%20character//) demands that such characters are encoded. Only printable characters are allowed without escaping.

**Comment by aaubry** [comment]
I will close the issue as I don't have any solution to offer. Feel free to reopen it if needed.

**Comment by azhe403** [comment]
Any way to keep emojis, like passing boolean to keep emojis?
