### ISSUE TITLE
Deserializing Complex Mappings into Dictionary Classes with anchor support

### ISSUE THREAD

**Issue by hoffmanntravis** [aaubry/YamlDotNet#474]
Hello,

I'll start by saying I've looked at this problem extensively, but I'm also a bit of a novice here so apologies if this is documented elsewhere or if I'm asking the wrong questions entirely.  I didn't see anything evident in the issues reported here that fit the bill.

What I'm trying to do is deserialize a YAML dictionary of objects that have both a unique property or set of properties using a 'complex mapping' AND an 'anchor' associated with the dictionary.  I could do this with a list of objects, but I want uniqueness.  I could also do this with basic dictionary objects, but I also want the ability to define compound keys.  Primarily consider the Environments and Regions dictionaries in the example below:

```
RegionShortCodes:
  ? &cu1 cu1 
  ? &eu2 eu2

Regions: 
 ? &centralus1
   Name: Central US
 : ShortCode: *cu1

 ? &eastus2    
   Name: East US 2
 : ShortCode: *eu2

Environments:
 ?    &devus
       Name: DEV
       Country: US
 :     Production: false
       Regions:
        Primary: *eastus2
        Secondary:   

 ?    &qaus
       Name: QA
       Country: US
 :     Production: false
       Regions:
        Primary: *eastus2
        Secondary:     
```

Powershell-Yaml, another deserializer, likes this YAML just fine.  The region names are unique and treated as the key, the anchors work as expected, and all is well.  YAMLDotNet however throws an error as soon as it get's to the line after 'Regions:'

InvalidOperationException: Failed to create an instance of type 'System.String'.

I think the error is fairly clear: it doesn't like me leading in with either the ? or the & on the anchor, as it's expecting a string as the key for the dictionary.  I was able to cast it as an object, but I don't think that's really what I'm trying to do here; I really am looking for it to not process the anchor as the key but instead the first attribute it encounters.  Somehow powershell-yaml at least computes this correctly and assigns uniqueness while allows the anchor to be used as a reference later but not computing it as part of the key.  I'm not clear if this yaml should be considered valid or not though.

Environments similarly works in poweshell-yaml with both an anchor as well as a compound key of name and country combined.  Below is snippet of a class I'm using to parse the data.

```
    public class VariableSchema
    {
        [YamlMember(Alias = "Subscriptions")]
        public Dictionary<string, Subscription> Subscriptions { get; set; }

        [YamlMember(Alias = "Environments")]
        public Dictionary<string, Environment> Environments { get; set; }

        [YamlMember(Alias = "Regions")]
        public Dictionary<string, Region> Regions { get; set; }
    }

    public class Region
    {
        [YamlMember(Alias = "Name")]
        public string Name { get; set; }

        [YamlMember(Alias = "ShortCode")]
        public string ShortCode { get; set; }
    }
```

Is what I'm attempting here possible or sensible, or have I missed the idea somewhere?  I can likely settle for a basic key and get 90% of what I want, but a complex mapping with an anchor applied I believe is ideal state.

Thanks so much,
Travis

**Comment by hoffmanntravis** [comment]
I think it's also worth mentioning YAML linters online seem to have mixed opinions about the YAML above.  At least some agree it's valid, but it's a bit unclear what is and is not valid YAML.  Seems to depend on the parser?

**Comment by aaubry** [comment]
Your model does not match the YAML document. That's why deserialization fails. For example, the `Regions` property is declared as a dictionary with string keys, but in the YAML document that key is a mapping, not a scalar (string).

A possible model would like like this:

```c#
public class VariableSchema
{
	public Dictionary<RegionIdentifier, Region> Regions { get; set; }
}

public class RegionIdentifier
{
	public string Name { get; set; }
}

public class Region
{
	public string ShortCode { get; set; }
}
```

I have created a sample that is able to parse your document: https://dotnetfiddle.net/xZu0Kz

**Comment by hoffmanntravis** [comment]
@aaubry 

Just wanted to say thanks so much for the fast, thoughtful response, and even a full example to boot!  The notion of ID as a class makes perfect sense now but I didn't put that together.  I was able to take your example and extend it to multiple additional cases with no issues :). Hopefully this is useful to someone else as examples of interesting things you can do with YAML and your library (they were at least to me anyway).
