### ISSUE TITLE
Pass ScalarStyle to members of Dictionary

### ISSUE THREAD

**Issue by nj0yeh** [aaubry/YamlDotNet#478]
The ScalarStyle of a Dictionary is not used for members of the Dictionary.
```
        [YamlMember(ScalarStyle = ScalarStyle.DoubleQuoted)]
        public Dictionary<string, object> EnvironmentVariables { get; set; }
```
The problem seems to be that in TraverseDictionary there is a call to GetObjectDescriptor that creates a new ObjectDescriptor with ScalarStyle = ScalarStyle.Any.

**Comment by aaubry** [comment]
The problem with this is that each element of a Dictionary will potentially produce two scalars. One for the key and another for the value. This means that, the following dictionary:

```c#
new Dictionary<string, object> {
  { "one", 1 },
  { "two", 2 }
}
```

would serialize as:

```c#
"one": "1"
"two": "2"
```

While this may be desirable in some cases, I'm sure that many people would want to control the scalar style of the keys and values independently.

Also, it may not be appropriate to use the `YamlMember` attribute to control how children are serialized. Currently the attribute applies only to the member to which it is applied. Maybe we need a different attribute to control how keys and values are emitted in dictionaries. What do you think ?

**Comment by nj0yeh** [comment]
Yes, in fact it is not that easy. What we needed is quotes around every string value in a Dictionary<string, object>, which can again contain Dictionary<string, object>s or List<object>s.

We hard-coded it by putting this code in TraverseDictionary after `var value = GetObjectDescriptor(entry.Value, valueType);`:
```
if (entry.Value is string)
{
    value.ScalarStyle = ScalarStyle.DoubleQuoted;
}
```

We did the same in TraverseList:
```
foreach (var item in (IEnumerable)value.NonNullValue())
{
	var listItemValue = GetObjectDescriptor(item, itemType);
	if (item is string)
	{
		listItemValue.ScalarStyle = ScalarStyle.DoubleQuoted;
	}

	Traverse(index, listItemValue, visitor, context, path);
	++index;
}
```

Of course we had to make ScalarStyle public settable. Perhaps it would make sense to create a global serializer settings to achieve this behaviour. It makes a big difference if the values are quoted or not e. g. for Helm (https://helm.sh/).

**Comment by dynamiquel** [comment]
This is just what I needed. Thanks.
It would be nice if I didn't need to edit the source to do this. I'm using dynamics and so I guess the deserialiser can't figure out what's a string or a number.

I then just used a custom INodeTypeResolver to assume that any scalar with the DoubleQuoted style is a string.

```cs
private class ScalarNodeTypeResolver : INodeTypeResolver
{
    bool INodeTypeResolver.Resolve(NodeEvent nodeEvent, ref Type currentType)
    {
        if (currentType != typeof(object))
            return false;

        if (nodeEvent is Scalar scalar)
        {
            if (scalar.Style == ScalarStyle.DoubleQuoted)
            {
                currentType = typeof(string);
                return true;
            }
        }
    }
}
```

**Comment by EdwardCooke** [comment]
There’s an option to set default quoting style now. Closing this since that should solve the problem mentioned.
