### ISSUE TITLE
Deserialize into a fixed type when the property name contains prefix

### ISSUE THREAD

**Issue by kpko** [aaubry/YamlDotNet#480]
Hi,

Is there a way I can get YamlDotNet to deserialize into a specified type according to the name of the property?

Background:

I want to deserialize a yaml document that looks like this:
```yaml
parameters:
  name: test
  $myvalue: ({ result: 5 + 10 })
```

the myvalue member is given to a javascript interpreter as a string and gets evaluated. **parameters** is a Dictionary<string, string>.

The value **({ result: 5 + 10 })** is not treated as a string and therefore the deserialization fails. I could work around this by quoting the value but I want to be able to prefix every property I have with a dollar sign to trigger my interpreter. 

Is there a way for me to tell the YamlDotNet deserializer to treat every property as a string once the name contains a specific prefix? 

Thanks!

**Comment by aaubry** [comment]
This doesn't work because your example is not valid YAML. Since your expression contains a mapping character `:`, it needs to be quoted:

```yaml
parameters:
  name: test
  $myvalue: "({ result: 5 + 10 })"
```

I would suggest a different approach which would be to take advantage of tags to indicate that a value is an expression. You could use a syntax similar to this one:

```yaml
parameters:
  name: test
  $myvalue: !eval 5 + 10
```

The `!eval` tag would need to be mapped to a type that would evaluate the expression when converted to string. A very rough implementation could be:

```c#
[TypeConverter(typeof(EvalExpression.EvalExpressionConverter))]
public class EvalExpression : IYamlConvertible {
  public class EvalExpressionConverter : TypeConverter {
    public override bool CanConvertTo(ITypeDescriptorContext context, Type destinationType)
    {
      return destinationType == typeof(string);
    }

    public override object ConvertTo(ITypeDescriptorContext context, CultureInfo culture, object value, Type destinationType)
    {
      return ((EvalExpression)value).Evaluate();
    }
  }
  
  private string expression;
  
  public void Read(IParser parser, Type type, ObjectDeserializer nestedDeserializer)
  {
    var scalar = parser.Consume<Scalar>();
    expression = scalar.Value;
  }
  
  public void Write(IEmitter emitter, ObjectSerializer nestedSerializer)
  {
    emitter.Emit(new Scalar("!eval", expression));
  }
  
  public string Evaluate()
  {
    return "15"; // TODO: Actually evaluate the expression
  }
}
```

You'll need to register the tag on the deserializer:

```c#
var deserializer = new DeserializerBuilder()
    .WithTagMapping("!eval", typeof(EvalExpression))
    .Build();
```

[See a working example here](https://dotnetfiddle.net/W5eGFg)

**Comment by kpko** [comment]
Hi,

thank you very much for the quick response and the example. I think I will build on your example and go a similiar route by deserializing into an "Expression" object that gets evaluated later. 

Thanks again for the clarification :)
