### ISSUE TITLE
Throw exception on missing nodes during deserialization (question)

### ISSUE THREAD

**Issue by BlazingTwist** [aaubry/YamlDotNet#488]
As my current project is still deeply stuck in the conceptualization-stage, I am frequently expanding my config structure - and occasionally my config will be outdated compared to the program itself (my fault entirely).
Outdated meaning, in this case, that my config is missing a node that is required by my program.

Currently, the Deserializer will silently ignore any fields of my config (class) that are not in the config (YAML), leaving those fields uninitialized, leading to a NullPointerException further down the line - or not, which will break predictability of my program.

Instead, I would like it to throw an exception similar to the one thrown when the YAML contains extra nodes that don't have corresponding fields to be matched to.

Are there any existing methods to enable this behavior or will I have to create a custom validator for that?

**Comment by aaubry** [comment]
I think that the best design would be to deserialize DTOs that would then be used to initialize a domain model containing all the validations.
If you'd rather use the deserialized values directly, an option is to use validation attributes, [as shown here](https://github.com/aaubry/YamlDotNet/wiki/Samples.ValidatingDuringDeserialization).

**Comment by rcdailey** [comment]
Normally I'd agree with your "best design" opinion, but there's certain important metadata I don't believe we'd be able to get post-deserialization that would be very helpful to communicate to users so they can quickly find and fix the problem. A good example is line number.

With a deserialized object, how do I throw an exception with line number information to help users identify the parent YAML element that is missing the required property?
