### ISSUE TITLE
8.1.1 bug

### ISSUE THREAD

**Issue by vitidev** [aaubry/YamlDotNet#492]
test yaml: 

    Text: >
       Sed ut perspiciatis, 
       maiores alias.   
   
    Value: foo

test code:

    static void Main(string[] args)
    {
        var deserializer = new DeserializerBuilder().WithNamingConvention(PascalCaseNamingConvention.Instance).Build();
        using (var textReader = File.OpenText("z:/test.yaml"))
        {
            var obj =  deserializer.Deserialize<Data>(textReader);
        }
    }
    public class Data
    {
        public string Text { get; set; }
        public string Value { get; set; }
    }

YamlDotNet 8.1.0 - works fine
YamlDotNet 8.1.1 cause error:

    YamlDotNet.Core.SemanticErrorException: '(Line: 5, Col: 1, Idx: 62) - (Line: 5, Col: 1, Idx: 62): 
    While scanning a literal block scalar, found more spaces in lines above first content line.'

.net48/netcore3.1

**Comment by aaubry** [comment]
I [tried to reproduce this error](https://dotnetfiddle.net/R7MCmv) with the YAML that you provided, but is works fine. Can you provide the exact file that you are using ?

**Comment by vitidev** [comment]
>Can you provide the exact file that you are using ?

[test.zip](https://github.com/aaubry/YamlDotNet/files/4616671/test.zip)

**Comment by vitidev** [comment]
the reason is these spaces 

![Image 8](https://user-images.githubusercontent.com/2243958/81718081-ffb68600-9483-11ea-91a4-9eddb9983de3.png)

**Comment by aaubry** [comment]
This definitely looks like a bug. Thanks for reporting it!

**Comment by lesair** [comment]
@aaubry I stumbled upon this bug as well. Every time lines with only spaces are preceding another Yaml key, the YamlDotNet.Core.SemanticErrorException "While scanning a literal block scalar, found more spaces in lines above first content line" exception is thrown.

Any workarounds or bug fix ETA?

**Comment by aaubry** [comment]
@lesair I am unable to try to fix this bug at the moment. I'm not sure if I will be able to pick it up during the next few weeks.

@am11 It appears that this bug was introduced in #475, specifically in [this line](https://github.com/aaubry/YamlDotNet/blob/7490e14fb4d673bc135c4691fa776af57d424e29/YamlDotNet/Core/Scanner.cs#L1699). I don't have much context on this change. Can you help ?

**Comment by am11** [comment]
Thanks for the report. The fix is up in #497.

**Comment by aaubry** [comment]
The fix is included in release [8.1.2](https://www.nuget.org/packages/YamlDotNet/8.1.2). The package should be available on NuGet in a few minutes.

**Comment by lesair** [comment]
Thank you @aaubry and @am11 it's working correctly now.
