### ISSUE TITLE
Serializer doesn't handle tag mappings

### ISSUE THREAD

**Issue by xoofx** [aaubry/YamlDotNet#50]
Somewhat related to issue #49, the Serializer class doesn't handle tag mappings unlike Deserializer that can handle it. This is an unbalanced feature that is making impossible to output a type with a different tag (for example, we want to remove some namespaces for some known applications).

If you give me some hint where you would introduce it - I imagine in a chained IObjectGraphVisitor - but I'm not sure, I could try to add this feature.

**Comment by aaubry** [comment]
Closing this because the issue probably no longer exists. Please open a new issue if you still encounter this bug.
