### ISSUE TITLE
Parsing multi document throws "Encountered an unresolved tag"

### ISSUE THREAD

**Issue by greuelpirat** [aaubry/YamlDotNet#502]
The following unit test works with `8.1.0` but not with `8.1.2` (don't know about `8.1.1`)

```
public class CustomClass
{
  public string Property { get; set; }
}

[TestMethod]
public void TestDeserializeTag()
{
	const string yaml = @"
%TAG ! !custom.tag.com,1:
--- !MySuperTag
Property: Value1

--- !MySuperTag
Property: Value2
";

  var reader = new StringReader(yaml);
  var parser = new Parser(reader);
  parser.Consume<StreamStart>();
  
  var deserializer = new DeserializerBuilder().WithNamingConvention(PascalCaseNamingConvention.Instance)
    .IgnoreUnmatchedProperties()
    .WithTagMapping("!custom.tag.com,1:MySuperTag", typeof(CustomClass))
    .Build();
  
  var list = new List<object>();
  while (parser.Accept<DocumentStart>(out _))
    list.Add(deserializer.Deserialize(parser));

  parser.Consume<StreamEnd>();

  Assert.AreEqual(2, list.Count);
}
````

`8.1.2`  throws following exception:
```
YamlDotNet.Core.YamlException: (Line: 6, Col: 5, Idx: 70) - (Line: 7, Col: 1, Idx: 83): Encountered an unresolved tag '!MySuperTag'
    bei YamlDotNet.Serialization.NodeTypeResolvers.PreventUnknownTagsNodeTypeResolver.YamlDotNet.Serialization.INodeTypeResolver.Resolve(NodeEvent nodeEvent, Type& currentType)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.GetTypeFromEvent(NodeEvent nodeEvent, Type currentType)
   bei YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   bei YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   bei YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser)
```

seems to be a problem with type resolvers in multiple document. there is no issue with a single document.

**Comment by aaubry** [comment]
This is because directives belong to a single document. In the previous version, tag directives were incorrectly carried over to the next document. You will need to repeat the tag directive for each document:
```yaml
%TAG ! !custom.tag.com,1:
--- !MySuperTag
Property: Value1
...
%TAG ! !custom.tag.com,1:
--- !MySuperTag
Property: Value2
```

**Comment by greuelpirat** [comment]
Oh! I did not know this. Okay, I will have to check this in our team. Thank you!

**Comment by QualityRobD** [comment]
This is interesting, I'm running into a similar "issue" where online linters and applications like CircleCI are expressing that this is valid YAML but YamlDotNet is say it's not valid yaml.

**Comment by greuelpirat** [comment]
@QualityRobD I was also irritated at first. But I agree that the strict interpretation of the YAML-Spec have no TAGs across documents.

https://yaml.org/spec/1.2/spec.html#document//

> A YAML character stream may contain several documents. Each document is completely independent from the rest.

**Comment by QualityRobD** [comment]
@greuelpirat, totally makes sense. I mispoke earlier about the circleci file, what I am seeing is actually some additional stuff for mkdocs, referenced here: https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```

The mkdocs example above is the exact piece of yaml that YamlDotNet is complaining about in my case. It works wonderfully with mkdocs, since it's provided by them directly. The problem lies when I try to deserialize the yaml using YamlDotNet. 

I'm not really sure how to proceed at this point. I know this is an older thread but if you or anyone else has a suggestion it would be really helpful.

**Comment by QualityRobD** [comment]
@aaubry, unless I am mistaken I think YamlDotNet is not properly handling language specific data tags like [pyyaml-tags](https://pypi.org/project/pyyaml-tags/#:~:text=PyYAML%2DTags%20is%20a%20library,simple%20decorators%20and%20meta%20API.)


or here: [yaml-tags](https://www.javatpoint.com/yaml-tags)
![image](https://user-images.githubusercontent.com/17755173/119507584-f588c200-bd3c-11eb-8c69-097654f937ad.png)

So in this case I am trying to validate a yaml file used for mkdocs, provided by mkdocs, which leverages language (python) specific tags. However, YamlDotNet is saying that the yaml is invalid.

Thoughts on the matter?

**Comment by greuelpirat** [comment]
@QualityRobD This is not document related so it is a other issue

And to be honest this yaml does not look right to me. Tags without `<` and `>` are shorthand-tags. but those requires a TAG-directive. And it also quite long for a short hand tag.
https://yaml.org/spec/1.2/spec.html#id2784064
but how knows ... :-)

**Comment by QualityRobD** [comment]
@greuelpirat, thanks for the input. I opened #615 with the relevant data just to at the very least log the issue my company is encountering.
