### ISSUE TITLE
is there a way to add line text

### ISSUE THREAD

**Issue by sthwentwrong** [aaubry/YamlDotNet#503]
I'd like to get below format:
```
%YAML:1.0
---
Items:
   - Item: "F:\\Workspace"
```

yes, lines 1, 3, 4 are done. but I don't have a chance to add one line "---", appreciated if there is a way.
my code:

```
var rootNode = new YamlMappingNode();
            var doc = new YamlDocument(rootNode);
            var items = new YamlSequenceNode();
            rootNode.Add("%YAML", new YamlScalarNode("1.0"));
            
            rootNode.Add("Items", items);
            foreach (var l in data)
            {
                items.Add(new YamlMappingNode(
                    new YamlScalarNode("Item"),
                    new YamlScalarNode(l) { Style = ScalarStyle.DoubleQuoted }));
            }

            using (var writer = new StreamWriter(filePath))
            {
                new Serializer().Serialize(writer, doc.RootNode);
            }
```

**Comment by aaubry** [comment]
You seem to be trying to produce a YAML 1.0 document. The `%YAML:1.0` is a [directive](https://yaml.org/spec/1.0/index.html#model-directive) that specifies the version of the YAML language. Unfortunately, YamlDotNet does not support YAML 1.0.
You could add the `%YAML:1.0---` manually before serializing:
```c#
writer.WriteLine("%YAML:1.0");
writer.WriteLine("---");
```
I can't guarantee that the output will be valid YAML 1.0 though.

**Comment by sthwentwrong** [comment]
> You seem to be trying to produce a YAML 1.0 document. The `%YAML:1.0` is a [directive](https://yaml.org/spec/1.0/index.html#model-directive) that specifies the version of the YAML language. Unfortunately, YamlDotNet does not support YAML 1.0.
> You could add the `%YAML:1.0---` manually before serializing:
> 
> ```cs
> writer.WriteLine("%YAML:1.0");
> writer.WriteLine("---");
> ```
> 
> I can't guarantee that the output will be valid YAML 1.0 though.

yes, hard code to write them line by line works for me. thx.
