### ISSUE TITLE
Change Yaml file content using a stream

### ISSUE THREAD

**Issue by awdm** [aaubry/YamlDotNet#504]
I have some extensive YAML-files, in which I need to only change a few lines when deploying new instances of my software. In the samples section, the only one that deals with serialization uses an object graph. In my case however, it would mean a lot of overhead work to deserialize the entire document into an object graph, only to change a few lines.

My approach was to read the file content as a stream, then change the values i need to change in the dictionary that comes from `yaml.Documents[0].RootNode.Children`, and then serialize it back into the file. Is that possible?

**Comment by pensono** [comment]
Yes, it's possible. You might find the `dynamic` type useful for this.

Example:
https://dotnetfiddle.net/tQnR6C

```csharp
var yaml = @"
products:
- &apple
  name: Apple
  cost: 1.25

sales:
- customer: pensono
  items:
  - *apple
";

var deserializer = new DeserializerBuilder().Build();
var data = deserializer.Deserialize<dynamic>(yaml);

data["sales"][0]["customer"] = "awdm";

var serializer = new SerializerBuilder().Build();
var serialized = serializer.Serialize(data);

Console.WriteLine(serialized);
```

**Comment by awdm** [comment]
That worked like a charm. Thanks
