### ISSUE TITLE
WithoutTypeInspector<TTypeInspector> throws KeyNotFoundException when trying to remove an existing inspector

### ISSUE THREAD

**Issue by John-Welch** [aaubry/YamlDotNet#507]
I was trying to remove the `ReadableAndWritablePropertiesTypeInspector` from a new Deserializer using:
```csharp
var deserializer = new DeserializerBuilder()
    .WithoutTypeInspector<ReadableAndWritablePropertiesTypeInspector>()
    .Build();
```
This throws a `KeyNotFoundException`, saying that no component of type `ITypeInspector` is registered.
On looking through the code, `BuilderSkeleton.cs` around line 270 contains 
```csharp
        public TBuilder WithoutTypeInspector<TTypeInspector>()
            where TTypeInspector : ITypeInspector
        {
            return WithoutTypeInspector(typeof(ITypeInspector));
        }
```
I think that the last line should read
```csharp
            return WithoutTypeInspector(typeof(TTypeInspector));
```
with **T**TypeInspector, not **I**TypeInspector.

**Comment by John-Welch** [comment]
Fortunately, there's an easy workaround: just call the non-generic overload that takes a `type` parameter. In my case:
```csharp
var deserializer = new DeserializerBuilder()
    .WithoutTypeInspector(typeof(ReadableAndWritablePropertiesTypeInspector))
    .Build();
```

**Comment by aaubry** [comment]
Thanks for reporting this, it was clearly a bug and your analysis was correct.
