### ISSUE TITLE
Using WithEventEmitter() to double-quote booleans

### ISSUE THREAD

**Issue by awdm** [aaubry/YamlDotNet#509]
I'm trying to use a ChainedEventEmitter to double-quote boolean values because Kuberenetes for some reason wants them to be. This is my code:

```cs
public class ForceQuotedBooleanValuesEventEmitter : ChainedEventEmitter
{
    public ForceQuotedBooleanValuesEventEmitter(IEventEmitter nextEmitter) : base(nextEmitter) { }

    public override void Emit(ScalarEventInfo eventInfo, IEmitter emitter)
    {
        if(typeof(bool).IsAssignableFrom(eventInfo.Source.Type))
        {
            eventInfo = new ScalarEventInfo(eventInfo.Source)
            {
                Style = ScalarStyle.DoubleQuoted
            };
        }

        nextEmitter.Emit(eventInfo, emitter);
    }
}

ISerializer serializer = new SerializerBuilder()
    .WithEventEmitter(next => new ForceQuotedBooleanValuesEventEmitter(next))
    .Build();
```

It doesn't work however. Booleans are still non-quoted.

**Comment by pensono** [comment]
Seems to work fine for me. Also you can just set the `Style` property of the `ScalarStyle` instead of creating a new object.

https://dotnetfiddle.net/NmHcL4

```
using System;
using System.IO;
using System.Collections.Generic;
using YamlDotNet.Serialization;
using YamlDotNet.Core;
using YamlDotNet.Core.Events;
using YamlDotNet.Serialization.EventEmitters;
					
public class Program
{
	public static void Main()
	{
		var serializer = new SerializerBuilder()
			.WithEventEmitter(next => new ForceQuotedBooleanValuesEventEmitter(next))
			.Build();
		
		var serialized = serializer.Serialize(false);
		Console.WriteLine(serialized);
		
		var data = new TestObject
		{
			BoolProperty = true,
		};
		serialized = serializer.Serialize(data);
		Console.WriteLine(serialized);
	}
	
	public class TestObject 
	{
		public bool BoolProperty { get; set; }
	}
	
	public class ForceQuotedBooleanValuesEventEmitter : ChainedEventEmitter
	{
		public ForceQuotedBooleanValuesEventEmitter(IEventEmitter nextEmitter) : base(nextEmitter) { }

		public override void Emit(ScalarEventInfo eventInfo, IEmitter emitter)
		{
			if(typeof(bool).IsAssignableFrom(eventInfo.Source.Type))
			{
				eventInfo.Style = ScalarStyle.DoubleQuoted;
			}

			nextEmitter.Emit(eventInfo, emitter);
		}
	}
}
```

**Comment by awdm** [comment]
I experimented a bit and it seems the issue occurs when reading the data from a string as a _dynamic_, as you have recommended me in my [last issue](https://github.com/aaubry/YamlDotNet/issues/504).

`using System;
using System.IO;
using System.Collections.Generic;
using YamlDotNet.Serialization;
using YamlDotNet.Core;
using YamlDotNet.Core.Events;
using YamlDotNet.Serialization.EventEmitters;
					
public class Program
{
	private const string Document = "BoolProperty = true";
	public static void Main()
	{
		var input = new StringReader(Document);

		var deserializer = new DeserializerBuilder().Build();

		var serializer = new SerializerBuilder()
			.WithEventEmitter(next => new ForceQuotedBooleanValuesEventEmitter(next))
			.Build();
		
		var serialized = serializer.Serialize(false);
		Console.WriteLine(serialized);

		dynamic data = deserializer.Deserialize<dynamic>(input);

		serialized = serializer.Serialize(data);
		Console.WriteLine(serialized);
	}
	
	public class TestObject 
	{
		public bool BoolProperty { get; set; }
	}
	
	public class ForceQuotedBooleanValuesEventEmitter : ChainedEventEmitter
	{
		public ForceQuotedBooleanValuesEventEmitter(IEventEmitter nextEmitter) : base(nextEmitter) { }

		public override void Emit(ScalarEventInfo eventInfo, IEmitter emitter)
		{
			if(typeof(bool).IsAssignableFrom(eventInfo.Source.Type))
			{
				eventInfo.Style = ScalarStyle.DoubleQuoted;
			}

			nextEmitter.Emit(eventInfo, emitter);
		}
	}
}`

**Comment by awdm** [comment]
I was able to get it to work by changing the condition in the Emiter.

```
class ForceQuotedBooleanValuesEventEmitter : ChainedEventEmitter
    {
        public ForceQuotedBooleanValuesEventEmitter(IEventEmitter nextEmitter) : base(nextEmitter) { }

        public override void Emit(ScalarEventInfo eventInfo, IEmitter emitter)
        {
            if (eventInfo.Source.Value.ToString().Contains("true") || eventInfo.Source.Value.ToString().Contains("false"))
            {
                eventInfo.Style = ScalarStyle.DoubleQuoted;
            }

            nextEmitter.Emit(eventInfo, emitter);
        }
    }
```
