### ISSUE TITLE
Unable to serialize object with property without getter

### ISSUE THREAD

**Issue by hc4** [aaubry/YamlDotNet#518]
If object has property without getter Serializer throws NullReferenceException.

It happens because GetPublicProperties doesn't check if property has getter.
https://github.com/aaubry/YamlDotNet/blob/6194e9dde6242ca24520e57f1532b20097ef99c9/YamlDotNet/Helpers/Portability.cs#L188

**Comment by hc4** [comment]
I'm using latest version 8.1.2 from nuget

**Comment by EdwardCooke** [comment]
This was resolved in version 12.
I'm closing this issue, if you still see problems let me know and I'll get them resolved.
