### ISSUE TITLE
Parsing performance of large YAML files

### ISSUE THREAD

**Issue by PJB3005** [aaubry/YamlDotNet#519]
We're using YAML as a data format in our game, from data definitions to map files. We have a modestly sized map files now (that is at the time of writing, [~700 KiB uncompressed/38k lines](https://github.com/space-wizards/space-station-14/blob/8f1a74dcd1b8973a730ef6aeebe1f9f427886843/Resources/Maps/saltern.yml)).

I should note that we're *not* using deserialization features, JUST the AST (`YamlMappingNode` etc directly).

The parsing performance is really starting the hurt (currently taking about 10% of debug server startup time *just* spent inside YamlDotNet parsing the main map file) and, the kicker, 90% of *that* time is spent inside various collection ops like `Array.Copy`, `List.Insert` and `List.RemoveAt`.

<details>

<summary>Some profiling results</summary>

![image](https://user-images.githubusercontent.com/8107459/90338892-2fc67580-dfed-11ea-8cf3-35f25da967f1.png)

![image](https://user-images.githubusercontent.com/8107459/90338898-39e87400-dfed-11ea-82d1-5a57ce22f2b1.png)

</details>

Could this be optimized? I tried saving the map files in flow style instead (since from my looking at the code the reason there's so many list butchering is because of parsing issues with block style?) but it did not seem to help perf. In fact it seems slightly worse with flow style.

**Comment by aaubry** [comment]
There's probably room for improvement. I would be interested in exploring this but I can't dedicate much time to performance right now because I already have another development in progress. I can probably provide some help if you guide this process, though.

I've looked at `InsertionQueue`, which appears in your screenshot, and I can see that there's a big TODO:
> // TODO: Use a more efficient data structure

Looking at the `Dequeue` method, it is clear that it is really inefficient since it always removes the first item from a `List`, meaning that every other element needs to be shifted. We could start by changing this implementation to use a more efficient algorithm.

**Comment by aaubry** [comment]
Would you be able to provide an example of such a large YAML file ?

**Comment by PJB3005** [comment]
> Would you be able to provide an example of such a large YAML file ?

[From our repo](https://github.com/space-wizards/space-station-14/blob/8f1a74dcd1b8973a730ef6aeebe1f9f427886843/Resources/Maps/saltern.yml)

**Comment by aaubry** [comment]
Hello!
I've changed the implementation of `InsertionQueue` and `LookAheadBuffer` in an [experimental branch](https://github.com/aaubry/YamlDotNet/pull/533). Would you be able to test your code against [this build](https://ci.appveyor.com/project/aaubry/yamldotnet/builds/35420365/artifacts) to see if there is any improvement ?

**Comment by PJB3005** [comment]
Pretty good improvement!

Before:

![image](https://user-images.githubusercontent.com/8107459/94714486-7c230600-034c-11eb-884d-564dea645861.png)

After:

![image](https://user-images.githubusercontent.com/8107459/94714524-8b09b880-034c-11eb-810b-88a5e4d0f58f.png)

**Comment by aaubry** [comment]
Nice! I'll merge this change then.
Of course this was just a low-hanging fruit. I'm sure there are many more optimizations that can be performed. If you can identify more bottlenecks, I can see what we can do.

**Comment by EdwardCooke** [comment]
Since there was a fix for this merged in, I'm going to close this issue. If you need more assistance, let me know.
