### ISSUE TITLE
[Question] Is there a way I can use byte[] instead of string?

### ISSUE THREAD

**Issue by dynamiquel** [aaubry/YamlDotNet#524]
My project favours **byte[]** over **string** and doing Encoding.UTF8.GetBytes/GetString seems pretty inefficient.

Is there a way I can easily use byte[] without converting to string to save performance?

I'm currently doing: `Encoding.UTF8.GetBytes(serialiser.Serialize(value))` and `deserialiser.Deserialize<T>(Encoding.UTF8.GetString(bytes))`.

**Comment by aaubry** [comment]
Of course! You can pass a `TextWriter` that writes to a `Stream`. Here's an example that gives you access to the bytes, but you could also write directly to a file or some other stream:

```c#
var serializer = new SerializerBuilder().Build();

var buffer = new MemoryStream();
using (var writer = new StreamWriter(buffer))
{
    serializer.Serialize(writer, new { Hello = "world" });
}

var bytes = buffer.ToArray();
```

Please let me know if this answers your question.

**Comment by dynamiquel** [comment]
Yes, this perfectly answers my question. I didn't notice that SerializerBuilder.Serialize accepted a StreamWriter.
