### ISSUE TITLE
[Question] preserve property with empty string

### ISSUE THREAD

**Issue by srdjos** [aaubry/YamlDotNet#526]
Hi

as I cannot find the way, I would like to ask here. In my class I have string empty property:
name: ""

after serializing, the property is removed from .yml file. Also, I tried with the ChainedEventEmitter emitter, but the null or empty value does not come to the emitter. It looks like, the property is removed before the serializer hits the emitter:

Did I miss something in the serialization process?

```
public override void Emit(ScalarEventInfo eventInfo, IEmitter emitter)
        {
            if (eventInfo != null && eventInfo.Source.Type == typeof(string) && 
                (eventInfo.Source.Value == null || (string)eventInfo.Source.Value==""))
            {
                if (emitter != null)
                {
                    emitter.Emit(new Scalar(string.Empty));
                }
            }
            else
            {
                base.Emit(eventInfo, emitter);
            }
        }
```

**Comment by EdwardCooke** [comment]
This will be fixed when the next release goes out.
