### ISSUE TITLE
Case insensitive deserialization?

### ISSUE THREAD

**Issue by AndrewKnieriem** [aaubry/YamlDotNet#527]
Hi, the yaml I'm parsing is all lowercase and I'm deserializing it to a c# object. However, in c# I follow pascal casing. 

So when I try to deserialize the property "nugetversion" into "NugetVersion" the property is left null. None of the existing naming conventions seem to work. Any suggestions?

``` cs
            DeserializerBuilder deserializerBuilder = new DeserializerBuilder()
                .WithNamingConvention(YamlDotNet.Serialization.NamingConventions.CamelCaseNamingConvention.Instance)
                .IgnoreUnmatchedProperties();
            IDeserializer deserializer = deserializerBuilder.Build();
```

**Comment by aaubry** [comment]
You can write your own naming convention. Just create an implementation of `INamingConvention` that does what you want.

**Comment by aaubry** [comment]
It would be something like this:

```c#
class LowerCaseNamingConvention : INamingConvention
{
    public string Apply(string value) => value.ToLower();
}
```

**Comment by AndrewKnieriem** [comment]
Could you describe or point me to what Apply does? Is that how it converts from the yaml to the C# name, or vice versa?

**Comment by AndrewKnieriem** [comment]
I'm thinking a custom naming convention won't solve this problem since it only provides a name transform, and not an override for the way the strings get compared. For the Apply method to solve the problem it would have to be a string transform that will turn any given string into pascal case (the c# casing)... so that's probably not an option.

**Comment by AndrewKnieriem** [comment]
My solution for now is to use the YamlMember attribute:

``` cs
[YamlMember(Alias = "nugetversion", ApplyNamingConventions = false)]
public string NugetVersion { get; set; }
```

**Comment by AndrewKnieriem** [comment]
Sorry for the noise, re-opening this since the other tools that read the yaml are case insensitive, therefore I can't guarantee that the incoming yaml will always be the same case. The attribute works for incoming "nugetversion" but not if a different file has "NugetVersion" nor "nugetVersion".

**Comment by aaubry** [comment]
I hadn't understood that you need to have a case-insensitive naming convention. I thought that you wanted to always use lowercase. You can't achiev that with naming conventions because they are a 1-1 mapping between names, but you can use a custom `ITypeInspector`:

```c#
public class IgnoreCaseTypeInspector : ITypeInspector
{
    private readonly ITypeInspector innerTypeInspector;
    
    public IgnoreCaseTypeInspector(ITypeInspector innerTypeInspector)
    {
        this.innerTypeInspector = innerTypeInspector ?? throw new ArgumentNullException(nameof(innerTypeInspector));
    }
    
    public IEnumerable<IPropertyDescriptor> GetProperties(Type type, object? container)
    {
        return innerTypeInspector.GetProperties(type, container);
    }
    
    public IPropertyDescriptor GetProperty(Type type, object? container, string name, [MaybeNullWhen(true)] bool ignoreUnmatched)
    {
        var candidates = GetProperties(type, container)
            .Where(p => p.Name.Equals(name, StringComparison.OrdinalIgnoreCase));

        using (var enumerator = candidates.GetEnumerator())
        {
            if (!enumerator.MoveNext())
            {
                if (ignoreUnmatched)
                {
                    return null!;
                }

                throw new SerializationException($"Property '{name}' not found on type '{type.FullName}'.");
            }

            var property = enumerator.Current;

            if (enumerator.MoveNext())
            {
                throw new SerializationException(
                    $"Multiple properties with the name/alias '{name}' already exists on type '{type.FullName}', maybe you're misusing YamlAlias or maybe you are using the wrong naming convention? The matching properties are: {string.Join(", ", candidates.Select(p => p.Name).ToArray())}"
                );
            }

            return property;
        }
    }
}
```

The code is mostly copied from `TypeInspectorSkeleton`. What's different is how the property names are compared:
```c#
.Where(p => p.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
```

You can register this class in your `DeserializerBuilder` as follows:
```c#
DeserializerBuilder deserializerBuilder = new DeserializerBuilder()
    .WithNamingConvention(YamlDotNet.Serialization.NamingConventions.CamelCaseNamingConvention.Instance)
    .WithTypeInspector(n => new IgnoreCaseTypeInspector(n))
    .IgnoreUnmatchedProperties();
IDeserializer deserializer = deserializerBuilder.Build();
```

Let me know if this solved your problem.

**Comment by AndrewKnieriem** [comment]
Thanks thats awesome! I did see the TypeInspectorSkeleton and cloned locally to try it out, but this solution avoids changing the base code. I'll try it out tomorrow, thank you!

**Comment by AndrewKnieriem** [comment]
I can't use c# 8.0 features for this project, will removing the nullable reference types (`object?`, `[MaybeNullWhen(true)]`, `return null!;`) impact the performance or functionality of the code?

**Comment by AndrewKnieriem** [comment]
It works like a charm, thanks for the help!
