### ISSUE TITLE
Serialization of float of value 0 is omited

### ISSUE THREAD

**Issue by snowgoon88** [aaubry/YamlDotNet#530]
Hello,

float with zero (0f) value are not serialized. Is it on purpose ?

I have this Animat structure
```
public class Animat {
        public float animatRotDeg { get; set; }        
        public float animatMaxVelocity { get; set; }
}
```
when I serialize with 
```
Animat anim = new Animat {
animatRotDeg = 0f,
animatMaxVelocity = 200f
}

var serializer = new SerializerBuilder().Build();
var yaml = serializer.Serialize( anim );
```
I have 
```
animatMaxVelocity: 200
```
but if I use
```
Animat anim = new Animat {
animatRotDeg = 10f,
animatMaxVelocity = 200f
}
```
I have
```
animatRotDeg: 10
animatMaxVelocity: 200
```

**Comment by EdwardCooke** [comment]
I don't know what version it changed in, but the default appears to be defaulting to emit default values. If you want to change that, on the builder, you can call `ConfigureDefaultValuesHandling` and pass the appropriate enum value.

```csharp
var serializer = new SerializerBuilder()
    .ConfigureDefaultValuesHandling(DefaultValuesHandling.Preserve)
    .Build();
```

I'm going to close this issue, if you need further help, let me know.
