### ISSUE TITLE
Round Tripping YAML file (preservation of comments)....

### ISSUE THREAD

**Issue by DynConcepts** [aaubry/YamlDotNet#534]
Is there any way to accomplish this???

**Comment by EdwardCooke** [comment]
If you build a concrete class you can put a `YamlMember` attribute with a description on it to get that in to the yaml, but any other arbitrary comments in your YAML file, no, there is not. There is no record kept of what the original YAML file was after deserializing it into an object.

 An example of using the yaml member attribute to put in comments:
```csharp
using YamlDotNet.Serialization;

var serializer = new SerializerBuilder().Build();
var t = new Test { Value = 123 };
var yaml = serializer.Serialize(t);
Console.WriteLine(yaml);

public class Test
{
    [YamlMember(Description = "A comment")]
    public int Value { get; set; }
}
```

Results in:
```yaml
# A comment
Value: 123
```
