### ISSUE TITLE
Deserializing is not handling non-unique keys correctly

### ISSUE THREAD

**Issue by Khazuar** [aaubry/YamlDotNet#536]
According to the YAML spec (and common sense) keys in YAML-mappings should be a set of unique values. I frequently encounter errors (originating from tiny typos of mine), where a document (or mapping within a document) like

```yml
fu: bar
fu: baz
```

is interpreted like 

```yml
fu: baz
```

and the duplicate key issue is silently ignored. 

Would it be possible to at least have an option to treat duplicate keys as deserialization errors?

**Comment by stan-sz** [comment]
Thanks @nuttytree. The current changes does not handle duplicate keys in `DictionaryNodeDeserializer`, is that intentional?
This is also related to #764

**Comment by EdwardCooke** [comment]
Most likely an oversight, on my part as well. I’m working on getting a new release out shortly. If you want to put in a pr with the needed changes for it I can try and get it in.

**Comment by nuttytree** [comment]
Yes, an oversite on my part.  I have a task at work I committed to getting done today, I might still have time yet today to get a PR up, if not I will try to do it first thing in the morning.

**Comment by stan-sz** [comment]
Hi @EdwardCooke and @nuttytree - please check out the linked PR I just sent. Thanks!
