### ISSUE TITLE
YamlDotNet doesn't serialize Json.Net objects correctly

### ISSUE THREAD

**Issue by tomlm** [aaubry/YamlDotNet#545]
Given a JObject like this:
```csharp
       var obj = JObject.FromObject(new { text = 13, name = "bar" });
```

attempting to serialize it will create [] brackets instead of values.  
```
Console.WriteLIne(new Serializer().Serialize(obj));
---
text: []
name: []
```

If you convert it to an ExpandoObject it works correctly
```
Console.WriteLIne(new Serializer().Serialize(obj.ToObject<ExpandoObject>()));
---
text: 13
name: bar
```

**Comment by tomlm** [comment]
FYI, I have created a library that adds a type converter for JObject/JArray/JValue serialization to YamlDotNet.
https://github.com/tomlm/YamlConvert 
https://www.nuget.org/packages/YamlConvert/

**Comment by olee** [comment]
Wouldn't it be possible to adjust YamlDotNet to be able to serialize such json structures without needing a separate library?
