### ISSUE TITLE
YAML file that parses successfully in version 8.1.1 and several linters, fails to load in 9.1.0

### ISSUE THREAD

**Issue by ManfredLange** [aaubry/YamlDotNet#548]
The following test passes with YamlDotNet version `8.1.1` and fails with YamlDotNet version `9.1.0` with no other change than the package reference in the project file:

```csharp
      // from https://github.com/RimuTec/Faker/blob/e951efe18947d1ec2e9fb3482f5a21b7f9881df4/src/Faker.Tests/CompanyTests.cs#L206
      [Test]
      public void Foo()
      {
         using var input = new StringReader(Document);
         var yaml = new YamlStream();
         yaml.Load(input);
      }
      private const string Document =
         "en:" + "\n" +
         "  faker:" + "\n" +
         "    company:" + "\n" +
         "      suffix: [Inc, and Sons, LLC, Group]" + "\n" +
         "      # Buzzword wordlist from http://www.1728.com/buzzword.htm" + "\n" +
         "      buzzwords:" + "\n" +
         "        - [\"foo\", \"Facetoface\", \"Focused\", \"Frontline\", \"Fullyconfigurable\", \"Functionbased\", \"Fundamental\", \"Futureproofed\", \"Grassroots\", \"Horizontal\", \"Implemented\", \"Innovative\", \"Integrated\", \"Intuitive\", \"Inverse\", \"Managed\", \"Mandatory\", \"Monitored\", \"Multichannelled\", \"Multilateral\", \"Multilayered\", \"Multitiered\", \"Networked\", \"Objectbased\", \"Openarchitected\", \"Opensource\", \"Operative\", \"Optimized\", \"Optional\", \"Organic\", \"Organized\", \"Persevering\", \"Persistent\", \"Phased\", \"Polarised\", \"Pre-emptive\", \"Proactive\", \"Profit-focused\", \"Profound\", \"Programmable\", \"Progressive\", \"Public-key\", \"Quality-focused\", \"Reactive\", \"Realigned\", \"Re-contextualized\", \"Reengineered\", \"Reduced\", \"Reverseengineered\", \"Rightsized\", \"Robust\", \"Seamless\", \"Secured\", \"Selfenabling\", \"Sharable\", \"Standalone\", \"Streamlined\", \"Switchable\", \"Synchronised\", \"Synergistic\", \"Synergized\", \"Teamoriented\", \"Total\", \"Triplebuffered\" ]" + "\n" +
         "        - [\"24 hour\", \"24/7\", \"3rd generation\", \"4th generation\", \"5th generation\"]" + "\n" +
         "        - [\"ability\", \"access\", \"adapter\", \"algorithm\", \"alliance\"]";

```

When the test fails it is because of the following error:
```
YamlDotNet.Core.SemanticErrorException : (Line: 6, Col: 17, Idx: 101) - (Line: 6, Col: 18, Idx: 102): While parsing a block collection, did not find expected '-' indicator.
```

The above YAML code is a stripped down version of https://github.com/RimuTec/Faker/blob/master/src/Faker/locales/en/company.yml

I applied these changes to simplify the file and to try to narrow down what might cause the problem:
- removed all whitespaces from the first array under buzzwords
- removed all dashes '-' from the first array under buzzwords
- minimized the number of entries in the first array. If you take out the first element, i.e. "foo", the test passes. If you changed the value from "foo" to something else, e.g. "bar" it still fails. So, it's not about the content of that value.
- if you take out enough elements from the first array the test passes as well

The following three online linters claim that the content of the file is valid YAML:
- http://www.yamllint.com/
- https://codebeautify.org/yaml-validator
- https://jsonformatter.org/yaml-validator

It appears as if the exception is through if there are specificy counts of elements in the first array.

The above test is also available at https://github.com/RimuTec/Faker/blob/e951efe18947d1ec2e9fb3482f5a21b7f9881df4/src/Faker.Tests/CompanyTests.cs#L206

## Work around
Go back to YamlDotNet version `8.1.1`

**Comment by aaubry** [comment]
Thanks for reporting this. I will try to look into it today.

**Comment by aaubry** [comment]
I've identifed the commit that caused this regression. I will debug the code to figure out what is wrong.

**Comment by aaubry** [comment]
I have just pushed a fix for this bug. [Release 9.1.1](https://www.nuget.org/packages/YamlDotNet/9.1.1) contains the fix. Please confirm that this is working for you, thanks.

**Comment by ManfredLange** [comment]
@aaubry Hi Antoine, thank you so much for the fix. That's awesome! Yes, I upgraded to version 9.1.1 and no longer observe this issue. I'll close it accordingly.

As an FYI: I'm using it in https://github.com/RimuTec/Faker.

Thank you again and keep up the good work! Cheers, Manfred.

**Comment by ManfredLange** [comment]
BTW: Was the test I provided useful in resolving this issue? If not, how could I improve how I report issues?

**Comment by aaubry** [comment]
The test was definitely useful. It allowed me to quickly identify the commit where the bug was introduced with git bisect, then it was also useful to compare the behaviour before and after that change so that I could pinpoint exactly what triggered the bug.
Thanks a lot for taking the time to submit this code!

6 Jan 2021 22:47:56 Manfred <notifications@github.com>:
