### ISSUE TITLE
YamlDotNet.Core.SyntaxErrorException: While scanning a multi-line double-quoted scalar, found wrong indentation.'

### ISSUE THREAD

**Issue by JarLob** [aaubry/YamlDotNet#557]
Getting the exception on line continuation:
```yaml
key:
  key2: "line\
continues"
```
http://www.yamllint.com/ tells it is a valid yaml.

Debugged to https://github.com/aaubry/YamlDotNet/blob/d0b687d3a78f5eb1982e1552bd11c1a796557f87/YamlDotNet/Core/Scanner.cs#L1807 which looks wrong, but I'm not sure how to fix it because it breaks then other tests.

**Comment by aaubry** [comment]
I'm not sure what should be the correct behaviour in this case.
On one hand, many parsers seem happy with this YAML, but while others don't. Both [YAML:PP](https://metacpan.org/pod/YAML::PP) and the [reference parser implementation](http://hackage.haskell.org/package/YamlReference) complain about wrong indentation.
Also, the official test suite has a [test that expects an error in this case](https://github.com/yaml/yaml-test-suite/blob/master/test/QB6E.tml).
It is hard to understand what the [spec](https://yaml.org/spec/1.2/spec.html#style/flow/double-quoted) has to say about this, but in other multiline cases, each line needs at least as much indentation as the initial one. This helps keeping the document readable.

What do you think?

**Comment by JarLob** [comment]
I'm not sure how to read [the test](https://github.com/yaml/yaml-test-suite/blob/master/test/QB6E.tml), but I don't see a backslash there. I think the case when the last symbol on the line is a backslash is special, it tells to continue reading the next line as it is.

**Comment by JarLob** [comment]
But I'm not an expert in Yaml. I just wanted to say, it looks like the test doesn't cover the case of line continuation with a backslash. I also cannot find anything clear in the [spec](https://yaml.org/spec/1.2/spec.html#style/flow/double-quoted), just `Each continuation line must therefore contain at least one non-space character.`. Looks like a grey zone.

**Comment by aaubry** [comment]
You're right that the test doesn't have a backslash, my mistake. Still, the spec mentions that escaping the break character just prevents a line break from being inserted:
> It is also possible to escape the line break character. In this case, the line break is excluded from the content, and the trailing white space characters are preserved.

Regarding multiline double-quoted scalars, the [spec](https://yaml.org/spec/1.2/spec.html#id2787109) says that:
> In a multi-line double-quoted scalar, line breaks are are subject to flow line folding (...)

Reading the spec about [line folding](https://yaml.org/spec/1.2/spec.html#id2779048) doesn't provide much insight. The only part of the spec that seems relevant is where it discusses [indentation spaces](https://yaml.org/spec/1.2/spec.html#id2777534):
> A block style construct is terminated when encountering a line which is less indented than the construct.

Although double-quoted scalars are classified as "flow style" and the above applies to "block styles", if we interpret the multiline double-quoted scalar as a block, then the indentation is necessary on each line.

I agree that the spec is unclear on this topic, but given that the [reference parser](http://ben-kiki.org/ypaste/) treats it as an error, I think the current behaviour is the correct one.

**Comment by JarLob** [comment]
Ok, so I think there is no need to handle it in the default implementation.
Is there an easy way (like implement some interface) to customize YamlDotNet to handle these malformed continuations?

**Comment by aaubry** [comment]
Not really, the parser and scanner are not extensible and do not provide any way of recovering from errors. Maybe that would be a useful feature though, but would probably require a lot of work.

**Comment by JarLob** [comment]
Gotcha.  Thanks for taking a look!
