### ISSUE TITLE
C# 9.0 - Non-nullable properties with YamlDotNet

### ISSUE THREAD

**Issue by darkcharmander** [aaubry/YamlDotNet#564]
Hello,

C# 9.0 boasts a feature in which you can enable non-nullability for reference types by default.
Types that are deserialized by YamlDotNet, often never have intializers for their properties. VS spits out a warning about leaving them 'uninitialized'
`warning CS8618: Non-nullable property 'XXX' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. `

Obviously it is definitely going to be initialized by YamlDotNet. The C# compiler however, doesn't know this. Is there a way to get rid of this warning, without initializing the properties? I am afraid that just initializing them all for no reason, incurs a small performance penalty. It also doesn't make any sense to initialize them, and then have YamlDotNet overwrite them.

I performed a small benchmark, and there seems to be a small performance difference. I did **not** investigate the generated IL code.
Debug with initializers: 937msecs - 1019msecs
Debug without initializers: 868msecs - 961msecs
Release with initializers: 762msecs - 799msecs
Release without initializers: 756msecs - 776msecs

So, how did I test this? Well, here is a small sample:

```
class YamlTest
{
        public string Name { get; set; }
        public string[] Sources { get; set; }
        public string Destination { get; set; }
}
```

VS initializers

```
class YamlTest
{
        public string Name { get; set; } = string.Empty;
        public string[] Sources { get; set; } = new string[0];
        public string Destination { get; set; } = string.Empty;
}
```

and then to run it, something like this:

```
var text = [Your YAML file for this test]
var sw = new Stopwatch();
var elems = new List<YamlTest>(1024 * 20);

sw.Start();

for (int i = 0; i < 1024 * 20; ++i)
    elems.Add(yamlSerializer.Deserialize<YamlTest>(text));

sw.Stop();
Console.WriteLine("Time taken: " + sw.ElapsedMilliseconds);
Console.ReadKey();
```

**Comment by aaubry** [comment]
The correct solution would be to use a constructor, but YamlDotNet doesn't support that yet, although that is work in progress.
What I usually do is the following:
```c#
class YamlTest
{
        public string Name { get; set; } = default!;
        public string[] Sources { get; set; } = default!;
        public string Destination { get; set; } = default!;
}
```
This will prevent the compiler from complaining while making it explicit that you know that the properties should never be null. Of course if you create instances of this class through other means you lose the benefits of nullables.
You may want to add validation to ensure that all properties are indeed set. There is a [sample on one way of achieving that here](https://github.com/aaubry/YamlDotNet/wiki/Samples.ValidatingDuringDeserialization).

**Comment by darkcharmander** [comment]
Ah, I've never even heard about the null-forgiving operator!

It seems that your example with the 'default' keyword, also produces a bit less IL code. I think I'll do it like that, until there is a better way. Thanks.
