### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by aaubry** [aaubry/YamlDotNet#568]
**Describe the bug**
A clear and concise description of what the bug is. Please explain what you observe and what you expected to happen instead. If there is an exception, include its message and stack trace.

**To Reproduce**
Try to add the steps needed to reproduce the problem. Feel free to open a pull request with a failing test if that makes sense. Otherwise, at least provide some code and / or YAML that reproduce the issue.

```yaml
[1, 2
```

**Comment by yamldotnet** [comment]
> ```yaml
> [1, 2
> ```
**This YAML snippet appears to be invalid.**  
The following errors were identifier by the [reference parser](http://ben-kiki.org/ypaste/):
 - Line 3, char 1: Unexpected end of input
