### ISSUE TITLE
hypens and comments

### ISSUE THREAD

**Issue by jkears** [aaubry/YamlDotNet#581]
The YAML I need to produce has a parameter that includes a hypen such as **log-level: debug**.  How do I achieve this with C# class?  Is that using JSON name attribute? 

Also how can I inject comments for example  **# log-level configures the log level**

**Comment by leonard520** [comment]
I have same use case as @jkears . Is it already supported or not? Thanks.

**Comment by EdwardCooke** [comment]
Yes, you can use the `[YamlMember]` attribute to do both of these.

```csharp
using YamlDotNet.Serialization;

var serializer = new YamlDotNet.Serialization.SerializerBuilder().Build();
Console.WriteLine(serializer.Serialize(new Test() { LogLevel = "info" }));

class Test
{
    [YamlMember(Alias = "log-level", Description = "log-level configures the log level")]
    public string LogLevel { get; set; }
}
```

Results in this:

```yaml
# log-level configures the log level
log-level: info
```
