### ISSUE TITLE
Enums should allow EnumMemberAttribute

### ISSUE THREAD

**Issue by sebastianslutzky** [aaubry/YamlDotNet#586]
https://github.com/aaubry/YamlDotNet/blob/349d44a37896d1e6126459f5cdc9ca9f641f1c42/YamlDotNet/Serialization/Utilities/TypeConverter.cs#L157

I'm using v 8.0.0, target fx: 5netCoreApp 5.0

I have a hyphen in a yaml enum, that I cannot parse as it is an invalid c sharp enum member name.
I think it would be best to allow for EnumMember(Value = "with-hyphen") to be parsed
Using a custom serializer/validator for enums would be best maybe, but right now I have no control over that deserialization.

thanks
Sebastian

**Comment by MiYanni** [comment]
@sebastianslutzky

> I think it would be best to allow for EnumMember(Value = "with-hyphen") to be parsed

I did a solution for this issue here using a type converter: https://github.com/aaubry/YamlDotNet/issues/30#issuecomment-538604539

**Comment by EdwardCooke** [comment]
This will be in the next release.

**Comment by EdwardCooke** [comment]
It's released now.
