### ISSUE TITLE
IEnumerable<>.Empty does not serialise correctly

### ISSUE THREAD

**Issue by NeilMacMullen** [aaubry/YamlDotNet#588]
Firstly, thanks for the great library! 

```
   [TestMethod]
        public void SerialisingEmptyIEnumerableShouldNotGenerateFunnyCharacters()
        {
            new Serializer()
                .Serialize(new TestObject())
                .Should().Be(@"Models: []
Output: []
");
        }

        public class TestObject
        {
            public IEnumerable<string> Models { get; set; } = Enumerable.Empty<string>();
            public IEnumerable<string> Output { get; set; } = Enumerable.Empty<string>();
        }
```

This test fails:

```

Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Expected string to be 
"Models: []
Output: []
" with a length of 24, but 
"Models: &o0 []
Output: *o0
" has a length of 29, differs near "&o0" (index 8).
```
(yes the ampersand really is in the output)

Replacing the Enumerable.Empty with Array.Empty or changing the structure of the TestObject to avoid repeated IEnumerables seems to workaround the problem.

**Comment by taspeotis** [comment]
If you don't assign anchors you should get closer to your expected output. I don't know where it is on `Serializer` but if you're using `YamlStream` its `Save` method takes an `assignAnchors` boolean.

**Comment by NeilMacMullen** [comment]
@taspeotis  Thanks - I hadn't realised these were anchors but the behaviour makes a lot more sense with that in mind!

**Comment by taspeotis** [comment]
@NeilMacMullen No problems, I only encountered anchors myself yesterday. I was very confused.
