### ISSUE TITLE
Support language specific data tags like pyyaml-tags

### ISSUE THREAD

**Issue by QualityRobD** [aaubry/YamlDotNet#615]
**Is your feature request related to a problem? Please describe.**
Currently MKdocs uses yaml in a way that, when strictly interpretted, appears to not be [correct](https://yaml.org/spec/1.2/spec.html#id2784064). However MKdocs is pretty big and well established as a documentation tool. I don't see them making a big change like this, well ever.

MKDocs uses python specific data-tags in a differet way, referenced here: https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```

The mkdocs example above is the exact piece of yaml that YamlDotNet is complaining about in my case. This snipped is provided direclty by MKdocs. The problem lies when I try to deserialize the yaml using YamlDotNet. 

I'm not really sure how to proceed at this point. 

unless I am mistaken I think YamlDotNet is not properly handling language specific data tags like [pyyaml-tags](https://pypi.org/project/pyyaml-tags/#:~:text=PyYAML%2DTags%20is%20a%20library,simple%20decorators%20and%20meta%20API.)

or here: [yaml-tags](https://www.javatpoint.com/yaml-tags)

So in this case I am trying to validate a yaml file used for mkdocs, provided by mkdocs, which leverages language (python) specific tags. However, YamlDotNet is saying that the yaml is invalid.

**Describe the solution you'd like**
YamlDotNet should support language specific data-tags

**Describe alternatives you've considered**
None that I can think of

**Additional context**
### Screenshot taken from MKdocs documentation
![image](https://user-images.githubusercontent.com/17755173/119500448-d33f7600-bd35-11eb-8567-4269ee5a761d.png)

### Screenshot taken from yaml-tags
![image](https://user-images.githubusercontent.com/17755173/119507584-f588c200-bd3c-11eb-8c69-097654f937ad.png)

**Comment by aaubry** [comment]
What makes you think that YamlDotNet considers the file invalid? I tried loading the document with YamlStream without issues. Can you share the specific error that you encountered?

If you are using the deserializer, you need to register the tags like this:
```c#
var deserializer = new DeserializerBuilder()
	.WithTagMapping("tag:yaml.org,2002:python/name:materialx.emoji.twemoji", typeof(Twemoji))
	.WithTagMapping("tag:yaml.org,2002:python/name:materialx.emoji.to_svg", typeof(ToSvg))
	.Build();
```
You'll need to define the `Twemoji` and `ToSvg` types, or use other types that make sense in your application.

**Comment by QualityRobD** [comment]
Huh, interesting. I'm using YamlDotNet as a company-wide yaml parser to ensure folks are opening PRs with valid yaml. Having to register individual tags is a little unfortunate but when I get back online on Monday I'll check it out. I'll have to figure out a way to let each app (~2k apps) add tags on an ad-hoc basis as I won't want to introduce this type of coupling within the yaml validator tool.

**Comment by aaubry** [comment]
Given your use-case, it seems that it would be simpler to parse the YAML using `YamlStream`.
If you must use the deserializer, you could register a custom implementation of `INodeTypeResolver` that returns `typeof(object)` or something like that when any tag is encountered.

**Comment by QualityRobD** [comment]
@aaubry, I think I initially I was going to use the `YamlStream` but wanted to use the `IgnoreUnmatchedProperties` functionality in the `DeserializerBuilder`.

This is my current implementation, which runs agains all yaml files touched by PRs

```c#
var deserializer = new DeserializerBuilder()
    .IgnoreUnmatchedProperties()
    .Build();
deserializer.Deserialize<object>(fileData);
```

YamlDotNet has been supremely helpful in giving us rapid feedback on more than 99.9% of our yaml files, I'm just hoping to eliminate the noise, if possible, to the few outliers who utilize mkdocs.

to confirm, I tried this but was unable to find a way to essentially ignore duplicate keys.
```C#
var yamlFile = new StringReader(fileData);
var yaml = new YamlStream();
yaml.Load(yamlFile);
```

**Comment by QualityRobD** [comment]
To follow-up, the `YamlStream` does indeed work flawlessly for with my yaml file with those types of tags, if there is a way to ignore duplicate tags, we may be in business!

I'm not really sure how I would `type` the two mkdocs dags, for your recommendation with `WithTagMapping`

**Comment by aaubry** [comment]
YamlStream won't allow duplicate keys, unfortunately. This is something that will need to be improved.

I suggest that you register a custom `INodeTypeResolver` that resolves any tag to object. Something like this:

```c#
class MapTagsToObject : INodeTypeResolver
{
    public bool Resolve(NodeEvent? nodeEvent, ref Type currentType)
    {
        if (nodeEvent != null && !nodeEvent.Tag.IsEmpty)
        {
            currentType = typeof(object);
            return true;
        }
        return false;
    }
}

void Main()
{
    var deserializer = new DeserializerBuilder()
        .WithNodeTypeResolver(new MapTagsToObject())
        .Build();

    var yaml = @"markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg";


    var model = deserializer.Deserialize<object>(yaml);
    model.Dump();
}
```

The example you posted earlier parses fine in this way, and since you don't seem to need to do anything special with the tags, this should work for you.

**Comment by QualityRobD** [comment]
This did the trick, thank you so much!!
