### ISSUE TITLE
add a possibility to define the order of properties for serialization

### ISSUE THREAD

**Issue by dgorbach** [aaubry/YamlDotNet#62]
Using YamlDotNet in a WPF application with xaml databinding to an instance serialized/deserialized to/from yaml, I noticed that the order of the properties for serialization depends on the order of the controls bound to the correspondent property in the view.

The shape of the view affects the shape of the data. That’s weird.

I think this is because YamlDotNet uses reflection. (And xaml databinding uses reflection?) Reflection is caching its results and does not guarantee for the ordering. („The GetProperties method does not return properties in a particular order, such as alphabetical or declaration order.“).

I wrote a unit test to reproduce this behaviour and its effect on serialization:

``` C#
 public class A
{
    // todo: maybe introduce [YamlOrder(0)]
    public int P1 { get; set; }

    // todo: maybe introduce [YamlOrder(1)]
    public int P2 { get; set; }
}

[Fact]
public void SerializeTwice_CacheOfReflectionIsFilledDifferent_ResultIsSameForEachRun()
{
    var c = new A() { P1 = 1, P2 = 2 };

    var s = new Serializer();
    var b1 = new StringWriter();
    var b2 = new StringWriter();

    typeof(A).GetProperty("P2");  // get second property by Reflection

    s.Serialize(b1, c);

    GC.Collect();       
    GC.WaitForPendingFinalizers();

    typeof(A).GetProperty("P1");  // get first property by Reflection

    s.Serialize(b2, c);            

    var r1 = b1.ToString();
    var r2 = b2.ToString();

    Assert.Equal(r1, r2); // test fails with current YamlDotNet
} 
```

**Comment by nathan-alden** [comment]
Is there an improved way of accomplishing this in 2017?
