### ISSUE TITLE
[Question] Coerce types

### ISSUE THREAD

**Issue by chrisdrobison** [aaubry/YamlDotNet#632]
I'm working with a library that is expecting a specific generic structure. I'd like any dictionary to come out as a Dictionary<string, object> and any list to be either a List<string> or List<Dictionary<string, object>> depending on the context. Is there a good extension point for this? I've been looking at examples and I can get the dictionary where I want it, but the list is proving to be a lot harder. Any suggestions?

**Comment by EdwardCooke** [comment]
Per the yaml spec, there's no guarantee that the key to a value is going to be a string and there's no extension point to set the return type that I am aware of. You would need to build that resulting structure your self. Take a look here for recursively going through object returned by the non generic Deserialize method and pulling keys and values. It might give you a good starting point.

https://github.com/aaubry/YamlDotNet/issues/686#issuecomment-1181355821

If you have additional comments or questions, don't hesitate to re-open this issue. I'll help where I can.
