### ISSUE TITLE
Serializer: Need more control over how keys are emitted

### ISSUE THREAD

**Issue by fireflycons** [aaubry/YamlDotNet#644]
**Is your feature request related to a problem? Please describe.**
Whilst building a serializer for CloudFormation (yeah, that old cookie), I find that mapping keys are always emitted as unquoted strings. In a CF template some keys may be numeric, e.g. an AWS account ID as a key in the `Mappings` section of the template. CloudFormation insists that these keys are quoted.

Debugging through the code leads me to `Emitter.EmitBlockMappingKey`. I find that the scalar key to be emitted has the following properties
```
IsCanonical: false
IsPlainImplicit: true
IsQuotedImplict: false
Style: Any
```
...thus the mapping key is emitted without quotes.

If I put in the following hack, then the key is emitted with quotes

```csharp
            if (CheckSimpleKey())
            {
                states.Push(EmitterState.BlockMappingSimpleValue);

                if (evt is Scalar scalar && scalar.Value.All(char.IsDigit))
                {
                    evt = new Scalar(
                        scalar.Anchor,
                        scalar.Tag,
                        scalar.Value,
                        ScalarStyle.SingleQuoted,
                        scalar.IsPlainImplicit,
                        scalar.IsQuotedImplicit);

                }
                EmitNode(evt, true, true);
            }
```

**Describe the solution you'd like**
Some mechanism for setting up the behaviour of the emitter to be added to `SerializerBuilder` such that the strategy for emitting keys can be controlled. 

This could also provide at least some of the solution for https://github.com/aaubry/YamlDotNet/issues/591 since it could apply when a key has the string value `"null"`.

**Describe alternatives you've considered**
None. I see no way to achieve the required behaviour without direct code changes in YamlDotNet.

I may attempt a PR, but would like guidance on how you think a change like this might be implemented.

**Comment by PintTheDragon** [comment]
I would also love to have a way to force all strings to be quoted. In my case, YAML is used for configuration files, but the fact that not every string is quoted means that users who don't know YAML very well frequently put characters in unquoted strings that are only allowed in quoted strings.

**Comment by EdwardCooke** [comment]
I think this feature was added a few releases ago. Specify the default string quoting style on the serializerbuilder. If it’s still not working reopen this.
