### ISSUE TITLE
.netstandard 2

### ISSUE THREAD

**Issue by cphillips83** [aaubry/YamlDotNet#650]
Is it possible to get a `.netstandard2.0` version in the nuget package. When working with .net source generators the generator package needs to be `.netstandard2.0`. I simply have it pointing to 1.3 at the moment but it produces warnings.

**Comment by Hona** [comment]
I am trying the same thing. This would be a great change!

**Comment by EdwardCooke** [comment]
The next release will have .netstandard 2.0 built-in.
