### ISSUE TITLE
Convert YamlDotNet to a Portable Class Library

### ISSUE THREAD

**Issue by dsaf** [aaubry/YamlDotNet#66]
Would it be possible to convert YamlDotNet to a Portable Class Library and publish this version on NuGet? This will allow it to be used in cross-platform projects (Mono, Windows Store, Windows Phone).

http://msdn.microsoft.com/en-us/library/vstudio/gg597391(v=vs.100).aspx

Depending on how many non-portable types/methods used it could be as easy as installing VSCommands and using "Convert to Portable Library" context action.

I checked and it seems that YamlDotNet could be converted as easy as that. YamlDotNet.Dynamic would require changing minimum target platform to 4.5 afterwards in PCL project options.

**Comment by aaubry** [comment]
A portable version of YamlDotNet has been available in all recent builds for some time.
