### ISSUE TITLE
Are aliases supposed to be equal by value or by reference?

### ISSUE THREAD

**Issue by 0x0ade** [aaubry/YamlDotNet#660]
Apologies in advance if this question is misplaced here.

@WEGFan found a [possible problem in how we're using YamlDotNet in a project of ours](https://github.com/EverestAPI/Everest/pull/404), and it's unclear if it's a problem to begin with, or if I'm misunderstanding the docs.

[According to the documentation:](https://github.com/aaubry/YamlDotNet/wiki/Serialization.Serializer#disablealiases)

> When the same object appears multiple times in the serialized graph, the default behaviour is to emit it only once, assigning it an anchor, and use aliases to reference it on its subsequent occurrences. `DisableAliases` prevents this and causes the object to be emitted multiple times.

What does "same object" mean? Going by the current implementation, it's "equal by value", but judging by how anchors and aliases are supposed to help with circular references (at least from what I understand), I'd rather take it to mean "equal by reference". This is causing a bit of a headache for us right now as objects are being "merged" when round-tripping, most easily seen with `record`s. Should two equal `record`s exist which do not refer to the same object, both now do after deserialization. And we'd want to disable that merging behavior without risking reused references causing problems.

@WEGFan found that the [`AnchorAssigner` is using a dictionary under the hood](https://github.com/aaubry/YamlDotNet/blob/41e334c7f14eec1458c3926a576b09df3699ed2c/YamlDotNet/Serialization/ObjectGraphVisitors/AnchorAssigner.cs#L36). Should it be using an equality comparer that uses `ReferenceEquals`? Or is the default behavior checking `Equals` and `GetHashCode` intended for aliases?

**Comment by EdwardCooke** [comment]
After digging in the code it doesn't do anything special to the objects it uses as a key in the underlying dictionary. So, with that, it would use what the dictionary uses which I believe is `Equals` and `GetHashCode` to compare the objects and not by reference. 
Hopefully that helps.

If you need more help on the internals of YamlDotNet, I'm here to help, reopen the issue with any additional comments.
