### ISSUE TITLE
Serialized block comments are not correctly indented right after a block starts

### ISSUE THREAD

**Issue by krisrok** [aaubry/YamlDotNet#662]
**Describe the bug**
Here's what's expected:
```
Person:
  # The person's name
  Name: Paul
  # The person's age
  Age: 50
```

The current implementation yields:
```
Person:
# The person's name
  Name: Paul
  # The person's age
  Age: 50
```

**To Reproduce**
Serialize any class with a reference type having a comment (using `YamlMemberAttribute`) on its first property.

**Comment by EdwardCooke** [comment]
The PR fixing this was merged. Closing this.
