### ISSUE TITLE
Roundtripping empty reference in flow mapping fails

### ISSUE THREAD

**Issue by krisrok** [aaubry/YamlDotNet#666]
**Describe the bug**
Essentially, when serializing a null reference inside of a flow mapping its value gets translated to `""`. This in turn cannot be deserialized back to a given type, throwing an `InvalidCastException`. 

So `{Foo: ""}` cannot be deserialized into a class `class Bar { public Bar Foo }`.
Instead `{Foo: }` (without the empty quotes) get deserialized just fine.

I don't know if that should be tackled inside the serialization or deserialization part, neither my YAML- nor my YamlDotNet-knowledge is sufficient.

**To Reproduce**
I've added a quick test to demonstrate the behaviour: https://github.com/krisrok/YamlDotNet/commit/4a84500b45c5b0be212f9a82dd6909b97287d987

**Comment by EdwardCooke** [comment]
Thank you for the test cases. I'll start work on fixing this.

**Comment by EdwardCooke** [comment]
I just looked at this, it doesn't seem to be a problem any more. I used your test case, with the flow emitter it failed with what you showed. Without it, it worked fine. I used the following test case:

```csharp
        [Fact]
        public void RoundtripEmptyReferenceWithFlowMapping()
        {
            var serializer = new SerializerBuilder()
                .Build();

            var deserializer = new DeserializerBuilder()
                .Build();

            var yaml = serializer.Serialize(new RoundtripClass());
            var deserialized = deserializer.Deserialize<RoundtripClass>(yaml);
            deserialized.Should().NotBeNull();
            deserialized.Foo.Should().BeNull();
        }
```

I'm closing this issue as the problem lies in an emitter created outside of yamldotnet.
