### ISSUE TITLE
Float gets converted incorrectly. Am I missing something?

### ISSUE THREAD

**Issue by xavier-hernandez** [aaubry/YamlDotNet#671]
var json = @"{
                'Name':'Peter',
                'Height':1.4,
                'CourseDet':{
                        'CourseName':'CS',
                        'CourseDescription':'Computer Science',
                        },
                'Subjects':['Computer Languages','Operating Systems']
                }";

            dynamic deserializedObject = JsonConvert.DeserializeObject<ExpandoObject>(json);
            var serializer2 = new YamlDotNet.Serialization.Serializer();
            string yaml2 = serializer2.Serialize(deserializedObject);

**Result**

Name: Peter
Height: 1.3999999999999999
CourseDet:
  CourseName: CS
  CourseDescription: Computer Science
Subjects:
- Computer Languages
- Operating Systems

**Comment by sapvissers** [comment]
I was looking into this the other day when someone pointed out to me you can do the following:

```
private readonly Newtonsoft.Json.JsonSerializerSettings _defaultJsonSerializerSettings = new () 
{
   FloatParseHandling = FloatParseHandling.Decimal 
};
..........
dynamic? jsonObject = JsonConvert.DeserializeObject<ExpandoObject>(json, _defaultJsonSerializerSettings );
```

This will fix your issue.

**Comment by xavier-hernandez** [comment]
That worked. Thank you!
