### ISSUE TITLE
How to get type converters when using `WithPreProcessingPhaseObjectGraphVisitor`

### ISSUE THREAD

**Issue by WEGFan** [aaubry/YamlDotNet#677]
I'm currently trying to solve #660 in our project, by duplicating `AnchorAssigner` and replacing `assignments` dictionary definition to a compare by reference one. However, when I'm building the serializer, I found that `WithPreProcessingPhaseObjectGraphVisitor()` doesn't take a `Func` type as the parameter, so I need to instantiate my own `ReferenceEqualAnchorAssigner` but I don't know how can I get type converters.

So I would like to know is there a way to get a list of type converters?

My code is

```cs
new SerializerBuilder()
    .ConfigureDefaultValuesHandling(DefaultValuesHandling.Preserve)
    // expecting something `like typeConverters => new ReferenceEqualAnchorAssigner(typeConverters)` for the first argument
    .WithPreProcessingPhaseObjectGraphVisitor(new ReferenceEqualAnchorAssigner( ??? ), w => w.InsteadOf<AnchorAssigner>())
    .WithEmissionPhaseObjectGraphVisitor(args => new AnchorAssigningObjectGraphVisitor(args.InnerVisitor, args.EventEmitter, args.GetPreProcessingPhaseObjectGraphVisitor<ReferenceEqualAnchorAssigner>()),
        w => w.InsteadOf<AnchorAssigningObjectGraphVisitor>())
    .Build();
```

and `ReferenceEqualAnchorAssigner` is the same as `AnchorAssigner` except `assignments`:

```cs
public sealed class ReferenceEqualAnchorAssigner : PreProcessingPhaseObjectGraphVisitorSkeleton, IAliasProvider {
    private readonly IDictionary<object, AnchorAssignment> assignments = new Dictionary<object, AnchorAssignment>(ReferenceEqualityComparer.Instance);
    ...
}
```

**Comment by EdwardCooke** [comment]
There are 3 pre-built type converters, the `DateTimeConverter`, `GuidConverter` and `SystemTypeConverter`. They are in the `YamlDotNet.Serialization.Converters` namespace. In the serializer/deserializer builder base class, only GuidConverter and SystemTypeConverter are registered. I do see a way to remove type converters, but not add. You can see the code where it adds the type converters here:

https://github.com/aaubry/YamlDotNet/blob/38b6ff5f839efc19de1774e243e4becb418bfddb/YamlDotNet/Serialization/BuilderSkeleton.cs#L49-L53

I hope this helps.
