### ISSUE TITLE
How to skip the failed property automatically whitout exception when deserializing?

### ISSUE THREAD

**Issue by emako** [aaubry/YamlDotNet#680]
Feel free to ask any question on how to use the library. Alternatively, consider asking the question on [Stackoverflow](https://stackoverflow.com), tagged with [yamldotnet](https://stackoverflow.com/questions/tagged/yamldotnet).

---

Is there any scheme to automatically skip the property of the exception when deserializing?

Such as:

`config.yaml`:

```yaml
first: something1 
second: something2 
third: something3
```

`Config.cs`:

```c#
public class Config
{
    public string first { get; set; }
    public string second { get; set; }
}
```

Because `third` is not in the class, deserialization will fail and an exception will be thrown.

How can it skip the `third` property automatically and continute the deserialization whitout exception.

The purpose is to construct Config class entities as much as possible.

---

I know `YamlDotNet.Dynamic` or `RepresentationModel` can do it, but it's manual, not automatic.

**Comment by EdwardCooke** [comment]
On the `DeserializerBuilder` call `IgnoreUnmatchedProperties`. That worked when I just tested it.

```csharp
var deserializer = new DeserializerBuilder().IgnoreUnmatchedProperties().Build();
var yaml = @"
first: something1 
second: something2 
third: something3
";

var config = deserializer.Deserialize<Config>(yaml);
class Config
{
    public string first { get; set; }
    public string second { get; set; }
}
```

**Comment by EdwardCooke** [comment]
Re open if you need further help.
