### ISSUE TITLE
Deserialize fails for keys with newline

### ISSUE THREAD

**Issue by JKostov** [aaubry/YamlDotNet#684]
When using a complex key, that has newline char the serialization is successful but deserialization fails.

YAML example:
```yaml
? >-
  key

  a

  b
: >-
  value

  a

  b

```

Code:
```c#
using YamlDotNet.Serialization;

var serializer = new SerializerBuilder().Build();
var deserializer = new DeserializerBuilder().Build();

var data = new Dictionary<string, string>();
data.Add("key\na\nb", "value\na\nb");

var serialized = serializer.Serialize(data);

var deserialized = deserializer.Deserialize<Dictionary<string, string>>(serialized);

```

The version of the `YamlDotNet` package that I'm using is `11.2.1`.

Exception:

```
(Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): Exception during deserialization -> Value cannot be null. (Parameter 'key')
```

**Comment by EdwardCooke** [comment]
I'm going to see if this is even valid yaml, It still throws in the latest code, however the following works:

```yaml
? >-
  key

  a

  b: >-
  value

  a

  b
```

Notice where the `:`, on the same line as `b`. I'll let you know what I find out.

**Comment by EdwardCooke** [comment]
K, it is valid, digging in to the code to determine why it's failing.

**Comment by EdwardCooke** [comment]
This fix will go out in the next release.
