### ISSUE TITLE
Signed dlls required

### ISSUE THREAD

**Issue by abebube** [aaubry/YamlDotNet#687]
My team uses this package to convert c# objects to yaml.

However, we need a signed version of YamlDotNet.dll.
The nuget package is signed but the actual dll isn't signed, and this is triggering violations on our end.

Could we have this update?

**Comment by aaubry** [comment]
Which version are you using? I've checked the latest package and all the libraries are signed.

![image](https://user-images.githubusercontent.com/630495/165974247-d893c797-bec3-4d34-a93f-52329ccac7e1.png)

Notice that the key used to sign these packages is public, which means that anyone can produce a modified version of the library and sign it. This signature is just a convenience for users requiring a strong named assembly.

**Comment by aaubry** [comment]
The only signature that is provided is the .NET assembly signature, which is the standard practice in the .NET world, as far as I can tell. I suggest that you setup your own CI pipeline to sign the dlls yourself. The build should be easy to replicate. You can base yourself on [appveyor.yml](https://github.com/aaubry/YamlDotNet/blob/master/appveyor.yml).
