### ISSUE TITLE
This project is on hold

### ISSUE THREAD

**Issue by aaubry** [aaubry/YamlDotNet#690]
[See this discussion](https://github.com/aaubry/YamlDotNet/discussions/689). I'm referencing all currently open pull requests and issues so that they are notified.

Pull requests:
#674 #664 #661 #659 #654 #653 #636 #634 #631 #630 #585 #532 #486 #479 #468 #464 #462 #362 #306 #239 #238 #119

Issues:
#687 #686 #684 #681 #680 #679 #678 #677 #675 #674 #673 #672 #670 #669 #666 #665 #664 #663 #662 #661 #660 #659 #658 #656 #655 #654 #653 #650 #644 #643 #640 #638 #637 #636 #634 #632 #631 #630 #629 #627 #625 #611 #607 #606 #605 #593 #591 #590 #587 #586 #585 #581 #580 #575 #574 #573 #571 #570 #567 #560 #556 #551 #549 #547 #541 #538 #537 #536 #535 #534 #532 #531 #530 #528 #526 #523 #521 #520 #519 #518 #517 #514 #513 #511 #510 #508 #505 #499 #498 #496 #495 #494 #493 #487 #486 #484 #479 #478 #473 #471 #468 #464 #463 #462 #461 #459 #458 #455 #454 #453 #451 #449 #446 #445 #443 #440 #430 #429 #409 #408 #399 #394 #393 #387 #384 #383 #381 #379 #378 #375 #372 #370 #362 #360 #358 #343 #341 #339 #333 #311 #306 #304 #291 #282 #274 #271 #269 #265 #264 #248 #245 #241 #239 #238 #236 #233 #209 #207 #168 #167 #156 #153 #130 #119 #33 #9

**Comment by jamietwells** [comment]
What does it mean "on hold"? There hasn't been a release for about a year, even though bug fixes have gone in - are you planning on releasing a new version with the fixes included?

**Comment by aaubry** [comment]
I'm blocking comments on this issue because it is intended just to mention the currently open issues and pull requests. If you whish to comment on this topic, [please do so in this discussion](https://github.com/aaubry/YamlDotNet/discussions/689).

**Comment by EdwardCooke** [comment]
We now have maintainers for this project. I’m closing this to help avoid confusion.
