### ISSUE TITLE
Why does YamlIgnore attribute get ignored when property is decorated on an interface

### ISSUE THREAD

**Issue by FakeMan2332** [aaubry/YamlDotNet#715]
**Describe the bug**
I'm assigned `[YamlIgnore]` attribute to my property in interface, then inherit them to my struct.
By unknown reason, attribute was ignored, and property was included to my YAML file. 

**To Reproduce**

1. Create interface
2. Create property in interface
3. Assign `[YamlIgnore]` attribute to this property
4. Create class
5. Inherit created interface
6. Implement interface property
7. Serialize created class

YamlDotNet version: `12.0.0`

**Comment by RunicLib** [comment]
![image](https://user-images.githubusercontent.com/72656712/185814807-716ba08d-2a1e-4498-a3e5-124a747b4a23.png)
![image](https://user-images.githubusercontent.com/72656712/185814828-868b4e82-1abe-491b-9905-8fb59d8e857c.png)
![image](https://user-images.githubusercontent.com/72656712/185814834-060e83aa-1e5e-4dc1-acf5-df47526bfd60.png)

**Comment by EdwardCooke** [comment]
This one took a little bit to figure out, but it's a dot net limitation. Attributes on interfaces are not inherited on the implementing class. We *could* add some custom logic and an opt-in feature flag that would look at implemented interfaces for that property, I don't think we really want to do that, for pretty much the same reason that Microsoft doesn't want to implement it in dot net core. What if one interface needs to expose that property, but another one doesn't. Which one wins that battle?

https://docs.microsoft.com/en-us/dotnet/api/system.attributeusageattribute.inherited?view=net-6.0
https://stackoverflow.com/questions/12106566/attribute-on-interface-members-does-not-work

One possible solution to this, is to change your interface into either an abstract or inherited class, like this:

```csharp
public abstract class IConfig
{
    [YamlIgnore]
    public abstract string Filename { get; }
}

public class MainConfiguration : IConfig
{
    public override string Filename => "bot_config.yml";
    public string BotToken { get; set; }
    public string BotPrefix { get; set; }
}
```

Which works as expected.
```yaml
BotToken:
BotPrefix:
```

**Comment by FakeMan2332** [comment]
Okay, thank you!
