### ISSUE TITLE
YamlDotNet.Core in Web Essentials plugin

### ISSUE THREAD

**Issue by am11** [aaubry/YamlDotNet#72]
Can you help us hooking up your Yaml AST and implementing syntax highlighting in [Web Essentials](https://github.com/madskristensen/WebEssentials2013).

Related issue on WE2013: https://github.com/madskristensen/WebEssentials2013/issues/148

**Comment by aaubry** [comment]
The YamlDotNetEditor addin has been moved to its own repository here - https://github.com/aaubry/YamlDotNet.Editor
Further discussion, if necessary, should occur there.
