### ISSUE TITLE
String starting with tab and comma is incorrectly serialized leading to SemanticErrorException when that yaml is deserialized

### ISSUE THREAD

**Issue by gb6sthingz** [aaubry/YamlDotNet#732]
The following code is the full code to reproduce the bug. (Its commented.)

var serializer = new SerializerBuilder().Build();
var yaml = serializer.Serialize(new List<string>() { "\t," }); // Fails to decorate the yaml string, which causes the exception when deserializing - see below
var deserializer = new DeserializerBuilder().Build();
deserializer.Deserialize<List<string>>(yaml); // SemanticErrorException : (Line: 1, Col: 4, Idx: 3) - (Line: 1, Col: 5, Idx: 4): While parsing a node, did not find expected node 

Project settings
C#
<TargetFramework>net6.0-windows10.0.22000.0</TargetFramework>
<PackageReference Include="YamlDotNet" Version="12.0.2" />

Thanks

**Comment by EdwardCooke** [comment]
Thank you for the bug report. I'll take a look at it in the next few days. I suspect it's in the node serializer and it's not quoting strings that start with whitespace, it'd be interesting to know if `" ,"` also throws an error or is incorrect when deserializing. I suspect it will be missing the leading space.

**Comment by EdwardCooke** [comment]
I bet if we modify this regex to include a whitespace check at the beginning of the string it would fix it.

https://github.com/aaubry/YamlDotNet/blob/02685df84cb2e0b81f327e890968267e4b60e0f0/YamlDotNet/Serialization/EventEmitters/TypeAssigningEventEmitter.cs#L35

After doing that, it would work by calling withquotenecessarystrings on the serializer builder. It'll be a few days before I can test this out and get a fix in though.

**Comment by oxygen-dioxide** [comment]
This bug also happens to me. After I serialize an object with "\t- a" string, I can't deserialize the yaml. See https://github.com/stakira/OpenUtau/issues/1040

**Comment by EdwardCooke** [comment]
As soon as the next release goes out (in about 10-15 minutes), this will be fixed. You'll need to make sure to include the `.WithQuotingNecessaryStrings()` is called on your `SerializerBuilder`.

**Comment by aaubry** [comment]
A fix for this issue has been released in [version 15.1.2](https://github.com/aaubry/YamlDotNet/releases/tag/v15.1.2).
