### ISSUE TITLE
Default values of record structs aren't respected in deserialization

### ISSUE THREAD

**Issue by BlueStaggo** [aaubry/YamlDotNet#733]
**Describe the bug**
YamlDotNet ignores the default values of properties in `record struct`s when deserializing.

**To Reproduce**
Here is some simple reproduction code, using .NET 6 and YamlDotNet 12.0.2:
```cs
using System;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

public class Program
{
    public struct Person
    {
        public string Name;
        public int Age = 18;
    }
    
    public record struct PersonRecord
    (
        string Name,
        int Age = 18
    );
    
    public static void Main()
    {
        var input = @"
name: John
";
        
        var deserializer = new DeserializerBuilder().WithNamingConvention(CamelCaseNamingConvention.Instance).Build();
        var person = deserializer.Deserialize<PersonRecord>(input);
        Console.WriteLine($"{person.Name} is {person.Age} years old.");
    }
}
```
Note that the YAML has a "name" property but not an "age" property, which is set by default in both a struct called `Person` and a record struct called `PersonRecord`. When the YAML is deserialized to a `Person`, the output is `John is 18 years old.`. When the YAML is deserialized to a `PersonRecord`, the output is instead `John is 0 years old.`.

**Comment by edwardcookemacu** [comment]
Field initializers in structs don't run when the struct is instantiated, which is why it is the default value of 0 and not what you expect.

Even if you did a `var x = new PersonRecord()` it is also 0.

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/parameterless-struct-constructors#instance-field-initializers

**Comment by BlueStaggo** [comment]
Just did some testing and I guess this issue is a result of C# design. I since converted all the record structs in my project to classes or regular structs.
