### ISSUE TITLE
Is there any support for $ref in YAML spec to external files?

### ISSUE THREAD

**Issue by dpwdec** [aaubry/YamlDotNet#734]
I've seen that there is [this issue](https://github.com/aaubry/YamlDotNet/issues/357) from four years ago, however the code link at the bottom is broken.

Is it the case that the functionality of directly deserializing YAML files like...
```yaml
SomeProperty:
  $ref: ./another_file.yaml
```

```yaml
# another_file.yaml
AnotherProperty: some text
```

... with corresponding C# models...
```csharp
class SomeModel
{
  AnotherModel SomeProperty { get; set; }
}

class AnotherModel
{
  string AnotherProperty { get; set; }
}
```

...is still not supported?

If some is there a way to accomplish this that doesn't involve rewriting the input YAML files?

**Comment by EdwardCooke** [comment]
If I recall correctly that is not in the official yaml spec which we strive to follow. I’ll try and double check that tonight, but if it’s not in the spec we’ll probably not implement that feature in this library. There could be the potential of creating some kind of extension library in the future.

**Comment by perlpunk** [comment]
To confirm: There's no such feature in the YAML spec.

**Comment by EdwardCooke** [comment]
I’m closing this issue since it’s not in the official spec.
