### ISSUE TITLE
Scanner parse a multiple line text will consume the white spaces before the real line break

### ISSUE THREAD

**Issue by muguangyi** [aaubry/YamlDotNet#745]
**Describe the bug**
`Scanner.ScanFlowScalar` will consume the white spaces before the real line break and cause the parsed text is incorrect.

**To Reproduce**
```
%YAML 1.1
m_text: "abcdefg\n   
    -abcdefg\n   
    -abc"
```
NOTE: every "\n" in text follows 3 white spaces. The correct text value should be 'abcdefg\n**space** **space** **space** **space**-abcdefg\n**space** **space** **space** **space**-abc', but the actual result is 'abcdefg\n**space**-abcdefg\n**space**-abc'. Only one white space is left.

I would suggest making a fix as follows:

```csharp
private Token ScanFlowScalar(bool isSingleQuoted)
{
  ...
  while (analyzer.IsWhite() || analyzer.IsBreak())
  {
    ...
    if (!hasLeadingBlanks)
    {
      // Need to append the current whitespaces into value before clean.
      value.Append(whitespaces.ToString());

      whitespaces.Length = 0;
      leadingBreak.Append(ReadLine());
      hasLeadingBlanks = true;
    }
    else
    {
      trailingBreaks.Append(ReadLine());
    }
    ...
  }
}
```

**Comment by yamldotnet** [comment]
> ```yaml
> %YAML 1.1
> text: "abcdefg\n   
>     -abcdefg\n   
>     -abc
> "
> ```
**This YAML snippet appears to be invalid.**  
The following errors were identifier by the [reference parser](http://ben-kiki.org/ypaste/):
 - Line 2, char 1: Unexpected 't'

**Comment by yamldotnet** [comment]
> ```yaml
> %YAML 1.1
> text: "abcdefg\n   
>     -abcdefg\n   
>     -abc
> "
> ```
**This YAML snippet appears to be invalid.**  
The following errors were identifier by the [reference parser](http://ben-kiki.org/ypaste/):
 - Line 2, char 1: Unexpected 't'

**Comment by yamldotnet** [comment]
> ```yaml
> %YAML 1.1
> text: "abcdefg\n   
>     -abcdefg\n   
>     -abc
> "
> ```
**This YAML snippet appears to be invalid.**  
The following errors were identifier by the [reference parser](http://ben-kiki.org/ypaste/):
 - Line 2, char 1: Unexpected 't'

**Comment by yamldotnet** [comment]
> ```yaml
> %YAML 1.1
> text: "abcdefg\n   
>     -abcdefg\n   
>     -abc"
> ```
**This YAML snippet appears to be invalid.**  
The following errors were identifier by the [reference parser](http://ben-kiki.org/ypaste/):
 - Line 2, char 1: Unexpected 't'

**Comment by yamldotnet** [comment]
> ```yaml
> %YAML 1.1
> m_text: "abcdefg\n   
>     -abcdefg\n   
>     -abc"
> ```
**This YAML snippet appears to be invalid.**  
The following errors were identifier by the [reference parser](http://ben-kiki.org/ypaste/):
 - Line 2, char 1: Unexpected 'm'

**Comment by perlpunk** [comment]
The result is correct because multiple spaces are folded in flow scalars:
https://www.yaml.info/learn/quote.html#flow
If you want to keep the spaces, at a backslash at the end of the line (works only in double quoted scalars).

**Comment by EdwardCooke** [comment]
Since this is not an issue and working according to the spec, I'm going to close this.
