### ISSUE TITLE
Manually override NewLine character?

### ISSUE THREAD

**Issue by polterguy** [aaubry/YamlDotNet#746]
Can I override what newline character(s) the library is generating as it is creating YAML? I have the following code.

```csharp
// Converting to JSON object.
var expConverter = new ExpandoObjectConverter();
dynamic deserializedObject = JsonConvert.DeserializeObject<ExpandoObject>(someJsonStringHere, expConverter);

// Converting to YAML.
var serializer = new SerializerBuilder().Build();
var yaml = serializer.Serialize(deserializedObject);
```

I want the library to _always_ output `CR/LF`, regardless of what operating system I am on. Is this possible?

**Comment by EdwardCooke** [comment]
Right now, no. It shouldn’t be hard to implement though. We’re always willing to accept pull requests with bug fixes and additional features. If I get time I can also work on it.

**Comment by polterguy** [comment]
Let me know if it's acceptable. When you create a release with this, do you mind just commenting here to let me know? I kind of need this feature in our own stuff ...

**Comment by EdwardCooke** [comment]
I’ll take a look at it later today or tonight.

**Comment by polterguy** [comment]
Thx

**Comment by EdwardCooke** [comment]
Got the build started again, just a 403 error to work though. I think the token is expired for talking to github, which I can't fix. @aaubry  will need to do that.

**Comment by aaubry** [comment]
I'll have a look later.

**Comment by EdwardCooke** [comment]
I'm going to close this since the PR is released.
