### ISSUE TITLE
Version 12.1.0 not available

### ISSUE THREAD

**Issue by Chaosflo** [aaubry/YamlDotNet#751]
**Describe the bug**
As I wanted to test the newline configuration feature, I noticed that the new version is missing in the nuget.org

![image](https://user-images.githubusercontent.com/13841355/205603813-60a57cbc-c9d0-4b23-b9de-03d455b06b6c.png)

I noticed too that the build fails

**To Reproduce**
Simply go on [nuget site](https://www.nuget.org/packages/YamlDotNet#versions-body-tab) of the package.

**Comment by aaubry** [comment]
It's fixed now. The package wasn't published correctly because we had a bug in the build script which required some manual intervention and caused the release to be created in a non-standard way. This shouldn't happen anymore.
