### ISSUE TITLE
Values starting with `-` but otherwise being string are treated like a key start

### ISSUE THREAD

**Issue by konrad-kruczynski** [aaubry/YamlDotNet#757]
**Describe the bug**
Please just see the example below as it tells everything.

**To Reproduce**
```csharp
using YamlDotNet.Serialization;

var input = @"
Value: -[123]
";

var deserializer = new Deserializer();
deserializer.Deserialize(new StringReader(input));
```
Running this leads to an exception (Invalid key indicator format), while this should be simply deserialized to a string. It worked properly on YamlDotNet 8.0.0.

**Comment by EdwardCooke** [comment]
I believe that yaml is actually invalid. Plain scalars are not allowed to have braces in them. Version 8 is really old and may have been less strict about what is in the scalars. I’ll double check the other serializers out there to be sure in a little bit though. 

https://yaml.org/spec/1.1/#id907281

**Comment by aaubry** [comment]
This actually parses correctly on the reference implementation, so I think it is valid:
http://ben-kiki.org/ypaste/data/62185/index.html

**Comment by konrad-kruczynski** [comment]
I've tried a few YAML linters before issuing this bug report and it passed on all of them.

**Comment by EdwardCooke** [comment]
Thanks for saving me some time :) I’ll take a look in the next few days hopefully, I have another big task I’m working on. If you want to take a stab at it, it’s probably in the parser where it checks for the -.

**Comment by konrad-kruczynski** [comment]
Great, can I expect a release soon?

**Comment by konrad-kruczynski** [comment]
Or maybe it's already been released, since there is a new version from yesterday (12.2.1)? In that case it doesn't solve the problem, only the error message is a bit different.

**Comment by EdwardCooke** [comment]
Yes. It’ll be released soon.
