### ISSUE TITLE
Validate an unknown YAML string 

### ISSUE THREAD

**Issue by mirsahibmovsumov** [aaubry/YamlDotNet#762]
I didn't find out a way to validate an unknown YAML string in c#

It would be nice to have an `.Validate()` method to verify that the current string is in YAML format.

**Comment by EdwardCooke** [comment]
What you could do is use the deserialerbuilder to build a deserializer and parse it that way, just ignore the resulting object. If it doesn’t throw a yamlexception it’s valid.
