### ISSUE TITLE
Is there a way to make enumerated values use an alias the way that members do?

### ISSUE THREAD

**Issue by jmo-gelsight** [aaubry/YamlDotNet#766]
When I serialize the following enumerated values to Xml, my usage of the XmlEnum attribute makes the serializer write my preferred lowercase names for each of the enum values

```
public enum LengthUnit
{
    [XmlEnum(Name="??")] None,
    [XmlEnum(Name="nm")] NM, // Nanometers
    [XmlEnum(Name="um")] UM, // Microns
    [XmlEnum(Name="mm")] MM, // Millimeters
    [XmlEnum(Name="cm")] CM, // Centimeters
}
```

I cannot find a way to do this with YamlDotNet attributes. 

Naturally I tried applying the `YamlMember` attribute with the `Alias` property as shown below but it had no effect.  My enum values are still written out in capital letters

Is there a way to do this that I am missing?  

```
public enum LengthUnit
{
    [YamlMember(Alias="none")][XmlEnum(Name="??")] None,
    [YamlMember(Alias="nm")][XmlEnum(Name="nm")] NM, // Nanometers
    [YamlMember(Alias="um")][XmlEnum(Name="um")] UM, // Microns
    [YamlMember(Alias="mm")][XmlEnum(Name="mm")] MM, // Millimeters
    [YamlMember(Alias="cm")][XmlEnum(Name="cm")] CM, // Centimeters
}
```

**Comment by EdwardCooke** [comment]
You might be able to use a custom type converter for it.

**Comment by jmo-gelsight** [comment]
OK, great I could do that.  I just wanted to make sure there wasn't some other attribute or something I should be using.

**Comment by EdwardCooke** [comment]
I'm pretty sure there isn't out of the box. Would be a neat thing to add though. If you would like to create add that feature and create a PR that would be great.

**Comment by EdwardCooke** [comment]
Since there is a way of doing it with a custom yaml converter I’m going to close this issue.
