### ISSUE TITLE
MergingParser cannot parse yaml with array alias that contains list

### ISSUE THREAD

**Issue by hemnstill** [aaubry/YamlDotNet#777]
This yaml cannot be parsed by `MergingParser`:

``` 
common_config: &base
    tenant:
    -   '@name': 'tenant1'

WebServer: &WebServer
    <<: [*base] <- its working without square brackets

WebClient:
    <<: *WebServer
```

```
    var mergingParser = new MergingParser(new Parser(new StringReader(yamlContent)));
    new DeserializerBuilder().Build().Deserialize(mergingParser);
```

No node deserializer was able to deserialize the node into type System.Object

(https://dotnetfiddle.net/agEHtz)

Affected versions: any - 13.0.0

**Comment by EdwardCooke** [comment]
I’ll take a look when I get some time. It might be a little bit. If you need a fix sooner we’re always happy to accept pull requests.

**Comment by hemnstill** [comment]
This yaml cannot be parsed by MergingParser v13.0.1:

```
common_config: &base
    tenant:
    -   '@name': 'tenant1'
    -   '@name': 'tenant2'

WebServer: &WebServer
    <<: [*base]

WebClient:
    <<: *WebServer
```

I made a mistake with the fix

**Comment by EdwardCooke** [comment]
Can you put up a pr with the fix for that?

**Comment by hemnstill** [comment]
I need a little more time

**Comment by hemnstill** [comment]
I hope I fixed it this time (try2)
