### ISSUE TITLE
Could you please think about offering a `CaseInsensitiveNamingConvention`?

### ISSUE THREAD

**Issue by schittli** [aaubry/YamlDotNet#781]
Hello

**thank you very much for sharing your great work!**
I use YamDotNet for non-profit projects and it's great to have your library.

### Is your feature request related to a problem? Please describe.

Our technically quite skilled users can edit the yaml files directly.
By far the most common mistakes they make are in the capitalization of property names.
Therefore, they either need support to fix the issue or we have to program the application fault-tolerant.
But because the property names are 99% correct and only the case is wrong, there is a much more elegant solution… 

### Describe the solution you'd like

It would be very helpful if you could provide this `INamingConvention` provider: `CaseInsensitiveNamingConvention`
This would allow us to easily make YamlDotNet more fault tolerant 😊

### Describe alternatives you've considered
Of course, any application you could somehow handle these errors itself.

**But if the application is allowed to be fault tolerant with the configuration files**, 
then something like a `CaseInsensitiveNamingConvention` would be a very elegant solution.

Thanks a lot, kind regards,
Thomas

**Comment by EdwardCooke** [comment]
You’ll see this feature in the next release.

**Comment by EdwardCooke** [comment]
This is released
