### ISSUE TITLE
Properties getting serialized.

### ISSUE THREAD

**Issue by SpaceDandy-Tama** [aaubry/YamlDotNet#790]
```
    public struct Moon
    {
        public string Name;
        public int MeanDiameter;
        public int MeanTemperature;
        public Coordinates Coordinates => Planet.Coordinates;
        public Planet Planet;
    }
```

Coordinates property of this struct gets serialized. And since [System.NonSerialized] is not valid on Properties of any kind, I'm completely stuck.

Is it possible to configure the builder to build a Serializer that completely omits Properties?

Using [YamlIgnore] isn't possible or preferable.

**Comment by EdwardCooke** [comment]
You can put the YamlIgnore attribute on your properties and they won’t be serialized.

**Comment by SpaceDandy-Tama** [comment]
> You can put the YamlIgnore attribute on your properties and they won’t be serialized.

That works, but I would like abstraction between my project and YamlDotNet.
