### ISSUE TITLE
Tests failing if current Culture setting does not use decimal point separator

### ISSUE THREAD

**Issue by jhm-ciberman** [aaubry/YamlDotNet#792]
**Describe the bug**
I just cloned the repo for the first time to contribute, and tried to run the test suite and it fails. I don't know if I am missing some step or what could be happening.

**To Reproduce**
- `git clone git@github.com:aaubry/YamlDotNet.git && cd YamlDotNet`
- `git submodule update --init`
- `dotnet restore`
- `dotnet test`

**dotnet test results**

https://gist.github.com/jhm-ciberman/2dbfe53d6aa41e10e61e0dbb9fea4d5a

I pasted it in a gist because it was too long to include it in the issue. (65536+ chars)

**Environment:**
```bash
$ dotnet --version
7.0.104
$ git --version
git version 2.37.3.windows.1
```

**Comment by EdwardCooke** [comment]
Have you made any changes to the code? These tests run every time code is merged on both windows and Linux machines without any problems.

**Comment by jhm-ciberman** [comment]
Nope. I cloned the repository at `master` as is.

Reading the logs in details it looks the failing test is the same, just repeated multiple times: 
```
[xUnit.net 00:00:02.79]     ConformsWithYamlSpec(name: "YD5X", description: "Spec Example 2.5. Sequence of Sequences", inputFile: "C:\\repos\\YamlDotNet\\YamlDotNet.Test\\yaml-test-"..., outputFile: "C:\\repos\\YamlDotNet\\YamlDotNet.Test\\yaml-test-"..., error: False, quoting: True) [FAIL]
  Failed ConformsWithYamlSpec(name: "YD5X", description: "Spec Example 2.5. Sequence of Sequences", inputFile: "C:\\repos\\YamlDotNet\\YamlDotNet.Test\\yaml-test-"..., outputFile: "C:\\repos\\YamlDotNet\\YamlDotNet.Test\\yaml-test-"..., error: False, quoting: True) [20 ms]
  Error Message:
   Assert.Equal() Failure
                                     ↓ (pos 57)
Expected: ···cGwire\r\n  - 65\r\n  - 0.278\r\n- - Sammy Sosa\r\n  - 63\r\n  - 0.288\r···
Actual:   ···cGwire\r\n  - 65\r\n  - 278\r\n- - Sammy Sosa\r\n  - 63\r\n  - 288\r\n
                                     ↑ (pos 57)
  Stack Trace:
     at YamlDotNet.Test.Spec.SerializerSpecTests.ConformsWithYamlSpec(String name, String description, String inputFile, String outputFile, Boolean error, Boolean quoting) in C:\repos\YamlDotNet\YamlDotNet.Test\Spec\SerializerSpecTests.cs:line 119
   at InvokeStub_SerializerSpecTests.ConformsWithYamlSpec(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

It looks a float parsing error I think. Could it be something related to the `Culture` of the system? I'm running Windows with a regional settings set to Argentina (My country). We use `,` (comma) as decimal separator instead of `.` decimal point.

![image](https://user-images.githubusercontent.com/7988351/228701258-28aa508c-c7ae-474b-bbe1-4fac40291f15.png)

**Comment by jhm-ciberman** [comment]
I just reproduced. I changed my regional settings to English (United States) and run `dotnet test` and now it passes fine:

![image](https://user-images.githubusercontent.com/7988351/228701370-2ff3f050-1bc2-4b52-8fe5-754a0ee3123d.png)

**Comment by EdwardCooke** [comment]
That was my next question after noticing the comma instead of a period in the exponential number of one of the failed tests. I think we can specify the culture at the process level when the test run starts so they can run in any country, maybe. It’s been a long time since I’ve had to deal with globalization and localization in any of my projects. 

I know the en_US culture works. Not sure how that plays on Linux/windows in other cultures without it installed in the is though.

I can make an attempt at testing it and try and find a workaround but it could be some time before I get a solution in place. If you would like to work on it let me know. Interesting problem.

**Comment by EdwardCooke** [comment]
Can you try adding this to the test csproj and see if the tests pass in your culture?

https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md#enabling-the-invariant-mode

**Comment by jhm-ciberman** [comment]
It fails
 
**CultureNotFoundException : Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information.**

```
[xUnit.net 00:00:01.55]     Given_Values_WithLocale_WriteYaml_ShouldReturn_Result(year: 2016, month: 12, day: 31, hour: 3, minute: 0, second: 0, kind: Utc, locale: "es-ES") [FAIL]
  Failed Given_Values_WithLocale_WriteYaml_ShouldReturn_Result(year: 2016, month: 12, day: 31, hour: 3, minute: 0, second: 0, kind: Utc, locale: "ko-KR") [2 ms]
  Error Message:
   System.Globalization.CultureNotFoundException : Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
ko-KR is an invalid culture identifier.
  Stack Trace:
     at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at YamlDotNet.Test.Serialization.DateTimeConverterTests.Given_Values_WithLocale_WriteYaml_ShouldReturn_Result(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, DateTimeKind kind, String locale) in C:\repos\YamlDotNet\YamlDotNet.Test\Serialization\DateTimeConverterTests.cs:line 522
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

But, I want to share some insights. The problem it seems are the tests that use `object.ToString()`. I tested this in a REPL console using my current culture (es-AR):

```csharp
> var ic = System.Globalization.CultureInfo.InvariantCulture;

> (2.70).ToString()
"2,7"             // Uses comma
> (2.70).ToString(ic)
"2.7"             // Uses point
> var value = 2.7;

> value.ToString()
"2,7"            // Uses comma
> string.Format(ic, "{0}", value)
"2.7"            // Uses point
```

The test that fails are `SerializerSpecTests.ConformsWithYamlSpec` for `float` and `double`, and `DeserializerTest.DeserializeScalarEdgeCases` for multiple specs

The `ConformsWithYamlSpec` uses `ToString` inside the test so it could be the test itself that is culture dependent.

In the other hand, for `DeserializeScalarEdgeCases` I don't see it uses `ToString` in the test itself, but rather inside the serializer. Maybe it's the serializer that is culture sensitive.

**Comment by EdwardCooke** [comment]
Ok. My next suggestion would be to set the globalization to en_US at the process level when the test runner starts

**Comment by jhm-ciberman** [comment]
I get fixed `DeserializeScalarEdgeCases`. The fix is easy as use an invariant culture in the test:

```diff
  [Theory]
  [MemberData(nameof(DeserializeScalarEdgeCases_TestCases))]
  public void DeserializeScalarEdgeCases(IConvertible value, Type type)
  {
      var deserializer = new DeserializerBuilder().Build();
+     var stringValue = string.Format(CultureInfo.InvariantCulture, "{0}", value);
-     var result = deserializer.Deserialize(value.ToString(), type);
+     var result = deserializer.Deserialize(stringValue, type);
  
      result.Should().Be(value);
  }
```

I will keep searching the root cause for `ConformsWithYamlSpec`

**Comment by jhm-ciberman** [comment]
I discovered the bug. In was a bug with the `ScalarNodeDeserializer`. So I think it's an important bug. I will make a PR with both fixes.

**Comment by jhm-ciberman** [comment]
@EdwardCooke I opened #793 and #794 to address both problems.
