### ISSUE TITLE
(Documentation) It is unclear how to perform a simple parse.

### ISSUE THREAD

**Issue by billpg** [aaubry/YamlDotNet#795]
The samples section of the documentation doesn't have a sample for taking a YAML string (or file or byte-array) and parsing it into a collection of objects. Perhaps a standard-library `Dictionary<string,something>` or a `YObject` to if YamlDotNet were to parallel NewtonSoft's `JObject`.

Note that I'm not asking about *deserialization*. I don't want to convert my YAML string into a class by looping through the data members of that class. I'm looking to take a step below that layer and access the contents of the YAML as a basic object notation language.

**Comment by SchreinerK** [comment]
I hope this helps:

```
string yaml = "your YAML code here";
var deserializer = new DeserializerBuilder().Build();

// Convert YAML to object
var yamlObject = deserializer.Deserialize(new StringReader(yaml));
Enumerate(yamlObject);

void Enumerate(object? yamlObject) {
    // Determine the type of the YAML object
    switch (yamlObject) {
        case IDictionary<string, object> dict: // Mapping
            foreach (var item in dict) 
                Console.WriteLine(@"{0}: {1}", item.Key, item.Value);
            break;
        case IList<object> list: // Sequence
            foreach (var item in list)
                Console.WriteLine(item);
            break;        
        default: // Scalar
            Console.WriteLine(yamlObject);
            break;
    }
}
```

**Comment by SchreinerK** [comment]
I hope this helps:

```
var reader = new StringReader("foo: bar");
var parser = new Parser(reader);
var level = 0;
while (parser.MoveNext()) {
    switch (parser.Current) {
        case Scalar sc:
            Console.WriteLine($@"<{parser.Current.GetType().Name}> '{sc.Value}' ({sc.Style})");
            break;
        case StreamStart: 
        case DocumentStart:
        case MappingStart:
        case SequenceStart: 
            level++; 
            goto default;
        case DocumentEnd:
        case StreamEnd:
        case MappingEnd:
        case SequenceEnd: 
            level--; 
            goto default;
        default:
            Console.WriteLine($@"<{parser.Current.GetType().Name}>");
            break;
    }
}
```

**Comment by billpg** [comment]
Thank you. I've not tried it yet but I'm going to presume that fragment works perfectly. Could it copied into the documentation as a sample? I'm sure I can't be the first person to wonder how to parse a YAML string without deserializing it into an object.

**Comment by SchreinerK** [comment]
@billpg I'm not a distributor I'm only a user ;-) and IMHO the only thing what you have to know for your question is `var parser = new Parser(reader)`. Everything else gives you the `parser ` while you use it to program your ideas. The best way (for me) to explore is to write unit tests.

**Comment by jjhayter** [comment]
> var parser = new Parser(reader);
If by hopes this helps you mean save my brain from melting at trying to walk through Ronaald Mak's Writing Compilers and Interpreters yet again then you nailed it!

**Comment by gregsdennis** [comment]
I found this works

```c#
public static YamlDocument Parse(string yamlText)
{
	using var reader = new StringReader(yamlText);
	var yamlStream = new YamlStream();
	yamlStream.Load(reader);
	var yaml = yamlStream.Documents.First();
	return yaml;
}
```

Of course, you could have multiple documents per file.  Modify to your need.

**Comment by billpg** [comment]
@gregsdennis - Thank you. I've not tried it out yet but could this fragment be copied into the documentation?

(If the project maintainer's don't want that kind of fragment in the samples section, this ticket should be closed as won't-fix.)

**Comment by gregsdennis** [comment]
> could this fragment be copied into the documentation?

I think it probably should be, but I have no control over that.

**Comment by EdwardCooke** [comment]
For @SchreinerK's example, we have this method which you can see used in the unit tests for validating the yaml.org's files

https://github.com/aaubry/YamlDotNet/blob/ae590e9ec723cc4dfb1b83a7819957c236c60198/YamlDotNet/RepresentationModel/LibYamlEventStream.cs#L45

Test:
https://github.com/aaubry/YamlDotNet/blob/ae590e9ec723cc4dfb1b83a7819957c236c60198/YamlDotNet.Test/Spec/ParserSpecTests.cs#L67

Our test library really is the best area for examples on how to use the library. We can of course add this to the wiki examples, but those are sparse and designed to be very basic examples of how to use it. Where using the parser and streams directly is a pretty advanced use case, not sure we want to go down that route.

**Comment by EdwardCooke** [comment]
I'm going to close this issue since there was working example code given.
