### ISSUE TITLE
(Question) Deep Merging Multiple Files

### ISSUE THREAD

**Issue by Cjewett** [aaubry/YamlDotNet#796]
Is this possible? We want to merge multiple Helm charts together and after stepping through the code it seems like this will always override instead of merging. https://github.com/aaubry/YamlDotNet/blob/f18356c28bd11465f9ba1f8451dfbd6ec3ffe919/YamlDotNet/Serialization/NodeDeserializers/DictionaryDeserializer.cs#L44

**Comment by EdwardCooke** [comment]
Can you put in a simple example of what your wanting to do and your expected output?

**Comment by EdwardCooke** [comment]
Did you want to put up an example of what you're trying to achieve? Or can I close this issue?

**Comment by Cjewett** [comment]
@EdwardCooke  Sorry about that we can close this. It's possible to convert to JSON, do a merge, and then convert back to YAML so there is a reasonable and reliable workaround.
