### ISSUE TITLE
How to emit an empty Scalar

### ISSUE THREAD

**Issue by SchreinerK** [aaubry/YamlDotNet#797]
emitter.Emit(new MappingStart());
emitter.Emit(new Scalar("Nothing"));
emitter.Emit(new Scalar()); ??? emitter.Emit(new Scalar(null);  ??? bug or missing feature?
emitter.Emit(new Scalar("EmptyString"));
emitter.Emit(new Scalar(""));
emitter.Emit(new MappingEnd());

as result:
```YAML
Nothing:
EmptyString: ''
```

The parser works fine:
```
<StreamStart>
<DocumentStart>
<MappingStart>
<Scalar> "Nothing" (Plain)
<Scalar> "" (Plain)    <-- here is the empty Scalar
<Scalar> "EmptyString" (Plain)
<Scalar> "" (SingleQuoted)
...
```
_It may also be that I am simply blind ;-)_

**Comment by EdwardCooke** [comment]
What is the yaml your trying to get back?

**Comment by SchreinerK** [comment]
The same as above 
```
Nothing:
EmptyString: ''
```
The serializer can do that, I just don't know how to achieve that with the emitter.

**Comment by EdwardCooke** [comment]
When you new up the scalar try setting the scalar style to plain and use an empty string.

**Comment by SchreinerK** [comment]
I think I tried all possible parameters, but only an empyt string `Nothing:: ' '` is written.

**Comment by SchreinerK** [comment]
The answer is:
```C#
emitter.Emit(new Scalar(AnchorName.Empty, new TagName("tag:yaml.org,2002:null"),  "", ScalarStyle.Plain, true, false));
```
I happened to find this in the code: `new TagName("tag:yaml.org,2002:null")`  and just tried it out to see what it does. 

But IMHO the following line would be more legible, only as a suggestion:
```
emitter.Emit(new Scalar(null));
````

**Comment by EdwardCooke** [comment]
Since there was an answer, I'm going to close this issue.
