### ISSUE TITLE
Naming convention not applied when deserializing?

### ISSUE THREAD

**Issue by FelicePollano** [aaubry/YamlDotNet#798]
Possibly a dumb question... I'm trying todeserialize a configuration in an object that have Pascal case properties. While deserializing the yaml ( that has lower cases ) I expect, by specifying Pascal case naming convention to have the property name properly assigned.

Minimal code to reproduce the problem 
``` csharp
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;
class Test
{
    public int Value { get; set; }
}

public class Program
{
    public static void Main()
    {
        var deserializer = new DeserializerBuilder().
                            WithNamingConvention(PascalCaseNamingConvention.Instance)
                            .Build();
        //throws : YamlDotNet.Core.YamlException: 'Property 'value' not found on type 'Test'.'
        var result = deserializer.Deserialize<Test>("value: 25");
    }
}
```

By inspecting the code I found troubles for me starts from here:
``` csharp
var propertyName = parser.Consume<Scalar>();
        if (duplicateKeyChecking && !consumedProperties.Add(propertyName.Value))
         {
                    throw new YamlException(propertyName.Start, propertyName.End, $"Encountered duplicate key {propertyName.Value}");
          }
          try
          {
                    var property = typeDescriptor.GetProperty(implementationType, null, propertyName.Value, ignoreUnmatched);
                    if (property == null)
                    {
                        parser.SkipThisAndNestedEvents();
                        continue;
                    }

```
so property name cames raw from yaml definition, and code try to match directly on the type, so in my case will never succed.
Is this by design? in this case why can't we have a naming convention applied on deserialization? Or I missing something? 

After more investigation here, looks a very similar issue #281 has been reported long time ago, OP says he found a solution, but he does not say which one...

**Comment by FelicePollano** [comment]
Found: naming convention has to be considered c#--->yaml so we have to use here CamelCaseNamingConvention

**Comment by Anton-V-K** [comment]
`CamelCaseNamingConvention` didn't help in my case.
However `UnderscoredNamingConvention` does the trick! :)
So the comments are a bit misleading...
