### ISSUE TITLE
(Documentation) Unclear how to deserialize into objects

### ISSUE THREAD

**Issue by graviaDaemon** [aaubry/YamlDotNet#805]
Beforehand: If this question is a duplicate I apologize

I came accross your package when I was trying to parse a markdown file into yaml and a body, which this seems perfect for, however I've come accross the package not deserializing because it's looking for a yaml syntax property in my object class, even with alias given.

Here's how I built, according to the documentation:

**Index.Code.cs**
```cs
using HttpClient client = new HttpClient();
        HttpResponseMessage response = await client
            .GetAsync("https://localhost:7052/uploads/fpsettings/settings.md");
        await using Stream stream = await response.Content.ReadAsStreamAsync();
        _settings = await stream
            .ParseSettingsAsync<FrontPageSettings>();
```

**Parser Helper class and Object classes (in which to parse)**
[MyFiddle](https://dotnetfiddle.net/k1d6I2)

The example Markdown
```md
---
title: FP Config
hero_settings:
  title: my title
  subtitle: test meuk
  button_text: mail
client_header:
  title: clients
  subtitle: of us
clients: []
services_header:
  title: services
  subtitle: services
expertise_header:
  title: expertise
  subtitle: stuff
about_header:
  title: about
  subtitle: about
about:
  - leadmct: true
    mct: true
    mvp: true
    title: bryce
    subtitle: manager
    image: url.to/image/path.png
partnerships_header:
  title: partnerships
  subtitle: partners
---
# Header
Here comes the markdown .Body property
```

But the error I receive is the following:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Property 'hero_settings' not found on type 'My.Namespace.Data.FrontPageSettings'.
```

Have I misunderstood the documentation, or is there something else happening I don't understand?

**Comment by EdwardCooke** [comment]
If there is a field in the yaml then that field/property needs to exist in the class you are deserializing. I believe there is a method you can call on the deserializerbuilder to skip that check. I think it’s named something like ignoremissingfields.

**Comment by graviaDaemon** [comment]
The field "hero_settings" exists both in the Yaml as well as the Class I'm deserializing, when I would use `IgnoreMissingFields()" it would skip that one entirely no? That's not what I want though. But if you look at the fiddle, it is a nested class

**Comment by EdwardCooke** [comment]
Just looked at your fiddle, can you try it without the naming convention line and see if that works?

**Comment by EdwardCooke** [comment]
Did removing the naming convention fix it?

**Comment by EdwardCooke** [comment]
Since I haven’t  heard back I’m closing this.
