### ISSUE TITLE
Set anchor tag name during serialization using YamlDotNet?

### ISSUE THREAD

**Issue by Nidhi1819** [aaubry/YamlDotNet#807]
This sounds interesting. Is there also an easy way to control the anchor naming during serialization? I would like to use YamlDotNet to create a stable file format, that changes as little as possible during multiple deserialize, change, serialize cycles, so different versions of the files can be compared and merged easily.

_Originally posted by @rohahn in https://github.com/aaubry/YamlDotNet/issues/227#issuecomment-311423294_

**Comment by EdwardCooke** [comment]
I think you can replace this implementation with your own and be able to create more meaningful names. However, you may not be able to get meaningful context to generate a name that makes sense. 

https://github.com/aaubry/YamlDotNet/blob/9a5900fb35e5cb668a77d2449b96f8bc85c179ba/YamlDotNet/Serialization/ObjectGraphVisitors/AnchorAssigner.cs#L29

**Comment by EdwardCooke** [comment]
Since there was a solution provided with no feedback I’m closing this issue. If you disagree go ahead and reopen it and we can discuss more.

**Comment by BBoldenow-Alt** [comment]
> Since there was a solution provided with no feedback I’m closing this issue. If you disagree go ahead and reopen it and we can discuss more.

@EdwardCooke - I think this is reasonable, but am having trouble getting the IAliasProvider implementation to trigger. I mostly copied the AnchorAssigner, but customized the name portion. I then provided this to my serializer like this:

```csharp
var anchorNaming = new CustomAnchorAssigner(new List<IYamlTypeConverter>()
{
    customConverter1,
    customConverter2,
    customConverter3,
});

var serializerBuilder = new SerializerBuilder()
    .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitEmptyCollections)
    .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull)
    .WithTypeConverter(customConverter1)
    .WithTypeConverter(customConverter2)
    .WithTypeConverter(customConverter3)
    .WithPreProcessingPhaseObjectGraphVisitor(anchorNaming)
```

This triggers all of the `VisitObject` events, but the `GetAlias` method is never called. Is there something I'm missing to use this Alias Provider?

**Comment by Schrolli91** [comment]
@BBoldenow-Alt @EdwardCooke 
I am a little bit confused, how to implement that.
Is there a little more complete example, how to get a custom anchor naming working?

**Comment by EdwardCooke** [comment]
Please open a new issue and I’ll try and build out an example in the next bit. I have very limited access to the internet right now.
