### ISSUE TITLE
Emitter doesn't handle comments between the mapping value and key

### ISSUE THREAD

**Issue by YihaoOct** [aaubry/YamlDotNet#812]
**Describe the bug**

When there is a comment after a mapping key and before the value, the Emitter doesn't generate the correct YAML output.

Examples are:

Inline comment:

```yaml
hello: # comment
  - world
```

Parse it and emit it again, the output will be:
```
hello # this is a comment:
- world
```

Standalone comment:

```yaml
hello:
  # comment
  - world
```

Parse it and emit it again, the output will be:
```
hello
# this is a comment
:
- world
```

**To Reproduce**

Checkout the branch for this PR: https://github.com/aaubry/YamlDotNet/pull/811

Run and debug the two new test cases, see the broken output.

**Comment by EdwardCooke** [comment]
Well that would be an annoying bug....I'll take a look at this and see about merging it in today.
