### ISSUE TITLE
Parser does not recognize quoted keys

### ISSUE THREAD

**Issue by matyas2szabo** [aaubry/YamlDotNet#817]
I'm using the Parser class to read in YAML content.
When the Parser instance encounters a mapping key which is double quoted or single quoted, it returns a Scalar ParsingEvent in the Current property (it is OK), but fails to set IsKey true (this is the bug).

So parsing up YAML content, like:
```
"name": "John"
```
fails as "name" is recognized as plain scalar and not a key. This makes parsing JSON content impossible for me, as correct JSON like
```
{ "name": "John" }
```
also fails.

If I remove the single or double quotes from around the mapping keys, everything works just fine.

The issue is present in releases 13.1.0 and 13.0.2 at least.

**Comment by EdwardCooke** [comment]
What about pre 12.0? I added the IsKey somewhere in the 12.x line. Can't remember exactly which version.

**Comment by EdwardCooke** [comment]
Found the bug. The fix will go out in the next release :)
