### ISSUE TITLE
Do you think it's useful to add some F# examples along with the C# code?

### ISSUE THREAD

**Issue by 64J0** [aaubry/YamlDotNet#822]
## Description

Hello, hope you're good. I noticed that this project lacks some F# code examples, and I would like to know if you think it makes sense to add those.

If you think it makes, I can start working on it.

---

Feel free to ask any question on how to use the library. Alternatively, consider asking the question on [Stackoverflow](https://stackoverflow.com), tagged with [yamldotnet](https://stackoverflow.com/questions/tagged/yamldotnet).

**Comment by EdwardCooke** [comment]
The one thing I worry about with doing another samples project is maintaining it going forward. We have the c# one that doesn’t really get anything new added to it. Let me think about this some more and if you want to create a pr with a single simple sample so I can see what your thinking go for it.

**Comment by 64J0** [comment]
Sounds good, I'll do it later today @EdwardCooke

**Comment by 64J0** [comment]
There it go: https://github.com/aaubry/YamlDotNet/pull/824

**Comment by 64J0** [comment]
I thought this issue would be closed automatically. But I'll do it manually. Thanks @EdwardCooke! 🚀
