### ISSUE TITLE
How to Serialize an object with Directives, start and end marks (---, ...)?

### ISSUE THREAD

**Issue by Develeon64** [aaubry/YamlDotNet#829]
Hello there!
Thanks for your library. I really enjoy using it, because it's very streight forward and works very simple :)

I only miss one information: How can I serialize to full document with maximum information (version specification, document start and end) like
```yaml
%YAML 1.2
---
<serialized things here>
...
\n
```

**Comment by EdwardCooke** [comment]
Since I gave an answer and I haven't heard back, I'm going to close the issue.
