### ISSUE TITLE
YamlStream.Load with JSON with emojis (even escaped) fails: "While scanning a quoted scalar, found invalid Unicode character escape code."

### ISSUE THREAD

**Issue by cmeeren** [aaubry/YamlDotNet#838]
I am serializing something to JSON with System.Text.Json, and then converting it to YAML using `YamlStream`. However, if the JSON contains an emoji, even if it's escaped, `YamlStream.Load` throws:

> (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 4, Idx: 3): While scanning a quoted scalar, found invalid Unicode character escape code.

Code to reproduce:

```f#
open System.IO
open System.Text.Json
open YamlDotNet.RepresentationModel

let input = "👍"

let json = JsonSerializer.Serialize input

assert (json = "\"\\uD83D\\uDC4D\"")

let yamlStream = YamlStream()
yamlStream.Load(new StringReader(json))
```

**Comment by cmeeren** [comment]
UTF-16? But JSON is always UTF-8 by definition, isn't it?

**Comment by cmeeren** [comment]
Also, AFAIK many emojis are composed of 2 or more unicode characters. [This SO question and answers](https://stackoverflow.com/questions/33642339/how-is-a-high-unicode-codepoint-expressed-as-two-codepoints) may be helpful.

Finally, I _highly_ doubt that System.Text.Json (the official .NET JSON serialization API) is doing things wrong.

**Comment by EdwardCooke** [comment]
This will also help me in getting a fix in

https://github.com/dotnet/runtime/issues/42847
There’s some other linked issues that should help clarify the nuances in Unicode.

not sure when I’ll get it done though.

**Comment by cmeeren** [comment]
Is there any workaround I can apply now, for converting JSON to YAML? The emojis etc. doesn't have to be unescaped; I'm OK with anything that preserves the escape codes. I just want my JSON content converted to YAML (tweaked using a YAML visitor).

**Comment by cmeeren** [comment]
Ideally I would like unescaped output (i.e., emojis in the YAML), but at least the following workaround lets me preserve the surrogate pair escape codes:

```f#
let unicodeEscapeCodePlaceholder = Guid.NewGuid().ToString()

let escapeUnicodeEscapeCodes (str: string) =
    str.Replace(@"\u", unicodeEscapeCodePlaceholder)

let unEscapeUnicodeEscapeCodes (str: string) =
    str.Replace(unicodeEscapeCodePlaceholder, @"\u")

let formatAsYaml json =
    let json = escapeUnicodeEscapeCodes json
    let yaml = (* load with YamlStream and transform to YAML *)
    unEscapeUnicodeEscapeCodes yaml
```

**Comment by EdwardCooke** [comment]
I definitely do agree that utf8 surrogate pairs should be supported. I’m hoping to have some time this weekend to look at it. I did find where it was throwing a fit though.

**Comment by cmeeren** [comment]
Happy to hear it! 😁

**Comment by cmeeren** [comment]
Thanks! I have no idea what the internals of YamlDotNet is doing, but wouldn't it work to just keep the loaded text as-is and not attempting to decode the escape sequences, which is seems like it's doing now?

**Comment by EdwardCooke** [comment]
This fix is going to be released in the latest nuget package which should be available in about 10-15 minutes.

**Comment by cmeeren** [comment]
It works. Thanks a lot! 😊
