### ISSUE TITLE
DynamicYaml capitalization problem

### ISSUE THREAD

**Issue by IHS-Gdansk** [aaubry/YamlDotNet#85]
I've cloned repository, opened in VS.NET 2013 and fired up unit tests. One test "TestNonExistingMember" was failing with "YamlDotNet.Dynamic.DynamicYaml' to 'int?' since TryGetMember implementation inside returns DynamicYaml created from null YamlNode whenever member is not found.
Also for another test "TestMappingNode" the beginnig of MappingYaml I would change from:
private const string MappingYaml = @"---
            receipt:    Oz-Ware Purchase Invoice

into
private const string MappingYaml = @"---
            Receipt:    Oz-Ware Purchase Invoice

capitalizing receipt key then the test would also fail. This is also because decapitalized key search is done first and "empty" DynamicYaml is returned and capitalized search for Receipt is never actually done.

I discovered this when I was using YamlDotNet.Dynamic on my project and I had capitalized key names in my yaml files.

Would it be ok if TryGetValueByKeyAndType tried both capitalized and decapitalized keys and only then decide to return empty DynamicYaml?

Something like this:

		private bool TryGetValueByKeyAndType(string key, Type type, out object result)
		{
			if (mappingNode == null)
			{
				return FailToGetValue(out result);
			}
			var decapitalizedKey = new YamlScalarNode(key.Decapitalize());
			var capitalizedKey = new YamlScalarNode(key.Capitalize());
			
            if(TryGetValueByYamlKeyAndType(decapitalizedKey, out result)) 
                return true;
		    
            if (TryGetValueByYamlKeyAndType(capitalizedKey, out result))
		        return true;

            return IsNullableType(type) ? SuccessfullyGetValue(new DynamicYaml((YamlNode)null), out result) : FailToGetValue(out result);
		}

		private bool TryGetValueByYamlKeyAndType(YamlScalarNode yamlKey, out object result)
		{
			if (mappingNode.Children.ContainsKey(yamlKey))
			{
				var value = mappingNode.Children[yamlKey];
				if (YamlDoc.TryMapValue(value, out result))
				{
					return true;
				}
			}
            result = null;
		    return false;
		}

**Comment by aaubry** [comment]
Closing this because the issue probably no longer exists. Please open a new issue if you still encounter this bug.
