### ISSUE TITLE
Add support for including types defined in another assembly in static code generation

### ISSUE THREAD

**Issue by prochnowc** [aaubry/YamlDotNet#851]
**Is your feature request related to a problem? Please describe.**
My serializable types are defined in some 3rd party assembly and I can not add the `[YamlSerializable]` attribute.

**Describe the solution you'd like**
I would like the static code generator to include types defined in another assembly.

**Comment by EdwardCooke** [comment]
Since this is now complete, I'm closing the issue. Thank you for taking care of it so quickly.
