### ISSUE TITLE
Add quotes for strings on model serialization

### ISSUE THREAD

**Issue by sunnamed434** [aaubry/YamlDotNet#869]
I want to add quotes for strings when serializing a model (class), but adding attributes on properties is not my case - because I want it automated.

I checked issues on this GitHub repo and stackoverflow to find answers to my question, but without success, I saw solutions but they either did not work or just added the quotes for everything.

I think about smth like this, I guess there should be a way to do that via event emitter or in another way.
```cs
var yamlSerializer = new SerializerBuilder()
                        .WithQuotesForStrings()
                        .Build();
```

```console
Before:

- Id: Item1
  Value: Hello world 1!
- Id: Item2
  Value: Hello world 2!
- Id: Item3
  Value: 10
- Id: Item4
  Value: true

After:

- Id: "Item1"
  Value: "Hello world 1!"
- Id: "Item2"
  Value: "Hello world 2!"
- Id: "Item3"
  Value: 10
- Id: "Item4"
  Value: true
```

**Comment by EdwardCooke** [comment]
I’m pretty sure there’s a withdefaultquountingstyle method on the serializerbuilder that was added recently.

**Comment by EdwardCooke** [comment]
It’s DefaultScalarStyle

https://github.com/aaubry/YamlDotNet/blob/847230593e95750d4294ca72c98a4bd46bdcf265/YamlDotNet/Serialization/SerializerBuilder.cs#L126C16-L126C16

**Comment by sunnamed434** [comment]
Thanks, solved!

```cs
var yamlSerializer = new SerializerBuilder()
                        .WithNamingConvention(CamelCaseNamingConvention.Instance)
                        .WithDefaultScalarStyle(ScalarStyle.DoubleQuoted) // add this line
                        .Build();
```
