### ISSUE TITLE
Problem Deserializing a list of player

### ISSUE THREAD

**Issue by robinmoon2** [aaubry/YamlDotNet#875]
Hello, I have a problem. 
I have a code that can write this kind of YAML file : 
- name: p1
  timer: 60
  score: 1
- name: p2
  timer: 60
  score: 1
Where one (name,timer,score) is for 1 player which is a class in my code. 

I use the serializer to write the YAML file and it works pretty well. But when I need to read it with the deserializer and put it in a list of players it doesn't work and I have the error message following : 
Unhandled exception. (Line: 1, Col: 3, Idx: 2) - (Line: 1, Col: 3, Idx: 2): Exception during deserialization.

I put the 2 function below, if someone have the solution it will really help me out.

![image](https://github.com/aaubry/YamlDotNet/assets/77844158/1fa889d5-9a79-4cc9-8650-4a1bc0079e00)

**Comment by EdwardCooke** [comment]
Can you your entire player class? There should also be more details on that exception as well.

**Comment by robinmoon2** [comment]
So this is the player class : 
![image](https://github.com/aaubry/YamlDotNet/assets/77844158/c09fdcae-d465-4209-94c7-181d4c93f9e0)

Then I built the PlayerList class : 
![image](https://github.com/aaubry/YamlDotNet/assets/77844158/6bc0e94e-2747-4c3f-accb-c330f13731b2)

And this is where I call the function to Read and Write on the YAML File.

The function Writing works perfectly but not the reading one. 

What do you mean by "Can you your entire player class" ? 

I don't find any more details about this exception on the repo.

**Comment by EdwardCooke** [comment]
You need a parameterless constructor on your player class. Add that in there and it should work.
