### ISSUE TITLE
Getting Following Error for YamlDotNet.NetCore

### ISSUE THREAD

**Issue by ssavi-ict** [aaubry/YamlDotNet#883]
Hello There, 
I am trying to add YamlDotNet.NetCore in my project for parsing a YAML. It is showing the following errors. 
```<TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>```
```
System.IO.FileNotFoundException: 'Could not load file or assembly 'YamlDotNet, Version=13.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e' or one of its dependencies. The system cannot find the file specified.'
```

Thanks.

**Comment by EdwardCooke** [comment]
Don’t use that package. Use just YamlDotNet.

**Comment by EdwardCooke** [comment]
Did that fix your problem?

**Comment by ssavi-ict** [comment]
Hello @EdwardCooke, I used YamlDotNet. Thank You.
