### ISSUE TITLE
IEnumerable support in StaticGenerator

### ISSUE THREAD

**Issue by tg123** [aaubry/YamlDotNet#884]
**Is your feature request related to a problem? Please describe.**

```
    // public List<string>? MyList { get; set; }
    public IEnumerable<string>? MyList { get; set; }
```

allow `IEnumerable`/`IReadOnlyList`/`IList` in StaticGenerator

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by EdwardCooke** [comment]
In addition to those interfaces, I’m adding collection and ireadonlydictionary. The code is complete and working. Just need stable WiFi.

**Comment by EdwardCooke** [comment]
This is released and working now.
