### ISSUE TITLE
YamlDotNet does not write accurately equal to yaml being loaded

### ISSUE THREAD

**Issue by lx1988** [aaubry/YamlDotNet#892]
Example input file any scene from Unity3D. Example code:

var input = new StringReader(File.ReadAllText("Scene1.unity"));
var yaml = new YamlStream();
yaml.Load(input);
var tw = File.CreateText(sc.path + ".yaml");
yaml.Save(tw,false);
Verification shell command:
diff Scene1.unity Scene1.unity.yaml
^ got totally different result
![image](https://github.com/aaubry/YamlDotNet/assets/6447069/deadadbd-0516-430a-9452-4163fc7c5f8a)

**Comment by EdwardCooke** [comment]
Please post an example reproduction of the yaml for the problem.

**Comment by EdwardCooke** [comment]
This is probably due to aliases being enabled by default. Use disablealiases or something like that in your serializerbuilder and it should match.
