### ISSUE TITLE
JsonCompatible serializer is not Json compatible

### ISSUE THREAD

**Issue by Rackover** [aaubry/YamlDotNet#893]
**Describe the bug**
When serializing an object that contains an infinity float, the YAML DotNet serializer in JsonCompatible mode produces a JSON that contains the keyword `.inf` . 
According to JSON spec it should write `null`, otherwise i suppose writing a very big number or enclosing `.inf` with quotes would be appreciated. Currently the JSON produced by the serializer in that context is unusable for other parsers that expect valid data.

**To Reproduce**
```
 YamlDotNet.Serialization.SerializerBuilder serializerBuilder = new();
 serializerBuilder.JsonCompatible();
 serializerBuilder.WithIndentedSequences();

 var serializer = serializerBuilder.Build();

class Test
{
float a = float.PositiveInfinity;
}

var str = serializer.Serialize(a);
Console.Write(str);
```

**Comment by EdwardCooke** [comment]
Thanks for the report. It’s on my todo list. Might be a bit before I get to it. If you need it sooner go ahead and create a pr. You’ll need to handle other data types like double as well.

**Comment by Rackover** [comment]
Might have invented it, it seems the real status of Infinity and NaN is unclear:
https://www.ietf.org/rfc/rfc4627.txt

So it could be Null, it could be Undefined, or as someone proposed here https://stackoverflow.com/a/28763430/6230450 it could be the string "Infinity". Either choice is good I suppose as long as the final produced JSON is valid to deserialize.

**Comment by Rackover** [comment]
```
            string serialized = serializer.Serialize(heatpoint);
            Regex reg = new Regex("(\":) (\\.inf)");
            serialized = reg.Replace(serialized, "$1 0");
```

Currently using this as a workaround whenever i do any JSON serialization with the YAMLDotNet serializer (in case this helps anyone)

**Comment by EdwardCooke** [comment]
This will be fixed in the next release.
