### ISSUE TITLE
Set license expression on nuget package

### ISSUE THREAD

**Issue by thompson-tomo** [aaubry/YamlDotNet#918]
**Is your feature request related to a problem? Please describe.**
When my packages are analyzed in Dependency Track using SBOM files the licence is not able to be determined for any of the packages.

**Describe the solution you'd like**
The PackageLicenseExpression property is set in the csproj so that the NUGET package has the information. This can then be included in the SBOM so that analysis can occur in the appropriate tools.

**Describe alternatives you've considered**
Ignore the errors.

**Additional context**
License appears to be MIT

**Comment by lahma** [comment]
https://github.com/aaubry/YamlDotNet/pull/903
