### ISSUE TITLE
IncludeNonPublicProperties() broken in 16.0.0

### ISSUE THREAD

**Issue by dsdante** [aaubry/YamlDotNet#952]
After updating from 15.3.0 to 16.0.0 the deserializer no longer sees private/internal/etc properties even when built with `DeserializerBuilder.IncludeNonPublicProperties()`.

```csharp
// Program.cs
using YamlDotNet.Serialization;

using StreamReader file = new("test.yaml");
var result = new DeserializerBuilder()
    .IncludeNonPublicProperties()
    .Build()
    .Deserialize<Test>(file);
Console.WriteLine(result.PublicValue);

class Test
{
    [YamlMember(Alias = "key")]
    private string YamlValue { get; set; } = null!;

    public string PublicValue => YamlValue;
}
```
```yaml
# test.yaml
key: value
```

**Comment by EdwardCooke** [comment]
Thanks for the report. I’ll take a look at this as soon as I can.

**Comment by EdwardCooke** [comment]
Ok, just looked at it, I'll have a fix for it. What it really is is that `YamlMember` isn't read on non public properties/fields. For example, using the following yaml works:
```yaml
YamlValue: value
```

**Comment by EdwardCooke** [comment]
It's actually already fixed by a different commit going out in the next release. I have added a regression test so it doesn't happen again.
