### ISSUE TITLE
Question: Possible to work with comments?

### ISSUE THREAD

**Issue by Dynalon** [aaubry/YamlDotNet#96]
Hi,

I am considering YamlDotNet for a Project and looked at the Samples, but I have a question: Is it possible to work with the comments of a yaml file? I.e. parse them into some kind of datatype when deserializing?

I want the basic workflow: Read in a YAML file, modify some data fields, and write out to another yaml file. The comments should be maintained (but not modified) in the process. Is this possible?

**Comment by iouris** [comment]
Hi Roger,

how would you advise to go about reading yaml, making changes to it then saving it at the same time ensuring that the comments are preserved as they were?

Thanks

**Comment by ryanpagel** [comment]
@iouris  I'm interested in the same.
