### ISSUE TITLE
Type information lost when assigning to generic dictionaries

### ISSUE THREAD

**Issue by dhgoldman** [aaubry/YamlDotNet#97]
If I store an associative array with values of mixed types, e.g.:

```
var properties = new Dictionary<string, object>
{
    { "Name", "One" },
    { "Number", 1 },
    { "Double", 3.14 }
}
...
serializer.Serialize(writer, properties);
```

When I retrieve such a structure, the type information for both "Number" and "Double" are lost; instead, they are returned as strings.

```
var properties = deserializer.Deserialize<Dictionary<string, object>>(reader);
```

However, as the standard indicates that numbers stored as strings should be delineated with double quotes and otherwise treated as numbers, the deserializer should probably try to cast the value appropriately before populating the dictionary.

**Comment by aaubry** [comment]
This should be handled by schemas. Work has been started on this, but it is not yet ready.
