### ISSUE TITLE
Allow extending genericInterfaceImplementations of DefaultObjectFactory

### ISSUE THREAD

**Issue by n9** [aaubry/YamlDotNet#982]
**Is your feature request related to a problem? Please describe.**

It seems to me that there is currently no way to extend `defaultGenericInterfaceImplementations` of `DefaultObjectFactory`.

https://github.com/aaubry/YamlDotNet/blob/485daaa7fa2a9fdc5863294ef580b880aac6a4df/YamlDotNet/Serialization/ObjectFactories/DefaultObjectFactory.cs#L45-L51

Mappings are only added to `defaultNonGenericInterfaceImplementations`.

https://github.com/aaubry/YamlDotNet/blob/485daaa7fa2a9fdc5863294ef580b880aac6a4df/YamlDotNet/Serialization/ObjectFactories/DefaultObjectFactory.cs#L75-L83

**Describe the solution you'd like**

Provide a "simple" way to extend `defaultGenericInterfaceImplementations`.

**Describe alternatives you've considered**

Modify copy of `DefaultObjectFactory`.

**Additional context**

N/A

**Comment by EdwardCooke** [comment]
How are you wanting to extend that class? If you're wanting to add additional types you can do that by passing in a dictionary of type mappings. That linked method is just making sure the types are assignable and making a copy of the passed in dictionary. We could remove the `sealed` part of the class so you could extend it, that wouldn't be hard at all.

**Comment by n9** [comment]
Yes, that will be sufficient.

Moreover, I realized that in my case extending `defaultGenericInterfaceImplementations` does not help, I need to create an INodeTypeResolver (as suggested here https://github.com/aaubry/YamlDotNet/issues/236#issuecomment-632054372).

But for mapping-like collections, I also need to tweak the serialization (mentioned here https://github.com/aaubry/YamlDotNet/issues/236#issuecomment-2373863417). Currently, I do the following:

```C#
static readonly IObjectFactory objectFactoryForSerialization = new CustomObjectFactoryForSerialization();

...

.WithObjectGraphTraversalStrategyFactory((typeInspector, typeResolver, typeConverters, maximumRecursion) =>
    new FullObjectGraphTraversalStrategy(typeInspector, typeResolver, maximumRecursion, CamelCaseNamingConvention.Instance, objectFactoryForSerialization))
```

Where `CustomObjectFactoryForSerialization` is this:

```C#
public class CustomObjectFactoryForSerialization : ObjectFactoryBase
{
    public override bool GetDictionary(IObjectDescriptor descriptor, out IDictionary? dictionary, out Type[]? genericArguments)
    {
        genericArguments = descriptor.Type.GetInterfaceGenericArguments(typeof(IReadOnlyDictionary<,>));
        if (genericArguments != null)
        {
            dictionary = (IDictionary)Activator.CreateInstance(typeof(ReadOnlyDictionaryAdapter<,>).MakeGenericType(genericArguments), descriptor.Value)!;
            return true;
        }
        return base.GetDictionary(descriptor, out dictionary, out genericArguments);
    }

    public override object Create(Type type) => throw new NotSupportedException();
}
```

Since I cannot currently derive from `DefaultObjectFactory`.

Removing `sealed` from `DefaultObjectFactory` will also help in this case, I would be able to derive from `DefaultObjectFactory` instead of `ObjectFactoryBase`.

**Comment by EdwardCooke** [comment]
Sounds good, it'll be done.
