### ISSUE TITLE
IDataReader type converter

### ISSUE THREAD

**Issue by riezebosch** [aaubry/YamlDotNet#989]
I created this extension on `YamlDotNet`: https://github.com/riezebosch/YamlDotNetDataReader/. Maybe it is something you want to include in the main library or publish it as an official companion library? The only (new) dependency is on [`Microsoft.Data.SqlClient`](https://github.com/riezebosch/YamlDotNetDataReader/blob/main/YamlDotNetDataReader/YamlDotNetDataReader.csproj#L11) which you may already have since I saw some checks on `DBNull` already?

**Comment by EdwardCooke** [comment]
We currently have no dependencies in yamldotnet and it’s something we’d really like to stay that way. It makes it easier for consumers of the package.

**Comment by riezebosch** [comment]
https://github.com/aaubry/YamlDotNet/blob/7923dd8e600f7fea7710f3b45f3fadcfa1aa589c/YamlDotNet/ReflectionExtensions.cs#L201
